<?php 
    $about_dis = search_array('AboutDiscribtion',$config_system);
    $about_vision = search_array('about our vision',$config_system);
?>

<main class="about-page">
        <section class="section-about-page-heading">
            <div class="container">
                <div class="about-page-hero">
                    <div class="hero-side-1" data-aos="fade-right" data-aos-duration="1000">
                        <img src="<?php echo $image;?>E-com.png" alt="hero-img-1">
                    </div>
                    <div class="hero-side-2">
                        <h1>ABOUT   US</h1>
                    </div>
                    <div class="hero-side-3" data-aos="fade-left" data-aos-duration="1000">
                        <img src="<?php echo $image;?>marketingbg.png" alt="hero-img-2">
                    </div>
                </div>
            </div>
        </section>
        <section class="section-about-content">
            <div class="container">
                <div class="about-content">
                    <div class="content-right-side" data-aos="fade-up-right">
                        <?php echo $about_dis['value'] ; ?>    
                    </div>
                    <div class="content-left-side"data-aos="fade-up-left">
                        <img src="<?php echo $image;?>marketingbg.png" alt="content-section logo">
                    </div>
                </div>
            </div>
        </section>
        <!-- <section class="team">
            <h1>OUR TEAM</h1>
        </section>
        <section class="about-our-team">
            <div class="container">
                <div class="about-team-content">
                    <div class="card-row">
                        <div class="team-card"data-aos="flip-left">
                            <div class="team-card-upper"><img src="<?php echo $image;?>103246918_3311308415570414_1526472155788251672_o.jpg" alt="team-img"></div>
                            <div class="team-card-content">
                                <div class="team-name">Muzzamil Qureshi</div>
                                <div class="team-position">Graphics Designer / Front-end Dev</div>
                                <div class="team-depart">Nazreen Consulting</div>
                            </div>
                        </div>
                        <div class="team-card"data-aos="flip-up">
                            <div class="team-card-upper"><img src="<?php echo $image;?>103246918_3311308415570414_1526472155788251672_o.jpg" alt="team-img"></div>
                            <div class="team-card-content">
                                <div class="team-name">Muzzamil Qureshi</div>
                                <div class="team-position">Graphics Designer / Front-end Dev</div>
                                <div class="team-depart">Nazreen Consulting</div>
                            </div>
                        </div>
                        <div class="team-card"  data-aos="flip-down">
                            <div class="team-card-upper"><img src="<?php echo $image;?>103246918_3311308415570414_1526472155788251672_o.jpg" alt="team-img"></div>
                            <div class="team-card-content">
                                <div class="team-name">Muzzamil Qureshi</div>
                                <div class="team-position">Graphics Designer / Front-end Dev</div>
                                <div class="team-depart">Nazreen Consulting</div>
                            </div>
                        </div>
                        <div class="team-card" data-aos="flip-right">
                            <div class="team-card-upper"><img src="<?php echo $image;?>103246918_3311308415570414_1526472155788251672_o.jpg" alt="team-img"></div>
                            <div class="team-card-content">
                                <div class="team-name">Muzzamil Qureshi</div>
                                <div class="team-position">Graphics Designer / Front-end Dev</div>
                                <div class="team-depart">Nazreen Consulting</div>
                            </div>
                        </div>
                    </div>
                    <div class="card-row">
                        <div class="team-card"data-aos="flip-right">
                            <div class="team-card-upper"><img src="<?php echo $image;?>103246918_3311308415570414_1526472155788251672_o.jpg" alt="team-img"></div>
                            <div class="team-card-content">
                                <div class="team-name">Muzzamil Qureshi</div>
                                <div class="team-position">Graphics Designer / Front-end Dev</div>
                                <div class="team-depart">Nazreen Consulting</div>
                            </div>
                        </div>
                        <div class="team-card"data-aos="flip-up">
                            <div class="team-card-upper"><img src="<?php echo $image;?>103246918_3311308415570414_1526472155788251672_o.jpg" alt="team-img"></div>
                            <div class="team-card-content">
                                <div class="team-name">Muzzamil Qureshi</div>
                                <div class="team-position">Graphics Designer / Front-end Dev</div>
                                <div class="team-depart">Nazreen Consulting</div>
                            </div>
                        </div>
                        <div class="team-card" data-aos="flip-right">
                            <div class="team-card-upper"><img src="<?php echo $image;?>103246918_3311308415570414_1526472155788251672_o.jpg" alt="team-img"></div>
                            <div class="team-card-content">
                                <div class="team-name">Muzzamil Qureshi</div>
                                <div class="team-position">Graphics Designer / Front-end Dev</div>
                                <div class="team-depart">Nazreen Consulting</div>
                            </div>
                        </div>
                        <div class="team-card" data-aos="flip-left">
                            <div class="team-card-upper"><img src="<?php echo $image;?>103246918_3311308415570414_1526472155788251672_o.jpg" alt="team-img"></div>
                            <div class="team-card-content">
                                <div class="team-name">Muzzamil Qureshi</div>
                                <div class="team-position">Graphics Designer / Front-end Dev</div>
                                <div class="team-depart">Nazreen Consulting</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section> -->
        <section class="vision-heading">
            OUR Vision
        </section>
        <section class="about-ourvision">
            <div class="container">
                <div class="about-vision-content">
                        <div class="vison-left" data-aos="zoom-out-up">
                            <img src="<?php echo $image;?>E-com.png" alt="vision-img">
                        </div>
                        <div class="vison-right" data-aos="zoom-out-up">
                            <?php echo $about_vision['value'] ; ?>
                        </div>
                </div>
            </div>
        </section>
        <section class="about-social">
            Join us
        </section>        
        <section class="social">
            <div class="container">
                <div class="about-social-icons" data-aos="fade-up"
                data-aos-duration="1500">
                   <a href="#"><i class="fa fa-facebook-square" aria-hidden="true"></i></a>
                    <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                    <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                    <a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a>
                </div>
            </div>
        </section>
    </main>