<main class="about-page">
        <section class="section-about-page-heading">
            <div class="container">
                <div class="about-page-hero">
                    <div class="hero-side-1" data-aos="fade-right" data-aos-duration="1000">
                        <img src="<?php echo $image;?>E-com.png" alt="hero-img-1">
                    </div>
                    <div class="hero-side-2">
                        <h1>ABOUT   US</h1>
                    </div>
                    <div class="hero-side-3" data-aos="fade-left" data-aos-duration="1000">
                        <img src="<?php echo $image;?>marketingbg.png" alt="hero-img-2">
                    </div>
                </div>
            </div>
        </section>
        <section class="section-about-content">
            <div class="container">
                <div class="about-content">
                    <div class="content-right-side" data-aos="fade-up-right">
                        <p>Have you thought that selling online was a little out of your reach? Think again. Opening an online store has never been easier. <b>ServeWise</b> is a leading choice for small business merchants to easily set up a store and start selling fast. No need to abandon your existing site — <b>ServeWise</b> can be added virtually anywhere you have an online presence. You have the freedom to operate multiple online stores including on your website, social media channels, and mobile devices. So stop reading and start selling from your new online store!</p>
                    </div>
                    <div class="content-left-side"data-aos="fade-up-left">
                        <img src="<?php echo $image;?>marketingbg.png" alt="content-section logo">
                    </div>
                </div>
            </div>
        </section>
        <section class="team">
            <h1>OUR TEAM</h1>
        </section>
        <section class="about-our-team">
            <div class="container">
                <div class="about-team-content">
                    <div class="card-row">
                        <div class="team-card"data-aos="flip-left">
                            <div class="team-card-upper"><img src="<?php echo $image;?>103246918_3311308415570414_1526472155788251672_o.jpg" alt="team-img"></div>
                            <div class="team-card-content">
                                <div class="team-name">Muzzamil Qureshi</div>
                                <div class="team-position">Graphics Designer / Front-end Dev</div>
                                <div class="team-depart">Nazreen Consulting</div>
                            </div>
                        </div>
                        <div class="team-card"data-aos="flip-up">
                            <div class="team-card-upper"><img src="<?php echo $image;?>103246918_3311308415570414_1526472155788251672_o.jpg" alt="team-img"></div>
                            <div class="team-card-content">
                                <div class="team-name">Muzzamil Qureshi</div>
                                <div class="team-position">Graphics Designer / Front-end Dev</div>
                                <div class="team-depart">Nazreen Consulting</div>
                            </div>
                        </div>
                        <div class="team-card"  data-aos="flip-down">
                            <div class="team-card-upper"><img src="<?php echo $image;?>103246918_3311308415570414_1526472155788251672_o.jpg" alt="team-img"></div>
                            <div class="team-card-content">
                                <div class="team-name">Muzzamil Qureshi</div>
                                <div class="team-position">Graphics Designer / Front-end Dev</div>
                                <div class="team-depart">Nazreen Consulting</div>
                            </div>
                        </div>
                        <div class="team-card" data-aos="flip-right">
                            <div class="team-card-upper"><img src="<?php echo $image;?>103246918_3311308415570414_1526472155788251672_o.jpg" alt="team-img"></div>
                            <div class="team-card-content">
                                <div class="team-name">Muzzamil Qureshi</div>
                                <div class="team-position">Graphics Designer / Front-end Dev</div>
                                <div class="team-depart">Nazreen Consulting</div>
                            </div>
                        </div>
                    </div>
                    <div class="card-row">
                        <div class="team-card"data-aos="flip-right">
                            <div class="team-card-upper"><img src="<?php echo $image;?>103246918_3311308415570414_1526472155788251672_o.jpg" alt="team-img"></div>
                            <div class="team-card-content">
                                <div class="team-name">Muzzamil Qureshi</div>
                                <div class="team-position">Graphics Designer / Front-end Dev</div>
                                <div class="team-depart">Nazreen Consulting</div>
                            </div>
                        </div>
                        <div class="team-card"data-aos="flip-up">
                            <div class="team-card-upper"><img src="<?php echo $image;?>103246918_3311308415570414_1526472155788251672_o.jpg" alt="team-img"></div>
                            <div class="team-card-content">
                                <div class="team-name">Muzzamil Qureshi</div>
                                <div class="team-position">Graphics Designer / Front-end Dev</div>
                                <div class="team-depart">Nazreen Consulting</div>
                            </div>
                        </div>
                        <div class="team-card" data-aos="flip-right">
                            <div class="team-card-upper"><img src="<?php echo $image;?>103246918_3311308415570414_1526472155788251672_o.jpg" alt="team-img"></div>
                            <div class="team-card-content">
                                <div class="team-name">Muzzamil Qureshi</div>
                                <div class="team-position">Graphics Designer / Front-end Dev</div>
                                <div class="team-depart">Nazreen Consulting</div>
                            </div>
                        </div>
                        <div class="team-card" data-aos="flip-left">
                            <div class="team-card-upper"><img src="<?php echo $image;?>103246918_3311308415570414_1526472155788251672_o.jpg" alt="team-img"></div>
                            <div class="team-card-content">
                                <div class="team-name">Muzzamil Qureshi</div>
                                <div class="team-position">Graphics Designer / Front-end Dev</div>
                                <div class="team-depart">Nazreen Consulting</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="vision-heading">
            OUR Vision
        </section>
        <section class="about-ourvision">
            <div class="container">
                <div class="about-vision-content">
                        <div class="vison-left" data-aos="zoom-out-up">
                            <img src="<?php echo $image;?>E-com.png" alt="vision-img">
                        </div>
                        <div class="vison-right" data-aos="zoom-out-up">
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. In sequi laudantium eligendi magnam similique explicabo dignissimos enim, minima sit iste. Magni asperiores molestias veritatis voluptate eos officiis hic necessitatibus esse?</p>
                        </div>
                </div>
            </div>
        </section>
        <section class="about-social">
            Join us
        </section>        
        <section class="social">
            <div class="container">
                <div class="about-social-icons" data-aos="fade-up"
                data-aos-duration="1500">
                   <a href="#"><i class="fa fa-facebook-square" aria-hidden="true"></i></a>
                    <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                    <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                    <a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a>
                </div>
            </div>
        </section>
    </main>