<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>add to cart</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">

    <style>
        *{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body{
            font-family: 'Roboto', sans-serif;
        }
        .container{
            max-width: 1280px;
            margin: auto;
        }
        .cart{
            width: 100%;
            margin: 80px auto;
        }
        .cart-table{
            width: 100%;
            border-collapse: collapse;
        }
        .cart-table th{
            text-align: left;
            padding: 5px;
            color: #ffff;
            background-color: #ff523b;
            font-weight: 400;

        }
        .cart-table td{
            padding: 10px 5px;
        }
        .cart-table td .info-content a{
            color: #ff523b;
            text-decoration: none;
            font-size: 12px;
        }
        .cart-table td input{
            width: 50px;
            height: 30px;
            padding: 5px;
        }

        .cart-table td img{
            width: 80px;
            height: 80px;
            margin-right: 10px ;
        }
        .cart-info{
            display: flex;
            flex-wrap: wrap;
        }

        .total-price{
            display: flex;
            justify-content: flex-end;
        }
        .total-price .table-total{
            border-top: 3px solid #ff523b;
            width: 100%;
            max-width: 500px;
        }
        .total-price .table-total tr td{
            padding: 10px 0px;
        }
        td:last-child{
            text-align: right;
        }
        th:last-child{
            text-align: right;
        }

    </style>
</head>
<body>
    <section class="cart">
        <div class="container">
            <div class="cart-content">
                <table class="cart-table">
                    <tr>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Sub Total</th>
                    </tr>
                    <tr>
                        <td>
                            <div class="cart-info">
                                <img src="p1.jpg">
                                <div class="info-content">
                                    <p>Product Name</p>
                                    <small>Price : $ 36.00</small>
                                    <br>
                                    <a href="#">Remove</a>
                                </div>
                            </div>
                        </td>
                        <td><input type="number" value="3"></td>
                        <td>$ 36.00</td>
                    </tr>
                    <tr>
                        <td>
                            <div class="cart-info">
                                <img src="p3.jpg">
                                <div class="info-content">
                                    <p>Product Name</p>
                                    <small>Price : $ 66.00</small>
                                    <br>
                                    <a href="#">Remove</a>
                                </div>
                            </div>
                        </td>
                        <td><input type="number" value="2"></td>
                        <td>$ 66.00</td>
                    </tr>
                    <tr>
                        <td>
                            <div class="cart-info">
                                <img src="p2.jpg">
                                <div class="info-content">
                                    <p>Product Name</p>
                                    <small>Price : $ 99.00</small>
                                    <br>
                                    <a href="#">Remove</a>
                                </div>
                            </div>
                        </td>
                        <td><input type="number" value="1"></td>
                        <td>$ 99.00</td>
                    </tr>
                </table>
                <div class="total-price">
                    <table class="table-total">
                        <tr>
                            <td>Subtotal</td>
                            <td>$ 99.00</td>
                        </tr>
                        <tr>
                            <td>TAX</td>
                            <td>$ 10.00</td>
                        </tr>
                        <tr>
                            <td>Total</td>
                            <td>$ 110.00</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </section>
    
</body>
</html>