<main>
        <section class="learn-hero">
            <div class="container">
                <div class="learn-hero-content">
                    <div class="learn-heading" data-aos="zoom-out-down">
                        Blogs / Knowledge Base
                    </div>
                </div>
            </div>
        </section>
        <section class="section1-blog"data-aos="fade-up"
        data-aos-duration="3000">
            <div class="container">
                <div class="section1-blog-content">
                    <div class="section1-heading">
                        The ServeWise E-Commerce Blog
                    </div>
                    <div class="section1-dis">
                        <p>Do you want a blog that’s all about running an online business? You got it. Our e-commerce marketing blog articles are tailor-made to help you be successful online. Pro Tip: don’t forget to subscribe to get the best e-commerce tips delivered direct to your inbox!</p>
                    </div>
                </div>
            </div>
        </section>
        <section class="section2-blog">
            <div class="container">
                <div class="section2-blog-content">
                    <div class="section2-blog-left-side"data-aos="fade-right">
                        <div class="section2-blog-row">
                            <div class="section2-blog-row-content1">
                                <div class="section2-blog-img">
                                    <img src="<?php echo $image;?>no-image.jpg" alt="cover">
                                </div>
                                <div class="section2-blog-heading">Getting Your E-commerce shop Ready</div>
                                <div class="section2-blog-link">
                                    <a href="#">Click here</a>
                                </div>
                            </div>
                            <div class="section2-blog-row-content1"data-aos="flip-left">
                                <div class="section2-blog-img">
                                    <img src="<?php echo $image;?>no-image.jpg" alt="cover">
                                </div>
                                <div class="section2-blog-heading">
                                    Getting Your E-commerce shop Ready
                                </div>
                                <div class="section2-blog-link">
                                    <a href="#">Click Here</a>
                                </div>
                            </div>
                        </div>
                        <div class="section2-blog-row">
                            <div class="section2-blog-row-content1"data-aos="flip-left">
                                <div class="section2-blog-img">
                                    <img src="<?php echo $image;?>no-image.jpg" alt="cover">
                                </div>
                                <div class="section2-blog-heading">Getting Your E-commerce shop Ready</div>
                                <div class="section2-blog-link">
                                    <a href="#">Click here</a>
                                </div>
                            </div>
                            <div class="section2-blog-row-content1"data-aos="flip-right">
                                <div class="section2-blog-img">
                                    <img src="<?php echo $image;?>no-image.jpg" alt="cover">
                                </div>
                                <div class="section2-blog-heading">
                                    Getting Your E-commerce shop Ready
                                </div>
                                <div class="section2-blog-link">
                                    <a href="#">Click Here</a>
                                </div>
                            </div>
                        </div>
                        <div class="section2-blog-row">
                            <div class="section2-blog-row-content1" data-aos="flip-left">
                                <div class="section2-blog-img">
                                    <img src="<?php echo $image;?>no-image.jpg" alt="cover">
                                </div>
                                <div class="section2-blog-heading">Getting Your E-commerce shop Ready</div>
                                <div class="section2-blog-link">
                                    <a href="#">Click here</a>
                                </div>
                            </div>
                            <div class="section2-blog-row-content1" data-aos="flip-right">
                                <div class="section2-blog-img">
                                    <img src="<?php echo $image;?>no-image.jpg" alt="cover">
                                </div>
                                <div class="section2-blog-heading">
                                    Getting Your E-commerce shop Ready
                                </div>
                                <div class="section2-blog-link">
                                    <a href="#">Click Here</a>
                                </div>
                            </div>
                        </div>
                        <div class="section2-blog-row">
                            <div class="section2-blog-row-content1"data-aos="flip-left">
                                <div class="section2-blog-img">
                                    <img src="<?php echo $image;?>no-image.jpg" alt="cover">
                                </div>
                                <div class="section2-blog-heading">Getting Your E-commerce shop Ready</div>
                                <div class="section2-blog-link">
                                    <a href="#">Click here</a>
                                </div>
                            </div>
                            <div class="section2-blog-row-content1" data-aos="flip-right">
                                <div class="section2-blog-img">
                                    <img src="<?php echo $image;?>no-image.jpg" alt="cover">
                                </div>
                                <div class="section2-blog-heading">
                                    Getting Your E-commerce shop Ready
                                </div>
                                <div class="section2-blog-link">
                                    <a href="#">Click Here</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="section2-blog-right-side"  data-aos="fade-left">
                        <div class="section2-blog-side">
                            <div class="section-blog-right-side"><b>Blog Link</b></div>
                            <div class="blog-side-link-content">
                                <a href="#"><p>Start your E-Commerce <br> <small>Click here</small></p></a>
                            </div>
                            <div class="blog-side-link-content">
                                <a href="#"><p>Start your E-Commerce <br> <small>Click here</small></p></a>
                            </div>
                            <div class="blog-side-link-content">
                                <a href="#"><p>Start your E-Commerce <br> <small>Click here</small></p></a>
                            </div>
                            <div class="blog-side-link-content">
                                <a href="#"><p>Start your E-Commerce <br> <small>Click here</small></p></a>
                            </div>
                            <div class="blog-side-link-content">
                                <a href="#"><p>Start your E-Commerce <br> <small>Click here</small></p></a>
                            </div>
                            <div class="blog-side-link-content">
                                <a href="#"><p>Start your E-Commerce <br> <small>Click here</small></p></a>
                            </div>
                            <div class="blog-side-link-content">
                                <a href="#"><p>Start your E-Commerce <br> <small>Click here</small></p></a>
                            </div>
                            <div class="blog-side-link-content">
                                <a href="#"><p>Start your E-Commerce <br> <small>Click here</small></p></a>
                            </div>
                            <div class="blog-side-link-content">
                                <a href="#"><p>Start your E-Commerce <br> <small>Click here</small></p></a>
                            </div>
                            <div class="blog-side-link-content">
                                <a href="#"><p>Start your E-Commerce <br> <small>Click here</small></p></a>
                            </div>
                            <div class="blog-side-link-content">
                                <a href="#"><p>Start your E-Commerce <br> <small>Click here</small></p></a>
                            </div>
                            <hr>
                            <div class="blog-side-podcast">
                                <a href="#">Click here to see the Podcast</a>
                            </div>
                            <hr>

                        </div>
                    </div>
                </div>
           
            </div>
        </section>
        <section class="section2-blog-email"data-aos="flip-up">
            <h1>Stay up to date with us!</h1>
            <p>Get free ecommerce tips, news and inspiring ideas right to your inbox</p>
            <form action="sumit">
                <input type="text">
                <button>Subscribe Now</button>
            </form>
            <form action="radio" class="radio-form-blog">
                <input type="radio" class="blog-radio">
                <p>I consent to receive Ecwid Newsletter. I can unsubscribe anytime.</p>
            </form>
        </section>
    </main>