<?php 
    $blog_title = search_array('blogtitle',$config_system);
    $blog_code = search_array('blogcode',$config_system);
?>

<main>
        <section class="learn-hero">
            <div class="container">
                <div class="learn-hero-content">
                    <div class="learn-heading" data-aos="zoom-out-down">
                        Blogs / Knowledge Base
                    </div>
                </div>
            </div>
        </section>
        <section class="section1-blog"data-aos="fade-up"
        data-aos-duration="3000">
            <div class="container">
                <div class="section1-blog-content">
                    <div class="section1-heading">
                    <?php echo $blog_title['value'] ; ?>
                    </div>
                    <!-- <div class="section1-dis">
                        <p>Do you want a blog that’s all about running an online business? You got it. Our e-commerce marketing blog articles are tailor-made to help you be successful online. Pro Tip: don’t forget to subscribe to get the best e-commerce tips delivered direct to your inbox!</p>
                    </div> -->
                </div>
            </div>
        </section>
        <section class="section2-blog">
            <div class="container">
                <?php echo $blog_code['value'] ; ?> 
            </div>
        </section>
        <section class="section2-blog-email"data-aos="flip-up">
            <h1>Stay up to date with us!</h1>
            <p>Get free ecommerce tips, news and inspiring ideas right to your inbox</p>
            <form action="sumit">
                <input type="text">
                <button>Subscribe Now</button>
            </form>
            <form action="radio" class="radio-form-blog">
                <input type="radio" class="blog-radio">
                <p>I consent to receive Ecwid Newsletter. I can unsubscribe anytime.</p>
            </form>
        </section>
    </main>