<?php
session_start();
require("../model/classDatabaseManager.php");
require("../model/addtocart/addtocartClass.php");
$db_handle = new Addtocart();
if(!empty($_GET["action"])) {
	
switch($_GET["action"]) {
	case "add":
		if(!empty($_POST["quantity"])) {
			$productByCode = $db_handle->getspecificproductdata ($_GET["code"]);
			$itemArray = array($productByCode[0]["code"]=>array('id'=>$productByCode[0]["product_id"],'name'=>$productByCode[0]["name"], 'code'=>$productByCode[0]["code"], 'quantity'=>$_POST["quantity"], 'price'=>$productByCode[0]["price"]));
			
			if(!empty($_SESSION["cart_item"])) {
				if(in_array($productByCode[0]["code"],array_keys($_SESSION["cart_item"]))) {
					foreach($_SESSION["cart_item"] as $k => $v) {
							if($productByCode[0]["code"] == $k) {
								if(empty($_SESSION["cart_item"][$k]["quantity"] )) {
									$_SESSION["cart_item"][$k]["quantity"] = 0;
									
									
								}
								$_SESSION["cart_item"][$k]["quantity"] += $_POST["quantity"];
								
							
							}
					}
				} else {
					$_SESSION["cart_item"] = array_merge($_SESSION["cart_item"],$itemArray);
				}
			} else {
				$_SESSION["cart_item"] = $itemArray;
			}
		}
	break;
	case "remove":
		if(!empty($_SESSION["cart_item"])) {
			foreach($_SESSION["cart_item"] as $k => $v) {
					if($_GET["code"] == $k)
						unset($_SESSION["cart_item"][$k]);				
					if(empty($_SESSION["cart_item"]))
						unset($_SESSION["cart_item"]);
			}
		}
	break;
	case "empty":
		unset($_SESSION["cart_item"]);
	break;
	case "upload":
		if(!empty($_SESSION["cart_item"])) {
		 foreach ($_SESSION["cart_item"] as $item){
		$name =  $item["name"];
			 $id = $item["id"];
			 $quantity = $item["quantity"];
			$unitprice = $item["price"];
			 $total = $quantity * $unitprice;
			 $userid = 6;
	
		$addtocart = $db_handle->addtocart($id,$quantity,$unitprice,$userid,$total);	 		
		if (!empty($addtocart)){
			//echo "Cart if Confirmed";
			unset($_SESSION["cart_item"]);
			
			//getting data from order_product table against user id and store it into order table.
			$getcartbyuserid = $db_handle->getcartrecordbyuserid($userid);
			if (!empty($getcartbyuserid)){
				foreach($getcartbyuserid as $order){
					$status = "pending";
					$checkopid = $db_handle->checkopid($order["op_id"]);
					if (empty($checkopid)){
				$addtoorder = $db_handle->addtoorder($order["op_id"],$status);
					} else {
				//		echo "op id exists";
					}
					//	echo $order["op_id"]."got the op id";
				if (!empty($addtoorder)){
				//echo "added to order";
				} else {
					//echo "not added to the order";
				}
		}
			} else {
			//	echo " not got the op id";
			}
			
		} else {
			//echo "Cart not confirmed";
		}
		 }
		}
		break;
}
}
?>

<div id="shopping-cart">
<div class="txt-heading">Shopping Cart</div>

<a id="btnEmpty" href="index.php?action=empty">Empty Cart</a>
<?php
if(isset($_SESSION["cart_item"])){
    $total_quantity = 0;
    $total_price = 0;
?>	
<table class="tbl-cart" cellpadding="10" cellspacing="1">
<tbody>
<tr>
<th style="text-align:left;">Name</th>
<th style="text-align:left;">Code</th>
<th style="text-align:right;" width="5%">Quantity</th>
<th style="text-align:right;" width="10%">Unit Price</th>
<th style="text-align:right;" width="10%">Price</th>
<th style="text-align:center;" width="5%">Remove</th>
</tr>	
<form method="post" action="index.php?action=upload">
	<?php		
   
	foreach ($_SESSION["cart_item"] as $item){
        $item_price = $item["quantity"]*$item["price"];
		?>
	
				<tr>
				<td><?php echo $item["name"]; ?></td>
				<td><?php echo $item["code"]; ?></td>
				<td style="text-align:right;"><?php echo $item["quantity"]; ?></td>
				<td  style="text-align:right;"><?php echo "$ ".$item["price"]; ?></td>
				<td  style="text-align:right;"><input name="itemprice" value="<?php echo $item_price ?>"><?php echo "$ ". number_format($item_price,2); ?></td>
				<td style="text-align:center;"><a href="index.php?action=remove&code=<?php echo $item["code"]; ?>" class="btnRemoveAction"><img src="icon-delete.png" alt="Remove Item" /></a></td>
				</tr>
				<?php
				$total_quantity += $item["quantity"];
				$total_price += ($item["price"]*$item["quantity"]);
		
	}
		
		?>
	<input type="submit" name="uploadbtn" id="btnEmpty" value="confirm cart">
</form>
<tr>
<td colspan="2" align="right">Total:</td>
<td align="right"><?php echo $total_quantity; ?></td>
<td align="right" colspan="2"><strong><?php echo "$ ".number_format($total_price, 2); ?></strong></td>
<td></td>
</tr>
</tbody>
</table>		
  <?php
} else {
?>
<div class="no-records">Your Cart is Empty</div>
<?php 
}
?>
</div>

<div id="product-grid">
	<div class="txt-heading">Products</div>
	<?php
	$product_array = $db_handle->getproductdata ();
	if (!empty($product_array)) { 
		foreach($product_array as $key=>$value){
	?>
		<div class="product-item">
			<form method="post" action="index.php?action=add&code=<?php echo $product_array[$key]["code"]; ?>">
			
			<div class="product-tile-footer">
			<div class="product-title"><?php echo $product_array[$key]["name"]; ?></div>
			<div class="product-price"><?php echo "$".$product_array[$key]["price"]; ?></div>
			<div class="cart-action"><input type="text" class="product-quantity" name="quantity" value="1" size="2" /><input type="submit" value="Add to Cart" class="btnAddAction" /></div>
			</div>
			</form>
		</div>
	<?php
		}
	}
	?>
</div>