<main>
        <section class="learn-hero">
            <div class="container">
                <div class="learn-hero-content">
                    <div class="learn-heading" data-aos="zoom-out-down">
                        Customer Service
                    </div>
                </div>
            </div>
        </section>
        
        <section class="section1-customer">
            <div class="container">
                <div class="section1-customer-content" data-aos="fade-up"
                data-aos-duration="3000">
                    <div class="customer-hero-heading">
                        How Can We Help You!
                    </div>
                    <div class="customer-search-box">
                        <form action="search">
                            <input type="text" placeholder="Search Here">
                        </form>
                        <div class="customer-search-content">
                        <p>Popular Questions:</p>
                        <a href="#">How i can start</a>
                        <a href="#">ServeWise Domain</a>
                        <a href="#">ServeWise Themes</a>
                        <a href="#">Theme Selection</a>
                    </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="section2-customer">
            <div class="container">
                <div class="section2-customer-content">
                    <div class="section2-card-customer" data-aos="zoom-in-right">
                        <div class="c-card-upper">E-mail</div>
                        <div class="c-card-mid">Click below to send us your E-mail!</div>
                        <div class="c-card-btn"><a href="#">Send Us your Email</a></div>
                    </div>
                    <div class="section2-card-customer" data-aos="zoom-in-left">
                        <div class="c-card-upper">Live Chat</div>
                        <div class="c-card-mid">Click below to Start Chating with us!</div>
                        <div class="c-card-btn"><a href="#">Upgrade to Chat</a></div>
                    </div>
                </div> 
            </div>
        </section>
        <section class="customer-detail" data-aos="zoom-out-up">
            <div class="container">
                <div class="customer-detail-content">
                    <p>Phone support is available via call-back requests made in chat. We’re here to help over the phone Monday to Friday from XX:XX p.m. – XX:XX p.m. PDT. Available in English for Business and Unlimited plans only.</p>
                    <div class="c-d-c-2">
                        <p><a href="#">info@servewise.com</a>-for Information.</p>
                        <p><a href="#">Contact@servewise.com</a>-For Contact.</p>
                    </div>
                </div>
            </div>
        </section>
        <section class="customer-email">
            <div class="container">
                <div class="customer-email-content"  data-aos="fade-up"
                data-aos-anchor-placement="top-bottom">
                    <div class="c-email-heading">Send us an e-mail</div>
                    <div class="c-email-content">Get answers to your question within 24 hours or less,</div>
                    <form action="submit">
                        <input type="text" placeholder="Your E-mail...">
                        <textarea name=""></textarea>
                        <button type="submit">Submit</button>
                    </form>
                </div>
            </div>
        </section>
    </main>