<footer>
        <div class="container">
            <div class="footer-content">
                <div class="footer-upper">
                    <div class="footer-upper-1 up1">
                        <div class="footer-logo">LOGO</div>
                    </div>
                    <div class="footer-upper-1">
                        <h2>Way to sell</h2>
                        <a href="#">Sell everywhere</a>
                        <a href="#">Facebook Store</a>
                        <a href="#">Instagram Store</a>
                        <a href="#">Google Store</a>
                        <a href="#">Wordpress Store</a>
                        <a href="#">Buy Button</a>
                        <a href="#">Point-of-Sale</a>
                        <a href="#">ShopApp</a>
                        <a href="#">Amazon</a>
                    </div>
                    <div class="footer-upper-1">
                        <h2>Support</h2>
                        <a href="#">Help Center</a>
                        <a href="#">Guides</a>
                        <a href="#">Videos</a>
                        <a href="#">Product Update</a>
                        <a href="#">API Documentation</a>
                        <a href="#">Status Monitor</a>
                        <a href="#">Contact Support</a>
                    </div>
                    <div class="footer-upper-1">
                        <h2>Product</h2>
                        <a href="#">Pricing</a>
                        <a href="#">Demo</a>
                        <a href="#">Feature</a>
                        <a href="#">Showcase</a>
                        <a href="#">ServeWise App</a>
                        <a href="#">App Market</a>
                        <a href="#">E-commerce Hosting</a></div>
                </div>
                <div class="footer-mid">
                    <div class="footer-mid-1 md1">
                        <div class="badge-1"></div>
                        <div class="badge-2"></div>
                    </div>
                    <div class="footer-mid-1">
                        <h2>Partners</h2>
                        <a href="#">Referral Program</a>
                        <a href="#">Affilate Program</a>
                        <a href="#">For Reseller</a>
                        <a href="#">Developers</a>
                        <a href="#">ServeWise</a>
                    </div>
                    <div class="footer-mid-1">
                        <h2>Company</h2>
                        <a href="#">About</a>
                        <a href="#">Press</a>
                        <a href="#">Media</a>
                        <a href="#">Terms of Service</a>
                        <a href="#">Privacy Policy</a>
                        <a href="#">SW Privacy Policy</a>
                        <a href="#">DPA</a>
                        <a href="#">Sitemap</a>
                        <a href="#">Copyright Policy</a>
                        <a href="#">CCPA Notice</a>
                    </div>
                    <div class="footer-mid-1">
                        <h2>Community</h2>
                        <a href="#">Blog</a>
                        <a href="#">Facebook</a>
                        <a href="#">Twitter</a>
                        <a href="#">Instagram</a>
                        <a href="#">Youtube</a>
                        <a href="#">Podcast</a>
                    </div>
                </div>
                <div class="footer-lower">              
                    <div class="footer-lower-1">
                        <div class="c-logo">LOGO</div>
                    </div>
                    <div class="footer-lower-1">
                        <div class="CopyRight">
                            &copy; 2020 ServeWise
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>