<?php 
    $fb = search_array('facebook',$config_system);
    $tw = search_array('twitter',$config_system);
    $inst = search_array('instagram',$config_system);
    $lin = search_array('Linkin',$config_system);
?>
<footer>
        <div class="container">
            <div class="footer-content">
                <div class="footer-upper">
                    <div class="footer-upper-1 up1">
                        <div class="footer-logo">LOGO</div>
                    </div>
                    <div class="footer-upper-1">
                        <h2>Support</h2>
                        <a href="?page=helpcenter">Help Center</a>
                        <a href="?page=guide">Guides</a>
                        <a href="?page=video">Videos</a>
                        <a href="?page=customer">Customer Service</a>
                    </div>
                    <div class="footer-upper-1">
                        <h2>Product</h2>
                        <a href="?page=blog">Pricing</a>
                        <a href="?page=blog">Demo</a>
                        <a href="?page=blog">Feature</a>
                        <a href="?page=showcase">Showcase</a>
                    </div>
                  
                </div>
                <div class="footer-mid">
                    <div class="footer-mid-1 md1">
                        <div class="badge-1"></div>
                        <div class="badge-2"></div>
                    </div>
                    <div class="footer-mid-1">
                        <h2>Partners</h2>
                        <a href="?page=partners">Referral Program</a>
                        <a href="?page=partners">Affilate Program</a>
                        <a href="?page=partners">For Reseller</a>
                        <a href="?page=about">Developers</a>
                        <a href="?page=about">ServeWise</a>
                    </div>
                    <div class="footer-mid-1">
                        <h2>Company</h2>
                        <a href="?page=about">About</a>
                        <a href="?page=termsofserve">Terms of Service</a>
                        <a href="?page=privacypolicy">Privacy Policy</a>
                        <!-- <a href="#">Sitemap</a> -->
                        <!-- <a href="#">Copyright Policy</a> -->
                        <!-- <a href="#">CCPA Notice</a> -->
                    </div>
                    <div class="footer-mid-1">
                        <h2>Community</h2>
                        <a href="?page=blog">Blog</a>
                        <a href="<?php echo $fb['value'] ; ?>"><i class="fa fa-facebook-official" aria-hidden="true"></i> Facebook</a>
                        <a href="<?php echo $tw['value'] ; ?>"><i class="fa fa-twitter-square" aria-hidden="true"></i> Twitter</a>
                        <a href="<?php echo $inst['value'] ; ?>"><i class="fa fa-instagram" aria-hidden="true"></i> Instagram</a>
                        <a href="<?php echo $lin['value'] ; ?>"><i class="fa fa-linkedin" aria-hidden="true"></i> Link In</a>
                        <a href="?page=video">Podcast</a>
                    </div>
                </div>
                <div class="footer-lower">              
                    <div class="footer-lower-1">
                        <div class="c-logo">LOGO</div>
                    </div>
                    <div class="footer-lower-1">
                        <div class="CopyRight">
                            &copy; 2020 ServeWise
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>