<?php 
    $guid_title = search_array('guide title',$config_system);
    $guid_dis = search_array('guide Short Description',$config_system);
    $guid_code = search_array('guide video',$config_system);
?>

<main>
        <section class="learn-hero">
            <div class="container">
                <div class="learn-hero-content">
                    <div class="learn-heading" data-aos="zoom-out-down">
                        GUIDE
                    </div>
                </div>
            </div>
        </section>
        
        <section class="section1-Guide">
            <div class="container">
                <div class="section1-Guide-content" data-aos="fade-right">
                    <div class="guide-heading-hero"><?php echo $guid_title['value'] ; ?></div>
                    <div class="guide-heading-pera"><?php echo $guid_dis['value'] ; ?></div>
                    <!-- <div class="guide-heading-btn"> <a href="#">READ</a> | <a href="#">LISTEN</a> | <a href="#">DOWNLOAD</a></div> -->
                </div>
            </div>
        </section>
        <section class="section2-Guide">
            <div class="container">
            <?php echo $guid_code['value'] ; ?>     
            </div>
        </section>
    </main>