<header>
        <nav>
            
        <div id="menuToggle">
            <input type="checkbox" />
                <span></span>
                <span></span>
                <span></span>
            
            <ul id="menu">
                <a href="#"><li>Blog</li></a>
                <a href="#"><li>Log Out</li></a>
            </ul>
        </div>
              <!-- end -->

            <div class="logo">
               <a href="?page=home"><img src="<?php echo $logo_frontend;?>" alt="demo"></a>
            </div>
            <div class="btn-1-nav">
                <a href="?page=about">
                    <div class="box-1">
                        <div class="btn btn-one">
                          <span>About</span>
                        </div>
                      </div>
                </a>
                <a href="?page=partners">
                    <div class="box-1">
                        <div class="btn btn-one">
                          <span>Partner</span>
                        </div>
                      </div>
                </a>
            </div>
            <div class="btn-2-nav">
                <ul class="learn-dropdown">
                <a href="?page=learn" class="nav-nav1">Learn</a>
                <div class="learn-option">
                  <a href="?page=helpcenter" class="learn-select1">Help Center</a>
                  <a href="?page=video" class="learn-select2">Videos</a>
                  <!-- <a href="?page=customer" class="learn-select2">Customer Service</a> -->
                  <a href="?page=blog" class="learn-select2">Blog/Knowledge Base</a>
                  <a href="?page=showcase" class="learn-select2">Showcase</a>
                  <a href="?page=guide" class="learn-select3">Guide</a>
                </div>
              </ul>
                <div class="search-box">
                  <input type="text" class="search-txt" placeholder="Search">
                  <button class="search-icon"><i class="fa fa-search" aria-hidden="true"></i></button>
                </div>
            </div>
            <div class="btn-3-nav">
                <div> 
                    
                <a href="?page=login_dashboard" class="btn btn-sm animated-button thar-login">Login</a>
                <a href="?page=becomevendor" class="btn btn-sm animated-button thar-get">Get Started</a> </div>
            </div>
        </nav>
    </header>