<main>
        <section class="learn-hero">
            <div class="container">
                <div class="learn-hero-content">
                    <div class="learn-heading" data-aos="zoom-out-down">
                        Help Center
                    </div>
                </div>
            </div>
        </section>
        <section class="section1-hc">
            <div class="container">
                <div class="section1-hc-content">
                    <div class="section1-hc-heading">What else you may want to know!</div>
                </div>
            </div>
        </section>
        <section class="section2-Guide">
            <div class="container">
               
                <div class="section2-hc-faq" data-aos="fade-up"
                data-aos-duration="3000">
                    <button class="accordion">Does ServeWise provide products to sell in my store?</button>
                    <div class="panel">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                    </div>
                    <button class="accordion">I'm attempting to import products from my store on another platform to my ServeWise store, but I continue receiving an error message. <br> What should I do?</button>
                    <div class="panel">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                    </div>
                    <button class="accordion">Can I connect the domain I already own to the ServeWise Instant Site?</button>
                    <div class="panel">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                    </div>
                    <button class="accordion">I've set up Instagram shopping/product tagging for a while now, but I still can't tag my products on Instagram. What should I do?</button>
                    <div class="panel">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                    </div>
                    <button class="accordion">How do I get paid?</button>
                    <div class="panel">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                    </div>
                    <button class="accordion">Can the Ecwid store be integrated with a third-party service?</button>
                    <div class="panel">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                    </div>
                </div>
            </div>
        </section>
    </main>