<!DOCTYPE html>
<meta name="viewport" content="width=device-width, initial-scale=1">
<head>

<meta name="google-site-verification" content="ilQNeDSEoYlzWa_gxXllrQuznnEvJRMKA6Fjg85XHqM" />
	<link rel="stylesheet" type="text/css" href="<?php echo $dashboardcss;?>">
	<link rel="stylesheet" type="text/css" href="<?php echo $aosstyle;?>">
	<link rel="stylesheet" type="text/css" href="<?php echo $fonts;?>">
	<link rel="stylesheet" type="text/css" href="<?php echo $stylesheet;?>">
	<link rel="stylesheet" type="text/css" href="<?php echo $substylesheet;?>">
    <link rel="stylesheet" type="text/css" href="<?php echo $fontawsome;?>">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/2.8.0/css/flag-icon.min.css"/>


		<title>ServeWise</title>
	
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-MXSHQXW');</script>
<!-- End Google Tag Manager -->
</head>
<body>
	
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MXSHQXW"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

<?php require($header); ?>
<section id='main'>
	
<?php 
if(($dashboard != NULL) && !empty($_SESSION['status'])){
	if($_SESSION['status'] != 'block'){
 require($footer);
}
 }
include $main_content; 

?>
</section>

<?php 

if($dashboard == NULL){
	echo "<footer>";
 require($footer);
 echo "</footer>";
 }else{
	 ?>
	     
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
	 <script>
        $(document).ready(function() {
        var ajaxCall = function() {
            url       = '../app/lib/notifications.php';
            //formData  = $("#myForm").serialize();
            $.ajax({
                type: 'post',
                url: url,
                data: 'formData',
                success: function(data) {
                // $('nav').hide();
                // $('main').hide();
                document.getElementById("result").innerHTML = data;
                console.log(data);
                }
            });
        }
        setInterval(ajaxCall, 5000);
        });
    </script>
	 <?php
 }
 
 ?>



<script type="text/javascript" src="<?php echo $jqurey;?>"></script>
<script type="text/javascript" src="<?php echo $aosjs;?>"></script>
<script type="text/javascript" src="<?php echo $jscript;?>"></script>
<script type="text/javascript" src="<?php echo $jscript_dashboard;?>"></script>
<script type="text/javascript" src="<?php echo $jscript_tile_dashboard;?>"></script>
<script type="text/javascript" src="<?php echo $editorjs;?>"></script>
<script type="text/javascript" src="<?php echo $editorsubjs;?>"></script>
<script type="text/javascript" src="<?php echo $ajax_handler;?>"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/printThis/1.15.0/printThis.min.js"></script>
<script src="https://code.jquery.com/jquery-3.2.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
  

</body>

</html>