<!DOCTYPE html>
<meta name="viewport" content="width=device-width, initial-scale=1">
<head>
	<link rel="stylesheet" type="text/css" href="<?php echo $dashboardcss;?>">
	<link rel="stylesheet" type="text/css" href="<?php echo $aosstyle;?>">
	<link rel="stylesheet" type="text/css" href="<?php echo $fonts;?>">
	<link rel="stylesheet" type="text/css" href="<?php echo $stylesheet;?>">
	<link rel="stylesheet" type="text/css" href="<?php echo $substylesheet;?>">
	<link rel="stylesheet" type="text/css" href="<?php echo $fontawsome;?>"> 

		<title>ServeWise</title>
	
</head>
<body>
	

<?php require($header); ?>
<section id='main'>
	
<?php 
if(($dashboard != NULL) && !empty($_SESSION['status'])){
	if($_SESSION['status'] != 'block'){
 require($footer);
}
 }
include $main_content; 

?>
</section>

<?php 

if($dashboard == NULL){
	echo "<footer>";
 require($footer);
 echo "</footer>";
 }else{
	 ?>
	     
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
	 <script>
        $(document).ready(function() {
        var ajaxCall = function() {
            url       = '../app/lib/notifications.php';
            //formData  = $("#myForm").serialize();
            $.ajax({
                type: 'post',
                url: url,
                data: 'formData',
                success: function(data) {
                // $('nav').hide();
                // $('main').hide();
                document.getElementById("result").innerHTML = data;
                console.log(data);
                }
            });
        }
        setInterval(ajaxCall, 500000);
        });
    </script>
	 <?php
 }
 
 ?>



<script type="text/javascript" src="<?php echo $jqurey;?>"></script>
<script type="text/javascript" src="<?php echo $aosjs;?>"></script>
<script type="text/javascript" src="<?php echo $jscript;?>"></script>
<script type="text/javascript" src="<?php echo $jscript_dashboard;?>"></script>
<script type="text/javascript" src="<?php echo $editorjs;?>"></script>
<script type="text/javascript" src="<?php echo $editorsubjs;?>"></script>
<script type="text/javascript" src="<?php echo $ajax_handler;?>"></script>
  

</body>

</html>