<!DOCTYPE html>
<meta name="viewport" content="width=device-width, initial-scale=1">
<head>
	<link rel="stylesheet" type="text/css" href="<?php echo $dashboardcss;?>">
	<link rel="stylesheet" type="text/css" href="<?php echo $aosstyle;?>">
	<link rel="stylesheet" type="text/css" href="<?php echo $fonts;?>">
	<link rel="stylesheet" type="text/css" href="<?php echo $stylesheet;?>">
	<link rel="stylesheet" type="text/css" href="<?php echo $substylesheet;?>">
	<link rel="stylesheet" type="text/css" href="<?php echo $fontawsome;?>"> 

		<title>ServeWise</title>
	
</head>
<body>
	

<?php require($header); ?>
<section id='main'>
	
<?php 
if($dashboard != NULL){
 require($footer);
 }
include $main_content; 

?>
</section>

<?php 

if($dashboard == NULL){
	echo "<footer>";
 require($footer);
 echo "</footer>";
 }
 
 ?>



<script type="text/javascript" src="<?php echo $jqurey;?>"></script>
<script type="text/javascript" src="<?php echo $aosjs;?>"></script>
<script type="text/javascript" src="<?php echo $jscript;?>"></script>
<script type="text/javascript" src="<?php echo $jscript_dashboard;?>"></script>
    <script type="text/javascript" src="<?php echo $ajax_handler;?>"></script>
  

</body>

</html>