<main>
        <section class="learn-hero">
            <div class="container">
                <div class="learn-hero-content">
                    <div class="learn-heading" data-aos="zoom-out-down">
                        LEARN
                    </div>
                </div>
            </div>
        </section>
        <section class="learn-navigation">
            <div class="container">
                <div class="learn-navigation-content">
                    <div class="navgation-row-1">
                        <a href="?page=helpcenter" data-aos="fade-right">
                            <div class="heading">HELP CENTER</div>
                            <div class="dis">
                                click here
                            </div>
                        </a>
                        <a href="?page=video" data-aos="fade-left">
                            <div class="heading">VIDEO</div>
                            <div class="dis">
                                click here
                            </div>
                        </a>
                    </div>
                    <div class="navgation-row-1">
                        <!-- <a href="learn-navigation/customer.html" data-aos="fade-up-right">
                            <div class="heading">CUSTOMER SERVICE</div>
                            <div class="dis">
                                click here
                            </div>
                        </a> -->
                        <a href="?page=blog" data-aos="fade-up-left">
                            <div class="heading">BLOG</div>
                            <div class="dis">
                                click here
                            </div>
                        </a>
                    </div>
                    <div class="navgation-row-1">
                        <a href="?page=showcase" data-aos="fade-up"
                        data-aos-anchor-placement="top-bottom">
                        <div class="heading">SHOWCASE</div>
                        <div class="dis">
                            click here
                        </div>
                    </a>
                    <a href="?page=guide" data-aos="fade-up"
                    data-aos-anchor-placement="center-bottom">
                        <div class="heading">GUIDE</div>
                        <div class="dis">
                            click here
                        </div>
                    </a>
                    </div>
                </div>
            </div>
        </section>
    </main>