<?php 
    $partner_hero_heading = search_array('partner hero heading',$config_system);
    $partner_hero_dis = search_array('partner hero disc',$config_system);
    $partner_faq_title = search_array('partner faq title',$config_system);
    $partner_faq_dis = search_array('partner faq ans',$config_system);
    $partner_pkg_name = search_array('partner pkg name',$config_system);
    $partner_pkg_price = search_array('partner pkg price',$config_system);
    $partner_pkg_heading = search_array('partner pkg heading',$config_system);
    $partner_pkg_dis = search_array('partner pkg dis',$config_system);
?>
<main class="patner">
        <section class="partner-hero">
            <div class="container">
                <div class="partner-hero-content">
                    <div class="hero-left-side"data-aos="zoom-out-right" data-aos-duration="1000">
                        <div class="p-heading"><?php echo $partner_hero_heading['value'] ; ?></div>
                        <?php echo $partner_hero_dis['value'] ; ?>
                        <div class="p-btn">
                            <a href="?page=privacypolicy">Privacy Policy</a>
                        </div>
                    </div>
                    <div class="hero-right-side" data-aos="fade-left" data-aos-duration="1000" >
                        <img src="../../assets/E-com.png" alt="">
                    </div>
                </div>
            </div>
        </section>
        <section class="partner-section1">
            <div class="container">
                <div class="section1-content" data-aos="zoom-in">
                    <div class="section-upper">
                        <div class="section1-heading">We make it Simple , powerful and Easy for your clients</div>
                    </div>
                    <div class="section-lower">
                        <div class="section1-card">
                            <div class="section1-icon">M</div>
                            <div class="section1-ids">Resell <b>ServeWise</b> under your brand and set your price with our white label e-commerce program.</div>
                        </div>
                        <div class="section1-card">
                            <div class="section1-icon">N</div>
                            <div class="section1-ids">Manage all your clients' accounts easily with one central dashboard for ecommerce resellers.</div>
                        </div>
                        <div class="section1-card">
                            <div class="section1-icon">O</div>
                            <div class="section1-ids">Never worry about maintenance or updates again thanks to our secure, hosted cloud solution.</div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="section2-faq">
            <div class="container">
                <div class="section2-heading"><?php echo $partner_faq_title['value'] ; ?></div>
                <div class="section2-content" data-aos="fade-up"
                data-aos-duration="3000">
                    <div class="section2-content-center">
                    <?php echo $partner_faq_dis['value'] ; ?>
                    </div>
                </div>
            </div>
        </section>
        <section class="section3-card">
            <div class="container">
                <div class="section3-heading">Find the Perfect Package for You</div>
                <div class="section3-card-content" data-aos="fade-up"
                data-aos-anchor-placement="top-bottom">
                    <div class="section3-pay-card">
                        <div class="section3-card1" data-aos="flip-right">
                            <div class="card1-heading">
                                <div class="side1">
                                    <p><?php echo $partner_pkg_name['value'] ; ?> <small>MEMBERSHIP</small></p>
                                </div>
                                <div class="side2">
                                    <p>$<?php echo $partner_pkg_price['value'] ; ?> <span>/Year</span></p>
                                </div>
                            </div>
                            <div class="card1-dis">
                                <p class="card1-heading-dis"><?php echo $partner_pkg_heading['value'] ; ?></p>
                                <?php echo $partner_pkg_dis['value'] ; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="section4-email">
            <div class="container">
                <div class="section4-email-content" data-aos="fade-up"
                data-aos-anchor-placement="center-center">
                        <div class="section4-heading">Drop your e-mail here for more info.</div>
                        <div class="section4-btn">
                            <form action="sumbit">
                                <input type="email" placeholder="E-mail Here...">
                                <button type="submit">Send</button>
                            </form>
                        </div>
                </div>
            </div>
        </section>
    </main>