<main class="patner">
        <section class="partner-hero">
            <div class="container">
                <div class="partner-hero-content">
                    <div class="hero-left-side"data-aos="zoom-out-right" data-aos-duration="1000">
                        <div class="p-heading">Have you thought about becoming an Partner reseller?</div>
                        <div class="p-dis">
                            Resell a leading ecommerce platform and grow your business with the Ecwid Partner Program. Sign up below to learn more about our partnership options and how to get started.
                        </div>
                        <div class="p-btn">
                            <a href="?page=privacypolicy">Privacy Policy</a>
                        </div>
                    </div>
                    <div class="hero-right-side" data-aos="fade-left" data-aos-duration="1000" >
                        <img src="../../assets/E-com.png" alt="">
                    </div>
                </div>
            </div>
        </section>
        <section class="partner-section1">
            <div class="container">
                <div class="section1-content" data-aos="zoom-in">
                    <div class="section-upper">
                        <div class="section1-heading">We make it Simple , powerful and Easy for your clients</div>
                    </div>
                    <div class="section-lower">
                        <div class="section1-card">
                            <div class="section1-icon">M</div>
                            <div class="section1-ids">Resell <b>ServeWise</b> under your brand and set your price with our white label e-commerce program.</div>
                        </div>
                        <div class="section1-card">
                            <div class="section1-icon">N</div>
                            <div class="section1-ids">Manage all your clients' accounts easily with one central dashboard for ecommerce resellers.</div>
                        </div>
                        <div class="section1-card">
                            <div class="section1-icon">O</div>
                            <div class="section1-ids">Never worry about maintenance or updates again thanks to our secure, hosted cloud solution.</div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="section2-faq">
            <div class="container">
                <div class="section2-heading">Frequently Asked Questions (FAQ)</div>
                <div class="section2-content" data-aos="fade-up"
                data-aos-duration="3000">
                    <div class="section2-content-center">
                        <h3>How does the partnership program work?</h3>
                        <p>When you join our program, you'll get everything you need to start reselling <b>ServeWise's</b> e-commerce plans to your own clients. We'll create your personal partner dashboard where you can create store accounts for your clients and manage their plans. If you'd like to resell <b>ServeWise's</b> under your own brand, our white label option lets you feature your own brand name and logos on the store account and login pages.</p>
                        <h3>How do I become a partner?</h3>
                            <ul>All you need to do is:
                                <li>i) Enter your email on this page</li>
                                <li>ii) Submit the membership fee for your first year using the personal payment link that we will send you by email.</li>
                                <li>iii) Submit your branding information (company name and logos).</li>
                                <li>iv) Once we have your payment and branding information, we will create your partner dashboard within 5 business days. Then you'll be ready to start selling e-commerce!</li>
                            </ul>
                        <h3>Can I choose which store features to enable/disable for my customers?</h3>
                        <p>Yes, you can choose to hide certain sections of the store control panel from your customers and select which apps should be pre-installed or available for installation in all your stores. This Advanced Setup option is included in the Gold Tier membership and is available as a paid add-on on the Silver Tier.</p>
                    </div>
                </div>
            </div>
        </section>
        <section class="section3-card">
            <div class="container">
                <div class="section3-heading">Find the Perfect Package for You</div>
                <div class="section3-card-content" data-aos="fade-up"
                data-aos-anchor-placement="top-bottom">
                    <div class="section3-pay-card">
                        <div class="section3-card1" data-aos="flip-left">
                            <div class="card1-heading">
                                <div class="side1">
                                    <p>PLATINUM <small>MEMBERSHIP</small></p>
                                </div>
                                <div class="side2">
                                    <p>$ 99.00 <span>/Year</span></p>
                                </div>
                            </div>
                            <div class="card1-dis">
                                <p class="card1-heading-dis">The easiest way to get started selling e-commerce</p>
                                <p class="card1-disc">
                                    30% discount on subscription plans
                                </p>
                                <p class="card1-disc">
                                    30% discount on subscription plans
                                </p>
                            </div>
                        </div>
                        <div class="section3-card1" data-aos="flip-right">
                            <div class="card1-heading">
                                <div class="side1">
                                    <p>PLATINUM <small>MEMBERSHIP</small></p>
                                </div>
                                <div class="side2">
                                    <p>$ 99.00 <span>/Year</span></p>
                                </div>
                            </div>
                            <div class="card1-dis">
                                <p class="card1-heading-dis">The easiest way to get started selling e-commerce</p>
                                <p class="card1-disc">
                                    30% discount on subscription plans
                                </p>
                                <p class="card1-disc">
                                    30% discount on subscription plans
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="section4-email">
            <div class="container">
                <div class="section4-email-content" data-aos="fade-up"
                data-aos-anchor-placement="center-center">
                        <div class="section4-heading">Drop your e-mail here for more info.</div>
                        <div class="section4-btn">
                            <form action="sumbit">
                                <input type="email" placeholder="E-mail Here...">
                                <button type="submit">Send</button>
                            </form>
                        </div>
                </div>
            </div>
        </section>
    </main>