<?php 
    $privacy_p = search_array('privacy policy',$config_system);
    $fb = search_array('facebook',$config_system);
    $tw = search_array('twitter',$config_system);
    $inst = search_array('instagram',$config_system);
    $lin = search_array('Linkin',$config_system);
?>

<main class="about-page">
        <section class="section-about-page-heading">
            <div class="container">
                <div class="about-page-hero">
                    <div class="hero-side-2">
                        <h1>Privacy Policy</h1>
                    </div>
                </div>
            </div>
        </section>
        <section class="section-privacy-content">
            <div class="container">
                <div class="about-content">
                    <?php echo $privacy_p['value'] ; ?>
                </div>
            </div>
        </section>
        
        
        <section class="about-social">
            Join us
        </section>        
        <section class="social">
            <div class="container">
                <div class="about-social-icons" data-aos="fade-up"
                data-aos-duration="1500">
                <a href="<?php echo $fb['value'] ; ?>"><i class="fa fa-facebook-square" aria-hidden="true"></i></a>
                    <a href="<?php echo $tw['value'] ; ?>"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                    <a href="<?php echo $inst['value'] ; ?>"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                    <a href="<?php echo $lin['value'] ; ?>"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
                </div>
            </div>
        </section>
    </main>