<?php
	//ini_set('display_errors', 1);
//ini_set('display_startup_errors', 1);
//error_reporting(E_ALL);	
session_start();
require ('../model/product/productClass.php');
require ('../model/classDatabaseManager.php');

//if(!isset($_SESSION["email"])){
				//echo "<script>window.location.href='login.php';</script>";

//}
	$product = new Product();

$emailid= $_SESSION["logIn"];

$productdetails = $product->getproductdata();

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Store</title>
    <!-- lib -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <!-- lib end -->
    <link rel="stylesheet" href="css/slick.css">
    <link rel="stylesheet" href="css/store.css">
</head>
<body>

    <header></header>
    <section class="store-nav">
        <nav>
            <div class="container">
                <div class="nav">
                    <div class="logo">
                        <h3>LOGO</h3>
                    </div>
                    <div class="navigation">
                        <a href="../View/login.php">Login</a>
                        <a href="#">Product</a>
                        <a href="#">Contact</a>
                        <a href="#">About</a>
                    </div>
                </div>
            </div>
        </nav>
    </section>
    <section class="slider">
        <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
              <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
              <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
              <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
              <div class="carousel-item active">
                <div class="overlay">
                    <img src="asset/1.jpg" class="d-block w-100" alt="1">
                    <div class="carousel-caption d-none d-md-block">
                    </div>
                </div>
              </div>
              <div class="carousel-item">
                <img src="asset/2.jpg" class="d-block w-100" alt="2">
                <div class="carousel-caption d-none d-md-block">
                </div>
              </div>
              <div class="carousel-item">
                <img src="asset/3.jpg" class="d-block w-100" alt="3">
                <div class="carousel-caption d-none d-md-block">
                </div>
              </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>

    </section>
	<section class="section-product-slider" data-aos="fade-up">
     <?php 
								
									
									
						
										foreach($productdetails as $productList){
											
			  ?>
    
        <div class="card">
            <div class="product-img">
                <img src="asset/p1.jpg" alt="product">
            </div>
            <div class="product-content">
                <h1><?php echo $productList['name'];  ?></h1>
                <h3><?php echo $productList['description'];  ?></h3>
                <p><span class="dollor">$</span><?php echo $productList['price'];  ?></p>
                <div class="product-buy">
                <a href="productdetail.php?id=<?php echo $productList["product_id"]; ?>">add to cart</a>
                </div>
            </div>
        </div>
		
        
    
	<?php } ?>
		</section>
    <section class="features-product">
        <div class="heading">
            <h1 class="feature-heading">HEADING</h1>
        </div>
        <div class="des">
            <h3 class="des-heading">Your Description</h3>
        </div>
        <div class="product-slider"></div>
    </section>
    <div class="hero-product"  data-aos="flip-left">
        <div class="container">
            <div class="hero-card">
            <div class="left-side">
                <img src="asset/3.jpg" alt="hero">
            </div>
            <div class="right-side">
                <div class="right-heading">Product Name
                    <span class="hot-span">Hot Product</span></div>
                <div class="right-des">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dicta, explicabo soluta iusto voluptatum reiciendis quaerat ad voluptates ullam facilis nostrum eos impedit deleniti eveniet fugit repudiandae quia tempora enim magni!</div>
                <div class="right-price">$ 99.00</div>
                <div class="right-btn"><a href="#">Add to cart</a></div>
            </div>
            </div>

        </div>
    </div>
    <section class="features-product">
        <div class="heading">
            <h1 class="feature-heading">BEST PRODUCT</h1>
        </div>
        <div class="product-slider"></div>
    </section>
    <section class="section-product-slider" data-aos="fade-up"
    data-aos-duration="500">
        <div class="card">
            <div class="product-img">
                <img src="asset/p1.jpg" alt="product">
                <div class="sub-heading">Brand LOGO</div>
            </div>
            <div class="product-content">
                <h1>Product Name</h1>
                <h3>Description</h3>
                <p><span class="dollor">$</span> 99.00</p>
                <div class="product-buy">
                <a href="#">add to cart</a>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="product-img">
            <img src="asset/p2.jpg" alt="product">
            <div class="sub-heading">Brand LOGO</div>
            </div>
            <div class="product-content">
                <h1>Product Name</h1>
                <h3>Description</h3>
                <p><span class="dollor">$</span> 99.00</p>
                <div class="product-buy">
                <a href="#">add to cart</a>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="product-img">
            <img src="asset/p3.jpg" alt="product">
            <div class="sub-heading">Brand LOGO</div>
            </div>
            <div class="product-content">
                <h1>Product Name</h1>
                <h3>Description</h3>
                <p><span class="dollor">$</span> 99.00</p>
                <div class="product-buy">
                <a href="#">add to cart</a>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="product-img">
            <img src="asset/p1.jpg" alt="product">
            <div class="sub-heading">Brand LOGO</div>
            </div>
            <div class="product-content">
                <h1>Product Name</h1>
                <h3>Description</h3>
                <p><span class="dollor">$</span> 99.00</p>
                <div class="product-buy">
                <a href="#">add to cart</a>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="product-img">
            <img src="asset/p2.jpg" alt="product">  
            <div class="sub-heading">Brand LOGO</div>
            </div>
            <div class="product-content">
                <h1>Product Name</h1>
                <h3>Description</h3>
                <p><span class="dollor">$</span> 99.00</p>
                <div class="product-buy">
                <a href="#">add to cart</a>
                </div>
            </div>
        </div>
    </section>
    <section class="ad-product">
        <div class="container">
            <div class="ad-content">
                <div class="left-side-content" data-aos="fade-right">
                    <a class="ads-1" href="#">
                        <img src="asset/5c8474f363d797009216d1ad9362ea36.jpg" alt="ads">
                    </a>
                </div>
                <div class="right-side-content" data-aos="fade-up">
                    <a class="ads-2" href="#">
                        <img src="asset/New-Sport-Collection-Banner-Template.jpg" alt="">
                    </a>
                </div>
            </div>    
            <div class="ad-content">
                <div class="left-side-content2" data-aos="fade-up-right">
                    <a class="ads-2" href="#">
                        <img src="asset/Winter-Collection-Promotion-Banner-Template.jpg" alt="ads">
                    </a>
                </div>
                <div class="right-side-content2" data-aos="fade-up-left">
                    <a class="ads-1" href="#">
                        <img src="asset/sale-banner-template_24972-824.jpg" alt="ads">
                    </a>
                </div>
                </div>
            </div>
        
    </section>
    <section class="brand-logo">
        <div class="container">
            <div class="brand-content">
                <a href="#"  data-aos="flip-left">
                    <img src="asset/louis-vuitton-1.png" alt="logo">
                </a>
                <a href="#"  data-aos="flip-left">
                    <img src="asset/louis-vuitton-1.png" alt="logo">
                </a>
                <a href="#"  data-aos="flip-left">
                    <img src="asset/louis-vuitton-1.png" alt="logo">
                </a>
                <a href="#"  data-aos="flip-left">
                    <img src="asset/louis-vuitton-1.png" alt="logo">
                </a>
                <a href="#"  data-aos="flip-left">
                    <img src="asset/louis-vuitton-1.png" alt="logo">
                </a>
                <a href="#"  data-aos="flip-left">
                    <img src="asset/louis-vuitton-1.png" alt="logo">
                </a>
            </div>
        </div>
    </section>
    <section class="about">
        <div class="container">
            <div class="about-content">
                <div class="heading-about" data-aos="fade-right">
                    <img src="asset/2.jpg" alt="about">
                </div>
                <div class="para-about" data-aos="fade-left">
                <div class="about-content1">
                    <h2>About</h2>
                    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magni dolor aperiam sequi minima quia vero adipisci est, magnam recusandae aliquid odio possimus. Iure nisi temporibus quae iste id quisquam exercitationem?
                        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magni dolor aperiam sequi minima quia vero adipisci est, magnam recusandae aliquid odio possimus. Iure nisi temporibus quae iste id quisquam exercitationem?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magni dolor aperiam sequi minima quia vero adipisci est, magnam recusandae aliquid odio possimus. Iure nisi temporibus quae iste id quisquam exercitationem?
                    </p>
                </div>
            </div>
            </div>
        </div>
    </section>
    <section class="shipping">
        <div class="container">
            <div class="shipping-content">

            </div>
        </div>
    </section>
    <section class="contact">
        <div class="container">
            <div class="content-contact-form">
                <h2>Contact Us</h2>
                <form action="sumit">
                    <input type="text" placeholder="First Name">
                    <input type="text" placeholder="last Name">
                    <input type="email" placeholder="Your E-mail">
                    <input type="text" placeholder="Your Contact Number">
                    <textarea name="Your Question"cols="10" rows="1" placeholder="Your Messege Here"></textarea>
                    <button>Sumit</button>
                </form>
            </div>
        </div>

    </section>
    <section class="payment"></section>

    <!-- js lib -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"></script>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <!-- js lib end -->
    <script src="js/slick.min.js"></script>
    <script src="js/store.js"></script>
</body>
</html>