<?php 
    $tos = search_array('Term of services',$config_system);
    $fb = search_array('facebook',$config_system);
    $tw = search_array('twitter',$config_system);
    $inst = search_array('instagram',$config_system);
    $lin = search_array('Linkin',$config_system);
?>

<main class="about-page">
        <section class="section-about-page-heading">
            <div class="container">
                <div class="about-page-hero">
                    <div class="hero-side-2">
                        <h1>Terms Of Service</h1>
                    </div>
                </div>
            </div>
        </section>
        <section class="section-about-content">
            <div class="container">
                <div class="about-content">
                    <?php echo $tos['value'] ; ?>
                </div>
            </div>
        </section>
        
        <!-- <section class="vision-heading">
            OUR Vision
        </section>
        <section class="about-ourvision">
            <div class="container">
                <div class="about-vision-content">
                        <div class="vison-left" data-aos="zoom-out-up">
                            <img src="<?php echo $image;?>E-com.png" alt="vision-img">
                        </div>
                        <div class="vison-right" data-aos="zoom-out-up">
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. In sequi laudantium eligendi magnam similique explicabo dignissimos enim, minima sit iste. Magni asperiores molestias veritatis voluptate eos officiis hic necessitatibus esse?</p>
                        </div>
                </div>
            </div>
        </section> -->
        <section class="about-social">
            Join us
        </section>        
        <section class="social">
            <div class="container">
                <div class="about-social-icons" data-aos="fade-up"
                data-aos-duration="1500">
                   <a href="<?php echo $fb['value'] ; ?>"><i class="fa fa-facebook-square" aria-hidden="true"></i></a>
                    <a href="<?php echo $tw['value'] ; ?>"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                    <a href="<?php echo $inst['value'] ; ?>"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                    <a href="<?php echo $lin['value'] ; ?>"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
                </div>
            </div>
        </section>
    </main>