<?php
	//ini_set('display_errors', 1);
//ini_set('display_startup_errors', 1);
//error_reporting(E_ALL);	
session_start();
require ('../model/user/userClass.php');
require ('../model/classDatabaseManager.php');
//if(!isset($_SESSION["email"])){
				//echo "<script>window.location.href='login.php';</script>";

//}
	$login=new User();

$emailid= $_SESSION["logIn"];

$olddetails = $login->getuserdetails($emailid);

?>

	<!-- navbar -->
	<div class="navbar">
		<!-- nav left -->
		<ul class="navbar-nav">
			<li class="nav-item">
				<a class="nav-link">
					<i class="fas fa-bars" onclick="collapseSidebar()">
					</i>
				</a>
			</li>
			<li class="nav-item">
				<img src="assets/nazreen logo web.png" alt="Admin logo" class="logo logo-light">
				<img src="assets/nazreen logo white web.png" alt="Admin logo" class="logo logo-dark">
			</li>
		</ul>
		<!-- end nav left -->
		<!-- form -->
		<form class="navbar-search">
			<input type="text" name="Search" class="navbar-search-input" placeholder="What you looking for...">
			<i class="fas fa-search"></i>
		</form>
		<!-- end form -->
		<!-- nav right -->
		<ul class="navbar-nav nav-right">
			<li class="nav-item mode">
				<a class="nav-link" href="#" onclick="switchTheme()">
					<i class="fas fa-moon dark-icon"></i>
					<i class="fas fa-sun light-icon"></i>
				</a>
			</li>
			<li class="nav-item dropdown">
				<a class="nav-link">
					<i class="fas fa-bell dropdown-toggle" data-toggle="notification-menu"></i>
					<span class="navbar-badge">2</span>
				</a>
				<ul id="notification-menu" class="dropdown-menu notification-menu">
					<div class="dropdown-menu-header">
						<span>
							Notifications
						</span>
					</div>
					<div class="dropdown-menu-content overlay-scrollbar scrollbar-hover">
						<li class="dropdown-menu-item">
							<a href="#" class="dropdown-menu-link">
								<div>
									<i class="fas fa-gift"></i>
								</div>
								<span>
									Nazreen Consulting Demo.
									<br>
									<span>
										23/10/2020
									</span>
								</span>
							</a>
						</li>
						<li class="dropdown-menu-item">
							<a href="#" class="dropdown-menu-link">
								<div>
									<i class="fas fa-tasks"></i>
								</div>
								<span>
									Nazreen Consulting Demo.
									<br>
									<span>
										23/10/2020
									</span>
								</span>
							</a>
						</li>
					</div>
					<div class="dropdown-menu-footer">
						<span>
							View all notifications
						</span>
					</div>
				</ul>
			</li>
			<li class="nav-item avt-wrapper">
				<div class="avt dropdown">
					<img src="assets/Muzzamil.jpg" alt="User image" class="dropdown-toggle" data-toggle="user-menu">
					<ul id="user-menu" class="dropdown-menu">
						<li  class="dropdown-menu-item">
							<a class="dropdown-menu-link">
								<div>
									<i class="fas fa-user-tie"></i>
								</div>
								<span>Profile</span>
							</a>
						</li>
						<li  class="dropdown-menu-item">
							<a href="#" class="dropdown-menu-link">
								<div>
									<i class="fas fa-sign-out-alt"></i>
								</div>
								<span>Logout</span>
							</a>
						</li>
					</ul>
				</div>
			</li>
		</ul>
		<!-- end nav right -->
	</div>
	<!-- end navbar -->
	<!-- sidebar -->
	<div class="sidebar">
		<ul class="sidebar-nav">
			<li class="sidebar-nav-item">
				<a href="userdashboard.html" class="sidebar-nav-link">
					<div>
						<i class="fas fa-tachometer-alt"></i>
					</div>
					<span>
						Dashboard
					</span>
				</a>
			</li>
			<li class="sidebar-nav-item">
				<a href="userprofile.html" class="sidebar-nav-link active">
					<div>
						<i class="fab fa-sellsy"></i>
					</div>
					<span>User Profile</span>
				</a>
			</li>
			<li  class="sidebar-nav-item">
				<a href="purchase.html" class="sidebar-nav-link">
					<div>
						<i class="fas fa-search-dollar"></i>
					</div>
					<span>Purchase History</span>
				</a>
			</li>
			<li  class="sidebar-nav-item">
				<a href="userorder.html" class="sidebar-nav-link">
					<div>
						<i class="fas fa-file"></i>
					</div>
					<span>Order View</span>
				</a>
			</li>
			<li  class="sidebar-nav-item">
				<a href="productview.html" class="sidebar-nav-link">
					<div>
						<i class="fas fa-eye"></i>
					</div>
					<span>Purchas Product</span>
				</a>
			<li  class="sidebar-nav-item">
				<a href="cart.html" class="sidebar-nav-link">
					<div>
						<i class="fas fa-laptop-code"></i>
					</div>
					<span>Cart</span>
				</a>
			</li>
		</ul>
	</div>
	<!-- end sidebar -->
	<!-- main content -->
	<div class="wrapper">
		<div class="row">
			<div class="col-12 col-m-12 col-sm-12">
				<div class="user-content">
                    <div class="user-content-upper"></div>
                    <div class="user-content-dis">
                        <div class="container-content">
                            <form action="../Controller/userupdate.php" method="POST">
                            <div class="user-profile-upper">
                                 <input type="submit" class="editbtn1" name="updatebtn" value="Update" />
                                <a class="editbtn2" href="../View/userprofile.php">Cancel</a>
                            </div>
                            <div class="user-profile-dis">
                                <div class="user-image">
                                    <input type="file">
                                </div>
                                <div class="user-detail1">
                                    <label>First Name.</label>
                                    <input type="text" name="fname" value="<?php if(isset($olddetails)){echo $olddetails[0]['first_name']; } ?>">
                                    
                                    <label>last Name.</label>
                                    <input type="text" name="lname" value="<?php if(isset($olddetails)){echo $olddetails[0]['last_name']; } ?>">
                                    
                                    <label>contact No.</label>
                                    <input type="text" name="contactno" value="<?php if(isset($olddetails)){echo $olddetails[0]['contact_no']; } ?>">
                                </div>
                                <div class="edit-detail">
                                    <label>Address.</label>
                                    <input type="text" name="address" value="<?php if(isset($olddetails)){echo $olddetails[0]['address']; } ?>">
                                    <label>Address2.</label>
                                    <input type="text" name="address2" value="<?php if(isset($olddetails)){echo $olddetails[0]['address_2']; } ?>">
                                    <label>City.</label>
                                   <input type="text" name="city" value="<?php if(isset($olddetails)){echo $olddetails[0]['city']; } ?>">
                                    <label>State.</label>
                                   <input type="text" name="state" value="<?php if(isset($olddetails)){echo $olddetails[0]['state']; } ?>">
                                    <label>Zip Code.</label>
                                   <input type="text" name="zip" value="<?php if(isset($olddetails)){echo $olddetails[0]['zip']; } ?>">
                                    <label>Country.</label>
                                    <input type="text" name="country" value="<?php if(isset($olddetails)){echo $olddetails[0]['country']; } ?>">
                                </div>
                            </div>
                            </form>
                        </div>
                    </div>
                </div>
			</div>		
		</div>
	</div>
	<!-- end main content -->
