
	<!-- main content -->
	<div class="wrapper">
		<div class="row">
			<div class="col-12 col-m-12 col-sm-12">
				<div class="card">
					<div class="card-header">
						<h3>
							Table
						</h3>
						<i class="fas fa-ellipsis-h"></i>
		 			</div>
					<div class="card-content">
						<table>
							<thead>
								<tr>
									<th>Order ID</th>
									<th>Product Name</th>
									<th>Price</th>
									<th>Quantity</th>
									<th>Order Date & Time</th>
									<th>Order Status</th>
								</tr>
							</thead>
							<?php


foreach ($orderhistory as $orderlist){
	
?>
							<tbody>
								<tr>
									<td><?php echo $orderlist["orders_id"] ?></td>
									<td><?php echo $orderlist["name"] ?></td>
									<td>
										<span>$</span><?php echo $orderlist["totalprice"] ?>
										
									</td>
									<td><?php echo $orderlist["quantity"] ?></td>
									<td><?php echo $orderlist["order_dt"] ?></td>
                                    <td><span class="dot">
                                        <i class="bg-success"></i>
                                        <?php echo $orderlist["order_status"] ?>
                                    </span></td>
									
								</tr>
							</tbody>
							<?php 
}
?>
						</table>
					</div>
				</div>
			</div>		
		</div>
	</div>

	<!-- end main content -->
	