
	<!-- navbar -->
	<div class="navbar">
		<!-- nav left -->
		<ul class="navbar-nav">
			<li class="nav-item">
				<a class="nav-link">
					<i class="fas fa-bars" onclick="collapseSidebar()">
					</i>
				</a>
			</li>
			<li class="nav-item">
				<img src="assets/nazreen logo web.png" alt="Admin logo" class="logo logo-light">
				<img src="assets/nazreen logo white web.png" alt="Admin logo" class="logo logo-dark">
			</li>
		</ul>
		<!-- end nav left -->
		<!-- form -->
		<form class="navbar-search">
			<input type="text" name="Search" class="navbar-search-input" placeholder="What you looking for...">
			<i class="fas fa-search"></i>
		</form>
		<!-- end form -->
		<!-- nav right -->
		<ul class="navbar-nav nav-right">
			<li class="nav-item mode">
				<a class="nav-link" href="#" onclick="switchTheme()">
					<i class="fas fa-moon dark-icon"></i>
					<i class="fas fa-sun light-icon"></i>
				</a>
			</li>
			<li class="nav-item dropdown">
				<a class="nav-link">
					<i class="fas fa-bell dropdown-toggle" data-toggle="notification-menu"></i>
					<span class="navbar-badge">2</span>
				</a>
				<ul id="notification-menu" class="dropdown-menu notification-menu">
					<div class="dropdown-menu-header">
						<span>
							Notifications
						</span>
					</div>
					<div class="dropdown-menu-content overlay-scrollbar scrollbar-hover">
						<li class="dropdown-menu-item">
							<a href="#" class="dropdown-menu-link">
								<div>
									<i class="fas fa-gift"></i>
								</div>
								<span>
									Nazreen Consulting Demo.
									<br>
									<span>
										23/10/2020
									</span>
								</span>
							</a>
						</li>
						<li class="dropdown-menu-item">
							<a href="#" class="dropdown-menu-link">
								<div>
									<i class="fas fa-tasks"></i>
								</div>
								<span>
									Nazreen Consulting Demo.
									<br>
									<span>
										23/10/2020
									</span>
								</span>
							</a>
						</li>
					</div>
					<div class="dropdown-menu-footer">
						<span>
							View all notifications
						</span>
					</div>
				</ul>
			</li>
			<li class="nav-item avt-wrapper">
				<div class="avt dropdown">
					<img src="assets/Muzzamil.jpg" alt="User image" class="dropdown-toggle" data-toggle="user-menu">
					<ul id="user-menu" class="dropdown-menu">
						<li  class="dropdown-menu-item">
							<a class="dropdown-menu-link">
								<div>
									<i class="fas fa-user-tie"></i>
								</div>
								<span>Profile</span>
							</a>
						</li>
						<li  class="dropdown-menu-item">
							<a href="#" class="dropdown-menu-link">
								<div>
									<i class="fas fa-sign-out-alt"></i>
								</div>
								<span>Logout</span>
							</a>
						</li>
					</ul>
				</div>
			</li>
		</ul>
		<!-- end nav right -->
	</div>
	<!-- end navbar -->
	<!-- sidebar -->
	<div class="sidebar">
		<ul class="sidebar-nav">
			<li class="sidebar-nav-item">
					<a href="../View/userdashboard.php" class="sidebar-nav-link  active">
					<div>
						<i class="fas fa-tachometer-alt"></i>
					</div>
					<span>
						Dashboard
					</span>
				</a>
			</li>
			<li class="sidebar-nav-item">
				<a href="../View/userprofile.php" class="sidebar-nav-link">
					<div>
						<i class="fab fa-sellsy"></i>
					</div>
					<span>User Profile</span>
				</a>
			</li>
			<li  class="sidebar-nav-item">
				<a href="../View/purchase.php" class="sidebar-nav-link">
					<div>
						<i class="fas fa-search-dollar"></i>
					</div>
					<span>Purchase History</span>
				</a>
			</li>
			<li  class="sidebar-nav-item">
				<a href="../View/userorder.php" class="sidebar-nav-link">
					<div>
						<i class="fas fa-file"></i>
					</div>
					<span>Order View</span>
				</a>
			</li>
			
		</ul>
	</div>
	<!-- end sidebar -->
	<!-- main content -->
	<div class="wrapper">
		<div class="row">
			<div class="col-12 col-m-12 col-sm-12">
				<div class="container-content">
                    <div class="user-profile-upper">
                        <a href="?page=useredit">Edit</a>
                    </div>
                    <div class="user-profile-dis">
                        <div class="user-image">
                          
                        </div>
                        <div class="user-detail1">
                            <label>First Name.</label>
                            <p class="first-name"> <?php if(isset($olddetails)){echo $olddetails[0]['first_name']; } ?></p>
                            
                            <label>last Name.</label>
                            <p class="last-name">  <?php if(isset($olddetails)){echo $olddetails[0]['last_name']; } ?></p>
                            
                            <label>contact No.</label>
                            <p class="Contact-no"><?php if(isset($olddetails)){echo $olddetails[0]['contact_no']; } ?></p>
                        </div>
                        <div class="user-detail2">
                            <label>Address.</label>
                            <p class="address-1"><?php if(isset($olddetails)){echo $olddetails[0]['address']; } ?></p>
                            <label>Address2.</label>
                            <p class="address-2"><?php if(isset($olddetails)){echo $olddetails[0]['address_2']; } ?></p>
                            <label>City.</label>
                            <p class="city"><?php if(isset($olddetails)){echo $olddetails[0]['city']; } ?></p>
                            <label>State.</label>
                            <p class="state"><?php if(isset($olddetails)){echo $olddetails[0]['state']; } ?></p>
                            <label>Zip Code.</label>
                            <p class="Zip-code"><?php if(isset($olddetails)){echo $olddetails[0]['zip']; } ?></p>
                            <label>Country.</label>
                            <p class="Country"><?php if(isset($olddetails)){echo $olddetails[0]['country']; } ?></p>
                        </div>
                    </div>
                </div>
			</div>		
		</div>
	</div>
	<!-- end main content -->
