<?php 
    $video_heading = search_array('video Title',$config_system);
    $video_dis = search_array('video short dis',$config_system);
    $video_code = search_array('video dis',$config_system);
?>


<main>
        <section class="learn-hero">
            <div class="container">
                <div class="learn-hero-content">
                    <div class="learn-heading" data-aos="zoom-out-down">
                        Video
                    </div>
                </div>
            </div>
        </section>
        
        <section class="section1-Guide">
            <div class="container">
                <div class="section1-Guide-content" data-aos="fade-right">
                    <div class="guide-heading-hero"><?php echo $video_heading['value'] ; ?></div>
                    <div class="guide-heading-pera"><?php echo $video_dis['value'] ; ?></div>
                </div>
            </div>
        </section>
        <section class="section2-Guide">
            <div class="container">
                <?php echo $video_code  ['value'] ; ?>
            </div>
        </section>
    </main>