<main>
        <section class="learn-hero">
            <div class="container">
                <div class="learn-hero-content">
                    <div class="learn-heading" data-aos="zoom-out-down">
                        Showcase
                    </div>
                </div>
            </div>
        </section>
    </main>

    <section class="showcase-hero">
        <div class="container">
            <div class="showcase-heading" data-aos="fade-right">
                Our Theme Show Case
            </div>
        </div>
    </section>

    <section class="showcase-theme">
        <div class="container">
            <div class="s-theme-content">
                <div class="s-theme-row">
                    <div class="s-theme-1" data-aos="fade-up-right">
                        <div class="theme-upper">
                            <img src="../asset/theme-4.jpg" alt="theme1">
                        </div>
                        <div class="theme-Content">
                            Our SuperMarket Theme.
                            <p>For Your Food & Grocery Busniess, the Best Option is Our SuperMarket Theme Which is easy to use and have a Fresh Interface.</p>
                        </div>
                        <div class="theme-btn">
                           <a href="#">Click Here To View The Demo</a>
                        </div>
                    </div>
                    <div class="s-theme-1" data-aos="fade-left">
                        <div class="theme-upper">
                            <img src="../asset/theme-3.jpg" alt="theme2">
                        </div>
                        <div class="theme-Content">
                            Our Restaurant Theme.
                            <p>For Your Restaurant Busniess, the Best Option is Our Restaurant Theme Which give you every main option to run a Restaurant Website.</p>
                        </div>
                        <div class="theme-btn">
                           <a href="#">Click Here To View The Demo</a>
                        </div>
                    </div>
                </div>
                <div class="s-theme-row">
                    <div class="s-theme-1" data-aos="zoom-in-up">
                        <div class="theme-upper">
                            <img src="../asset/theme-2.jpg" alt="theme1">
                        </div>
                        <div class="theme-Content">
                            Our Pharmacy Theme.
                            <p>For Your Medical Busniess, the Best Option is Our Pharmacy Theme. its fresh eyes freshing and easy to use.</p>
                        </div>
                        <div class="theme-btn">
                           <a href="#">Click Here To View The Demo</a>
                        </div>
                    </div>
                    <div class="s-theme-1" data-aos="zoom-in-up">
                        <div class="theme-upper">
                            <img src="../asset/theme-1.jpg" alt="theme2">
                        </div>
                        <div class="theme-Content">
                            Our Fashion Theme.
                            <p>For Your E-Commerce Busniess, the Best Option is Our Fashion Theme Which give you the best experiance of online shopping .</p>
                        </div>
                        <div class="theme-btn">
                           <a href="#">Click Here To View The Demo</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>