<?php require $footer;?>	
    <div class="container-varification">
    <div class="login-content">
        <form action="index.html">
            <h2 class="title">Change your Password</h2>
            <div class="input-div one">
              <div class="i">
                <i class="fa fa-user"></i>
              </div>
              <div class="div">
                <h5>Old Password</h5>
                <input type="text" class="input" required />
              </div>
            </div>
            <div class="input-div one">
                <div class="i">
                  <i class="fa fa-user"></i>
                </div>
                <div class="div">
                  <h5>New Password</h5>
                  <input type="password" class="input" id="password" required />
                </div>
              </div>
              <div class="input-div one">
                <div class="i">
                  <i class="fa fa-user"></i>
                </div>
                <div class="div">
                  <h5>Confirm New Password</h5>
                  <input type="password" class="input" id="confirmPassword" required />
                </div>
              </div>            
              <span id="message"></span>
            <input type="submit" class="btn" value="Change" />
            
          </form>
          
                   
    </div>
    </div>
