
<?php require $footer;?>	
	<!-- main content -->
	<div class="wrapper">
		<div class="row">
			<div class="col-12 col-m-12 col-sm-12">
				<div class="card">
					<div class="card-header">
						<h3>
							Table
						</h3>
						<i class="fas fa-ellipsis-h"></i>
					</div>
					<div class="card-content">
						<table>
							<thead>
								<tr>
									<th>#</th>
									<th>Product Name</th>
									<th>Price</th>
									<th>Quantity</th>
									<th>Order Time</th>
									<th>Order Date</th>
									<th>Order Status</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>1</td>
									<td>Shirt</td>
									<td>
										<span>$</span>20
										
									</td>
									<td>2</td>
									<td>07:00 A.M</td>
                                    <td>10/12/2020</td>
                                    <td><span class="dot">
                                        <i class="bg-success"></i>
                                        Completed
                                    </span></td>
                                </tr>
                                <tr>
									<td>1</td>
									<td>Shirt</td>
									<td>
										<span>$</span>20
										
									</td>
									<td>2</td>
									<td>07:00 A.M</td>
                                    <td>10/12/2020</td>
                                    <td><span class="dot">
                                        <i class="bg-warning"></i>
                                        In progress
                                    </span></td>
                                </tr>
                                <tr>
									<td>1</td>
									<td>Shirt</td>
									<td>
										<span>$</span>20
										
									</td>
									<td>2</td>
									<td>07:00 A.M</td>
                                    <td>10/12/2020</td>
                                    <td><span class="dot">
                                        <i class="bg-primary"></i>
                                        Pending
                                    </span></td>
                                </tr>
                                <tr>
									<td>1</td>
									<td>Shirt</td>
									<td>
										<span>$</span>20
										
									</td>
									<td>2</td>
									<td>07:00 A.M</td>
                                    <td>10/12/2020</td>
                                    <td>										<span class="dot">
                                        <i class="bg-danger"></i>
                                        Delayed
                                    </span></td>
                                </tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>		
		</div>
	</div>

