

INSERT INTO `languages`(`value`, `eng`, `pt`) VALUES 
('Product','Product','default')
, ('About','About','default')
, ('Shopping ','shopping','default')
, ('Cart','Cart','default')
, ('Cart','is empty!','default')
, ('Choose','Chose','default')
, ('Products','Products','default')
, ('Subtotal','Subtotal','default')
, ('View Cart','View Cart','default')
, ('Clear','Clear','default')
, ('Please','please','default')
, ('enter','enter','default')
, ('Your','Your','default')
, ('name','name','default')
, ('to','to','default')
, ('continue!','continue!','default')
, ('Your','Your','default')
, ('Name','Name','default')
, ('here','here','default')
, ('Your','Your','default')
, ('E-mail','E-mail','default')
, ('here','here','default')
, ('Your','your','default')
, ('Phone','Phone','default')
, ('Number','Number','default')
, ('Here','Here','default')
, ('Enter','Enter','default')
, ('Feature','Feature','default')
, ('Products','Products','default')
, ('Latest','Latest','default')
, ('Products','Products','default')
, ('Add','Add','default')
, ('to','to','default')
, ('cart','cart','default')
, ('About','About','default')
, ('Us','Us','default')
, ('Our Product','Our Product','default')
, ('the best','the best','default')
, ('product you','product you','default')
, ('can find','can find','default')
, ('Veggies','Veggies','default')
, ('Fruits','Fruits','default')
, ('100% Organic','100% Organic','default')
, ('Products','Products','default')
, ('Milk','Milk','default')
, ('Fruits','Fruits','default')
, ('Flour','Flour','default')
, ('Fresh Meat','Fresh Meat','default')
, ('Fresh Vegies','Fresh Vegies','default')
, ('Eggs','Eggs','default')
, ('Subscribe','Subscribe','default')
, ('to our','to our','default')
, ('Newsletter','Newsletter','default')
, ('Free Shipping','Free Shipping','default')
, ('Free Shipping','Free Shipping','default')
, ('Helpline','Helpline','default')
, ('Customer Support','Customer Support','default')
, ('Special Discount','Special Discount','default')
, ('for all','for all','default')
, ('Grocery products','Grocery products','default')



, ('MENU','MENU','default')
, ('RESERVATION','RESERVATION','default')
, ('Contact','Contact','default')
, ('DELICIOUS','DELICIOUS','default')
, ('FOOD','FOOD','default')
, ('Restaurant','Restaurant','default')
, ('THE','THE','default')
, ('RESTAURANT','RESTAURANT','default')
, ('TODAYS ','TODAYS ','default')
, ('MENU','MENU','default')
, ('A little','A little','default')
, ('about','about','default')
, ('us','us','default')
, ('and','and','default')
, ('a breif','a breif','default')
, ('history','history','default')
, ('of','of','default')
, ('how','how','default')
, ('we','we','default')
, ('started','started','default')
, ('Cow','Cow','default')
, ('Meat','Meat','default')
, ('Dish','Dish','default')
, ('Discription','Discription','default')
, ('this','this','default')
, ('is','is','default')
, ('delicious','delicious','default')
, ('ORDER NOW','ORDER NOW','default')
, ('RESERVATIONS','RESERVATIONS','default')
, ('Book','Book','default')
, ('a table','a table','default')
, ('online.','online.','default')
, ('Leads','Leads','default')
, ('will','will','default')
, ('reach','reach','default')
, ('in','in','default')
, ('your','your','default')
, ('email.','email.','default')
, ('Date','Date','default')
, ('Your Name','Your Name','default')
, ('Time','Time','default')
, ('Email Address','Email Address','default')
, ('Guests','Guests','default')
, ('Phone Number','Phone Number','default')
, ('MAKE RESERVATION','','default')
, ('You','You','default')
, ('can','can','default')
, ('also','also','default')
, ('call:','call:','default')
, ('to','to','default')
, ('make','make','default')
, ('a','a','default')
, ('reservation.','reservation.','default')
, ('OUR FEATURES','OUR FEATURES','default')
, ('Dishes','Dishes','default')
, ('OUR MENU','OUR MENU','default')
, ('ALL','ALL','default')
, ('STARTERS','STARTERS','default')
, ('BREAKFAST','BREAKFAST','default')
, ('LUNCH','LUNCH','default')
, ('DINNER','DINNER','default')
, ('DESSERTS','DESSERTS','default')
, ('ABOUT US','ABOUT US','default')
, ('YOUR TAG LINE','YOUR TAG LINE','default')
, ('love','love','default')
, ('posting','posting','default')
, ('photos','photos','default')
, ('of our','of our','default')
, ('coustomers','coustomers','default')
, ('having','having','default')
, ('a good time','a good time','default')
, ('ABOUT US','ABOUT US','default')
, ('REACH US','REACH US','default')
, ('CONTACT','CONTACT','default')
, ('ADDRESS','ADDRESS','default')
, ('WORKING HOURS','WORKING HOURS','default')
, ('FOLLOW US','FOLLOW US','default')
, ('Full Name','','default')
, ('Email Address','Email Address','default')
, ('Subject','Subject','default')
, ('Message','Message','default')
, ('SEND MESSAGE','','default')
, ('MENU','MENU','default')
, ('OUR MENU','OUR MENU','default')
, ('ALL','ALL','default')
, ('BREAKFAST','BREAKFAST','default')
, ('LUNCH','LUNCH','default')
, ('DINNER','DINNER','default')
, ('DESSERTS','DESSERTS','default')
, ('DISH 1','DISH 1','default')
, ('DISH 1','DISH 1','default')
, ('DISH 1','DISH 1','default')
, ('DISH 1','DISH 1','default')




, ('Product','Product','default')
, ('About','About','default')
, ('Flat 25% Off','Flat 25% Off','default')
, ('Medicine order','Medicine order','default')
, ('Add','Add','default')
, ('to','to','default')
, ('cart','cart','default')
, ('FEATURE PRODUCT','FEATURE PRODUCT','default')
, ('HERBAL PRODUCTS','HERBAL PRODUCTS','default')
, ('Deal of','Deal of','default')
, ('the Day','the Day','default')
, ('Best Digital','Best Digital','default')
, ('Thermometer','Thermometer','default')
, ('In The Market.','In The Market.','default')
, ('SHOP NOW','SHOP NOW','default')
, ('BEST','BEST','default')
, ('SELLING','SELLING','default')
, ('PRODUCTS','PRODUCTS','default')
, ('LATEST','LATEST','default')
, ('PRODUCTS','PRODUCTS','default')
, ('ABOUT US','ABOUT US','default')




, ('Product','Product','default')
, ('About','About','default')
, ('Best Product','Best Product','default')
, ('BEST DEAL','BEST DEAL','default')
, ('25% OFF','25% OFF','default')
, ('BEST WOMENS FASHION','BEST WOMENS FASHION','default')
, ('Show Now','Show Now','default')
, ('BEST DEAL','BEST DEAL','default')
, ('25% OFF','25% OFF','default')
, ('BEST MENS FASHION','BEST MENS FASHION','default')
, ('Show Now','Show Now','default')
, ('FEATURE PRODUCTS','FEATURE PRODUCTS','default')
, ('Whats New','Whats New','default')
, ('Fresh & New','Fresh & New','default')
, ('Style Option','Style Option','default')
, ('Multiple Images product','Multiple Images product','default')
, ('this is best','this is best','default')
, ('Hot Product','Hot Product','default')
, ('LATEST PRODUCT','LATEST PRODUCT','default')
, ('About','About','default')









