<div class="wrapper">
    <div class="row">
        <div class="flashdeal-dashboard-main">
        <h1 data-aos="fade-right" data-aos-duration="1500">Abandoned Cart</h1>
        <!-- <form data-aos="fade-down" data-aos-duration="1500">
            <input type="text">
            <input class="s-btn" type="button" value="Search">
        </form> -->
    </div>
    <div class="Flashdeal-table-main" data-aos="zoom-out-up" data-aos-duration="600">
        <form action="">
            <table>
                <tr>
                    <th>Serial.No</th>
                    <th>Name</th>
                    <th>Product Img</th>
                    <th>Price</th>
                    <th>Date</th>
                    <th>Option</th>
                </tr>
                <?php  
                        if (!empty($data)){
                            $count = 1;
                            foreach ($data as $key => $value) {
                                $product_image  = getproductsimages($value['product_id']);  
                                $product_name   = getproductnamebyid($value['product_id']);
                                $user_name      = getuserinfo($value['user_id']);
                                $price          = getproductinfo($value['product_id']);
                                $date           = getabandoncart($value['user_id']);
                                // var_dump($user_name);
                                // var_dump($value);
                            
                        ?> 
                <tr>
                
                    <td><?= $count; ?></td>
                    <td><?= $user_name[0]['first_name']; ?></td>
                    <td>
                        <img src="<?= $product_directory. $product_image[0]['image_path']; ?> " alt="<?= $product_name[0]['name']; ?>">
                    </td>
                    <td><?= $price[0]['price']; ?></td>
                    <td><?= $date[0]['date']; ?></td>
                    <td class="option">
                        <a href="?page=email_dashboard">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Send Email
                        </a>
                        <a href="#">
                            <i class="fa fa-trash" aria-hidden="true"></i> Remove
                        </a>
                    </td>
                </tr>
                <?php  
                    $count ++;
                } }  ?>
            </table>
        </form>
    </div>
</div>
</div>