<div class="wrapper">
    <div class="row">
        <div class="flashdeal-dashboard-main">
        <h1 data-aos="fade-right" data-aos-duration="1500">Abandoned Cart</h1>
        <form data-aos="fade-down" data-aos-duration="1500">
            <input type="text">
            <input class="s-btn" type="button" value="Search">
        </form>
    </div>
    <div class="Flashdeal-table-main" data-aos="zoom-out-up" data-aos-duration="600">
        <form action="">
            <table>
                <tr>
                    <th>Serial.No</th>
                    <th>Name</th>
                    <th>Product Img</th>
                    <th>Price</th>
                    <th>Date</th>
                    <th>Page Link</th>
                    <th>Option</th>
                </tr>
                <tr>
                    <td>1</td>
                    <td>Muzzamil</td>
                    <td>
                        <img src="https://demo.sirv.com/chair.jpg?scale.width=71  " alt="">
                    </td>
                    <td>20$</td>
                    <td>03/01/2021</td>
                    <td> 
                        <a href="#">www.google.com</a>
                    </td>
                    <td class="option">
                        <a href="#">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Send Email
                        </a>
                        <a href="#">
                            <i class="fa fa-trash" aria-hidden="true"></i> Remove
                        </a>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>
</div>