<?php 
            $about_desc = search_array('AboutDiscribtion',$config_system);
            $about_vission = search_array('about our vision',$config_system);
            $about_team_name = search_array('our team Name',$config_system);
            $about_team_position = search_array('our team position',$config_system);
            $about_team_company = search_array('our team company',$config_system);
?>
<div class="wrapper">
    <div class="row">
        <div class="dashboard-footer">
            <h1 data-aos="fade-right" data-aos-duration="2000" >About Us Edit</h1>
        </div>
        <div class="dashboard-footer-about" data-aos="zoom-out-right" data-aos-duration="1000">
            <form action="<?= $controller; ?>" class="d-footer-logo-about" id="formDesc">
                <input type="hidden" name="formDesc">
                <div class="dashboard-footer-about">
                    <div class="footer-about-upload-label">
                        <label for="">About Discribtion :</label>
                    </div>
                    <div class="footer-about-upload-content">
                        <textarea name="about_desc" id="myTextArea" class="tinymce" require><?php echo $about_desc['value'];?></textarea>
                    </div>
                </div>
                <div class="dashboard-footer-about-btn">
                    <input type="button" value="Upadate" onclick="submitFormDesc()">
                </div>
            </form>
        </div>
        <div class="about-us-dashboard-main2">
        <div class="dashboard-footer-section-2">
            <div class="dashboard-footer-contact" data-aos="fade-up-right" data-aos-duration="1000">
                <h1>Our Team info</h1>
                <form action="<?= $controller; ?>" class="d-footer-logo-contact" id="cntForm">
                    <input type='hidden' name="cntForm">
                    <div class="dashboard-footer-contact-add">
                        <div class="footer-contact-add-head">
                            <label for="">Name </label>
                        </div>
                        <div class="footer-contact-add-input">
                            <input type='text' name="team_name" value="<?php echo $about_team_name['value'];?>" />
                        </div>
                    </div>
                    <div class="dashboard-footer-contact-phone">
                        <div class="footer-contact-phone-head">
                            <label for="">Position</label>
                        </div>
                        <div class="footer-contact-phone-input">
                            <input type='text' name="team_position" value="<?php echo $about_team_position['value'];?>" />
                        </div>
                    </div>
                    <div class="dashboard-footer-contact-phone">
                        <div class="footer-contact-phone-head">
                            <label for="">Image</label>
                        </div>
                        <div class="footer-contact-phone-input">
                            <input type='file' name="team_img" />
                        </div>
                    </div>
                    <div class="dashboard-footer-contact-email">
                        <div class="footer-contact-email-head">
                            <label for="">Company Name</label>
                        </div>
                        <div class="footer-contact-email-input">
                            <input type='text' name="team_comp"  value="<?php echo $about_team_company['value'];?>"/>
                        </div>
                    </div>
                    <div class="dashboard-footer-contact-btn">
                        <input type="button" value="Upadate" onclick="submitFormCnt()">
                    </div>
                </form>
            </div>
        </div>
        <div class="dashboard-footer-bottom" data-aos="fade-left" data-aos-duration="1000" >
            <form action="<?= $controller; ?>" class="dashboard-footer-bottom-content" id="visionForm">
                <input type="hidden" name="visionForm">
                <div class="d-footer-copyright">
                    <div class="d-footer-copyright-head">
                        <label>Our Vision</label>
                    </div>
                    <div class="d-footer-copyright-input">
                        <textarea class="tinymce" id="myTextAreaSec" name="vision" require><?php echo $about_vission['value']; ?></textarea>
                    </div>
                </div>
                <div class="d-footer-social-media">
                    <div class="d-footer-social-links">
                        <div class="footer-social-link-icon">
                            <input type="button" value="Update" onclick="submitFormVision()">
                        </div>
                    </div>
                </div>
            </form>
        </div>
        </div>
        <div class="about-us-dashboard-main">
            <form>
                <table>
                    <tr>
                        <th>Serial No.</th>
                        <th>Name</th>
                        <th>Position</th>                
                        <th>img</th>                
                        <th>Company Name</th>                
                        <th>Option</th>                
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Muzzamil</td>
                        <td>front-end dev</td>
                        <td>whats???</td>
                        <td>Nazreen Consulting</td>
                        <td>
                            <a href="#">
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit
                            </a>
                            <a href="#">
                                <i class="fa fa-trash" aria-hidden="true"></i> Remove
                            </a>
                        </td>
                    </tr>                
                </table>
            </form>
        </div>
    </div>
</div>
</div>
<script>
    
  function submitFormDesc(form){
    var myContent = tinymce.get("myTextArea").getContent();
      $('#myTextArea').html(myContent);
    var url = $('#formDesc').attr("action");
    
    var formData = $('#formDesc').serializeArray();
    
    $.post(url, formData).done(function (data) {
        if(data == 1){
      alert('success');
      location.reload();
    }else{
      alert('error');
    }
    });
}
function submitFormCnt(form){
    
    var url = $('#cntForm').attr("action");
    
    var formData = $('#cntForm').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
      alert('success');
      location.reload();
    }else{
      alert('error');
    }
    });
}
function submitFormVision(form){
    
    var myContent = tinymce.get("myTextAreaSec").getContent();
      $('#myTextAreaSec').html(myContent);
    var url = $('#visionForm').attr("action");
    
    var formData = $('#visionForm').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
      alert('success');
      location.reload();
    }else{
      alert('error');
    }
    });
    
}


</script>
