<div class="wrapper">
    <div class="row">
        <div class="order-dashboard-main">
            <h1 data-aos="fade-right"data-aos-duration="1500">Activity</h1>
        </div>
        <div class="order-table-main" data-aos="zoom-in-up" data-aos-duration="600">
            <form action="">
                <table>
                    <tr>
                        <th>User Name</th>
                        <th>Activity Type</th>
                        <th>Brand ID</th>
                        <th>Vendor ID</th>
                        <th>Date/Time</th>
                        
                    </tr>
                    <?php
                        if(empty($data)){
                            echo 'No Data';
                        }else{
                            foreach ($data as $key => $value) {


                                $user_data = getuserinfo($value['user_id']);
                                if(empty($user_data[0]['first_name'])){
                                  $username = 'user';
                                }else{
                                  $username =  $user_data[0]['first_name'];
                                }


                            
                                if($value['vendor_id'] == 0){
                                    $vendor_name = 'No Vendor';
                                }else{
                                 $vendor_data =    getbranchbybranchid('',$value['vendor_id']);
                                    $vendor_name =  $vendor_data[0]['name'];
                                }


                            if($value['brand_id'] == 0){
                                    $brand_name = 'No Vendor';
                                }else{
                                 $brand_data =    getvendors('',$value['brand_id'],'FALSE');
                                    $brand_name =  $brand_data[0]['name'];
                                }



                                
                            
?>

 <tr>
                        <td><?=  $username  ?></td>
                        <td><?= $value['activity']?></td>
                        <td><?= $brand_name ;?></td>
                        <td><?=  $vendor_name ;?></td>
                        <td><?= $value['datetime'] ;?></td>
                        
                    </tr> 


<?php
                            }

                    ?>
                  
                    <?php 
                }
                ?>
                </table>
            </form>
        </div>
    </div>
</div>