<div class="wrapper">
    <div class="row">
        <div class="order-dashboard-main">
            <h1 data-aos="fade-right"data-aos-duration="1500">Activity</h1>
        </div>
        <div class="order-table-main" data-aos="zoom-in-up" data-aos-duration="600">
            <form action="">
                <table>
                    <tr>
                        <th>User Name</th>
                        <th>Activity Type</th>
                        <th>Brand ID</th>
                        <th>Vendor ID</th>
                        <th>Time</th>
                        <th>Date</th>
                    </tr>
                    <tr>
                        <td>Muzzamil Qureshi</td>
                        <td>Create Add Product</td>
                        <td>pakistan Branch</td>
                        <td>Coca Cola</td>
                        <td>5:46 PM</td>
                        <td>5/12/2021</td>
                    </tr> 
                    <tr>
                        <td>Jimmy</td>
                        <td>Update the Setting</td>
                        <td>pak_hp</td>
                        <td>Dell</td>
                        <td>2:17 PM</td>
                        <td>5/18/2021</td>
                    </tr> 
                    <tr>
                        <td>andy</td>
                        <td>Change the password</td>
                        <td>KFC-Norway</td>
                        <td>KFC</td>
                        <td>7:42 PM</td>
                        <td>5/20/2021</td>
                    </tr> 
                    <tr>
                        <td>Carlos</td>
                        <td>Change Store</td>
                        <td>Supera Krachi</td>
                        <td>Supera inc</td>
                        <td>3:13 PM</td>
                        <td>5/25/2021</td>
                    </tr> 
                    <tr>
                        <td>ali</td>
                        <td>Change logo</td>
                        <td>Devesa</td>
                        <td>Apple</td>
                        <td>8:08 PM</td>
                        <td>5/26/2021</td>
                    </tr>
                    <tr>
                        <td>Zubair Ayub</td>
                        <td>Edit Footer</td>
                        <td>Karachi_Branch</td>
                        <td>Levis</td>
                        <td>4:11 PM</td>
                        <td>5/29/2021</td>
                    </tr> 
                </table>
            </form>
        </div>
    </div>
</div>