<div class="wrapper">
    <div class="row">
        <div class="order-dashboard-main">
        <h1 data-aos="fade-right"data-aos-duration="1500">Add New Category</h1>
    </div>
    <div class="add-new-category" data-aos="zoom-in-up" data-aos-duration="600">
        <form action="<?= $controller; ?>" id="newCat">
            <div class="add-new-cat-head">
                Category Information
            </div>
            <div class="add-new-cat-content">
                <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                        Name
                    </div>
                    <div class="add-new-cat-content-input">
                        <input type="text" name="cat_name">
                    </div>
                </div>
                <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                        Type
                    </div>
                    <div class="add-new-cat-content-input">
                        <select name="cat_type" id="">
                            <option value="1">Physical</option>
                            <option value="2">Digital</option>
                        </select>
                    </div>
                </div>
                 <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                        Meta Title
                    </div>
                    <div class="add-new-cat-content-input">
                        <input type="text" name="cat_meta_title">
                    </div>
                </div>
                <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                        Meta Description
                    </div>
                    <div class="add-new-cat-content-input">
                        <input type="text" name="cat_meta_description">
                    </div>
                </div>
                <div class="add-new-cat-content-btn">
                    <input type="button" value="Save" onclick="submitForm()">
                </div>
            </div>
        </form>
    </div>
</div>
</div>
<script>
  function submitForm(form){
    
    var url = $('#newCat').attr("action");
    
    var formData = $('#newCat').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 0){
      alert('New Category is added');
    }else if(data == 1){
      alert('New Category is not added');
      alert(data);
    }
    else if(data == 2){
      alert('Category already exits');
    }
    });
}
</script> 