<div class="wrapper">
    <div class="row">
        <div class="order-dashboard-main">
        <h1 data-aos="fade-right"data-aos-duration="1500">Currency</h1>
    </div>
    <div class="add-new-category" data-aos="zoom-in-up" data-aos-duration="600">
        <form action="<?= $controller; ?>" id="newCurrency">
            <div class="add-new-cat-head">
            Currency Information
            </div>
            <div class="add-new-cat-content">
                <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                        Name
                    </div>
                    <div class="add-new-cat-content-input">
                       <input type="text" name="currency_name" value="<?= $name ?>">
                    </div>
                </div>
                <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                       Symbol
                    </div>
                    <div class="add-new-cat-content-input">
                        <input type="text" name="currency_symbol" value="<?= $symbol ?>" >
                    </div>
                </div>
                <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                       Code
                    </div>
                    <div class="add-new-cat-content-input">
                        <input type="text" name="currency_code" value="<?= $code ?>">
                    </div>
                </div>
                <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                       Exchange Rate
                    </div>
                    <div class="add-new-cat-content-input">
                        <input type="text" name="currency_rate" value="<?= $rate ?>">
                          <input type="hidden" name="action" value="<?= $update ?>">
                          <input type="hidden" name="id" value="<?= $id ?>">
                    </div>
                </div>
                <div class="add-new-cat-content-btn">
                    <input type="button" value="Save" onclick="submitForm()">
                </div>
            </div>
        </form>
    </div>
</div>
</div>
<script>
  function submitForm(form){
    
    var url = $('#newCurrency').attr("action");
    
    var formData = $('#newCurrency').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 0){
      alert('New Currency is added');
    }else{
      alert('New Currency is not added');
    }
    });
}
</script> 