
<div class="wrapper">
		<div class="row">
			<div class="add-product">

            <h1 data-aos="fade-right">Add New Product <a href="?page=viewproduct_dashboard">View Product</a></h1>
                <form class="addproduct-form" action="<?php echo $controller; ?>" method="post" enctype="multipart/form-data" >
    <table class="product-table" width="100%" data-aos="fade-up-right">
        <tr class="product-table-row">
            <td class="product-table-data">
                <div class="add-image">
                    <input type="file" name="files[]" onchange="readURL(this);"  multiple/>
                    <span class="img-text-1">+</span>
                    <span class="img-text-2">Uplaod Images</span>
                </div>
                <div class="add-image-box">
                    <?php 
                        if(!empty($product_img)){
                            $img = $product_img;
                        }else{

                            $img = '../app/view/img/add-product.png';
                        }
                    ?>
                <img id="blah" src="<?= $img ?>" alt="your image" style="width:130px;height:130px;" />
                </div>
                
                   
            </td>
        </tr>
        
    </table>
    <div class="frmDronpDown add-product-dropdown" data-aos="flip-up">
        <div class="row" data-aos="fade-right">
            <label>Category:</label><br /> <select name="category"
                id="country-list" 
                onChange="getsecondlevel(this.value);">
                <option value disabled selected>Select Category</option>
<?php
foreach ($getcategories as $category) {

if($category["name"] == $product_cat){
$select = 'SELECTED';
}else{
    $select = null;
}

    ?>
<option value="<?php echo $category["category_id"]; ?>" <?= $select ?>  ><?php echo $category["name"]; ?></option>
<?php

}
?>
</select>
        </div>
        <div class="row" data-aos="fade-up">
            <label>Sub Category:</label><br /> <select name="secondlevel"
                id="state-list" 
                onChange="getthirdlevel(this.value);">
                <option value ="">Select Second Level</option>

          
            </select>
        </div>
        <div class="row" data-aos="fade-left">
            <label>2nd Sub Category:</label><br /> <select name="thirdlevel"
                id="city-list" >
                <option >Select Third Level</option>
            </select>
        </div>
    </div>
                <div class="add-details" data-aos="zoom-in">
                    <div class="add-product-content-main">
                        <div class="add-d-coulum">
                        <label data-aos="fade-right">Name</label>
                        <input name="name" type="text" value="<?= $product_name ?>" data-aos="fade-right"/>
                        </div>
                        <div class="add-d-coulum">
                        <label data-aos="fade-right">Quantity</label>
                        <input class="count" name="quantity" type="number" value="<?= $product_qty ?>" placeholder="1"  data-aos="fade-right"/>
                        </div>
                        <div class="add-d-coulum">
                        <label data-aos="fade-right">Weight, Kg</label>
                        <input name="weight" type="text" value="<?= $product_weight?>" data-aos="fade-right"/>
                        </div>
                        <div class="add-d-coulum">
                        <label data-aos="fade-right">Description</label>
                        <input class="dis" name="description" type="text" value="<?= $product_desc ?>" data-aos="fade-right" />
                        </div>
                    </div>
                    <div class="add-product-content-main">
                        <div class="add-product-main-content">
                                <div class="add-d-coulum">
                                    <label data-aos="fade-right">Purchase Price</label>
                                    <input class="count" name="purchase_price" type="number" value="<?= $product_purchase?>"  data-aos="fade-right"/><br>
                                </div>
                                <div class="add-d-coulum">
                                    <label data-aos="fade-right">Sell Price :</label>
                                    <input class="count" name="price" type="number" value="<?= $product_sell?>"  data-aos="fade-right"/><br>
                            </div>
                        </div>
                        <div class="add-product-main-content">
                            <div class="add-d-coulum">
                                <label data-aos="fade-right">Is Featured :</label>
                                <input name="featured" type="checkbox" value="<?= $product_feature?>" data-aos="fade-right" <?= $product_feature ?>/>
                            </div>
                            <div class="add-d-coulum">
                                <label data-aos="fade-right">Publish :</label>
                                <input name="publish" type="checkbox" value="<?= $product_publish?>" data-aos="fade-right" <?= $product_publish ?>/>
                            </div>
                        </div>
                    </div>
                    <div class="add-product-content-main">
                        <div class="add-btn" data-aos="fade-right">
                        <input  type="submit" value="Add Product" name="add"  data-aos="fade-right"/>
                        <input name="action" type="hidden" value="<?= $update ?>" data-aos="fade-right"/>
                        <input name="product_id" type="hidden" value="<?= $product_id?>" data-aos="fade-right"/>
                        </div>
                    </div>
                   
                    <div class="add-msg">
                        <div class="warning">
                            <strong>NOTE: Incorrect input field</strong>
                        </div>
                        <div class="success">
                            <strong>Success</strong>
                        </div>
                        <div class="fail">
                            <strong>Fail</strong>
                        </div>
                    </div>
                </div>   
            </form>
        </div>
   </div>
</div>
<script>
  function submitForm(form){
    
    var url = $('#form').attr("action");
    
    var formData = $('#form').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 0){
      alert('Product is added');
    }else{
      alert('Product is not added');
    }
    });
}
</script> 
