<div class="wrapper">
    <div class="row">
        <div class="order-dashboard-main">
        <h1 data-aos="fade-right"data-aos-duration="1500">Add New Language</h1>
    </div>
    <div class="add-new-category" data-aos="zoom-in-up" data-aos-duration="600">
        <form action="<?= $controller; ?>" id="newLang">
            <div class="add-new-cat-head">
            Language Information
            </div>
            <div class="add-new-cat-content">
                <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                        Name
                    </div>
                    <div class="add-new-cat-content-input">
                       <input type="text" name="lang_name">
                    </div>
                </div>
                <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                       Code
                    </div>
                    <div class="add-new-cat-content-input">
                        <select name="lang_code" id="">
                            <option value="1">en</option>
                            <option value="2">ud</option>
                            <option value="2">ru</option>
                            <option value="2">cn</option>
                        </select>
                    </div>
                </div>
                <div class="add-new-cat-content-btn">
                    <input type="button" value="Save" onclick="submitForm()">
                </div>
            </div>
        </form>
    </div>
</div>
</div>
<script>
  function submitForm(form){
    
    var url = $('#newLang').attr("action");
    
    var formData = $('#newLang').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 0){
      alert('New Language is added');
    }else{
      alert('New Language is not added');
    }
    });
}
</script> 