<div class="wrapper">
    <div class="row">
        <div class="order-dashboard-main">
        <h1 data-aos="fade-right"data-aos-duration="1500"><?php 
echo getlang('','Coupons',getlangcookie()); 
?>  </h1>
    </div>
    <div class="add-new-category" data-aos="zoom-in-up" data-aos-duration="600">
        <form action="<?= $controller; ?>" id="newCoupon">
            <div class="add-new-cat-head">
            <?php 
echo getlang('','Coupon Information Adding',getlangcookie()); 
?>
            </div>
            <div class="add-new-cat-content">
                <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                        <?php 
echo getlang('','Coupon Name',getlangcookie()); 
?>
                    </div>
                    <div class="add-new-cat-content-input">
                        <input type="text" name="coupon_name" value="<?= $coupon_name ?>" required>
                    </div>
                </div>
                <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                        <?php 
echo getlang('','Coupon code',getlangcookie()); 
?>
                    </div>
                    <div class="add-new-cat-content-input">
                        <input type="text" name="coupon_code" value="<?= $coupon_code ?>" required>
                    </div>
                </div>
                 <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                        <?php 
echo getlang('','Minimum Shopping',getlangcookie()); 
?>
                    </div>
                    <div class="add-new-cat-content-input">
                        <input type="text" name="min_shop" value="<?= $coupon_min ?>" required>
                    </div>
                </div>
                <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                        <?php 
echo getlang('','Discount',getlangcookie()); 
?>
                    </div>
                    <div class="add-new-cat-content-input">
                        <input type="text" name="discount" value="<?= $coupon_dis ?>">
                        <select name="discount_select" id="" required>
                            <option value="1">Amount</option>
                            <option value="2">Percent</option>
                        </select>
                    </div>
                </div>
              
               
                <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                        <?php 
echo getlang('','From Date',getlangcookie()); 
?>
                    </div>
                    <div class="add-new-cat-content-input">
                        <input type="date" name="coupon_date_start" value="<?= $coupon_from ?>" required>
                    </div>
                </div>
                 <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                        <?php 
echo getlang('','To Date',getlangcookie()); 
?>
                    </div>
                    <div class="add-new-cat-content-input">
                        <input type="date" name="coupon_date_end" value="<?= $coupon_to ?>" required>
                         <input type="hidden" name="coupon_id" value="<?= $coupon_id ?>">
                    </div>
                </div>
                <div class="add-new-cat-content-btn">
                    <input type="button" value="<?php 
echo getlang('','Save',getlangcookie()); 
?>" onclick="submitForm()">
                </div>
            </div>
        </form>
    </div>
</div>
</div>
<script>
  function submitForm(form){
    var validInput = $('input').val();
    var url = $('#newCoupon').attr("action");
    var formData = $('#newCoupon').serializeArray();
    if(validInput == ""){
        alert('Please Fill the required field')
    }else{
    $.post(url, formData).done(function (data) {
        if(data == 0){
      alert('New Coupon is added');
    }else{
      alert('New Coupon is not added');
    }
    });
}
}
</script> 