<div class="wrapper">
    <div class="row">
        <div class="order-dashboard-main">
        <h1 data-aos="fade-right"data-aos-duration="1500">Add New Category</h1>
    </div>
    <div class="add-new-category" data-aos="zoom-in-up" data-aos-duration="600">
        <form action="">
            <div class="add-new-cat-head">
                Category Information
            </div>
            <div class="add-new-cat-content">
                <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                        Name
                    </div>
                    <div class="add-new-cat-content-input">
                        <input type="text">
                    </div>
                </div>
                <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                        Type
                    </div>
                    <div class="add-new-cat-content-input">
                        <select name="" id="">
                            <option value="1">Physical</option>
                            <option value="2">Digital</option>
                        </select>
                    </div>
                </div>
                 <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                        Meta Title
                    </div>
                    <div class="add-new-cat-content-input">
                        <input type="text">
                    </div>
                </div>
                <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                        Meta Description
                    </div>
                    <div class="add-new-cat-content-input">
                        <input type="text">
                    </div>
                </div>
                <div class="add-new-cat-content-btn">
                    <input type="button" value="Save">
                </div>
            </div>
        </form>
    </div>
</div>
</div>