
<div class="wrapper">
		<div class="row">
			<div class="add-product">

            <h1 data-aos="fade-right">Add New Product <a href="?page=viewproduct_dashboard">View Product</a></h1>
                <form class="addproduct-form" action="<?php echo $controller; ?>" method="post" enctype="multipart/form-data" >
    <table class="product-table" width="100%" data-aos="fade-up-right">
        <tr class="product-table-row">
            <td class="product-table-data">
                <div class="add-image">
                    <input type="file" name="files" onchange="readURL(this);"  multiple/>
                    <span>Upload .jpeg, .jpg, .png, .gif </span>
                </div>
                <div class="add-image-box">
                <img id="blah" src="http://placehold.it/150" alt="your image" style="width:150px;height:200px" />
                </div>
                
                    
            </td>
        </tr>
        
    </table>
    <div class="frmDronpDown add-product-dropdown" data-aos="flip-up">
        <div class="row" data-aos="fade-right">
            <label>Category:</label><br /> <select name="category"
                id="country-list" 
                onChange="getsecondlevel(this.value);">
                <option value disabled selected>Select Category</option>
<?php
foreach ($getcategories as $category) {
    ?>
<option value="<?php echo $category["category_id"]; ?>" ><?php echo $category["name"]; ?></option>
<?php
}
?>
</select>
        </div>
        <div class="row" data-aos="fade-up">
            <label>Second Level Category:</label><br /> <select name="secondlevel"
                id="state-list" 
                onChange="getthirdlevel(this.value);">
                <option value ="">Select Second Level</option>
            
          
            </select>
        </div>
        <div class="row" data-aos="fade-left">
            <label>Third Level Category:</label><br /> <select name="thirdlevel"
                id="city-list" >
                <option >Select Third Level</option>
            </select>
        </div>
    </div>
                <div class="add-details" data-aos="zoom-in">
                    <div class="add-d-coulum">
                    <label data-aos="fade-right">Name :</label>
                    <input name="name" type="text" value="" data-aos="fade-right"/>
                    </div>
                    <div class="add-d-coulum">
                    <label data-aos="fade-right">Description :</label>
                    <input class="dis" name="description" type="text" value="" data-aos="fade-right" />
                    </div>
                    <div class="add-d-coulum">
                    <label data-aos="fade-right">Quantity :</label>
                    <input class="count" name="quantity" type="number" value="1" placeholder="1"  data-aos="fade-right"/>
                    </div>
                    <div class="add-d-coulum">
                    <label data-aos="fade-right">Purchase Price :</label>
                    <input class="count" name="price" type="number" value=""  data-aos="fade-right"/><br>
                    </div>
                    <div class="add-d-coulum">
                    <label data-aos="fade-right">Sell Price :</label>
                    <input class="count" name="price" type="number" value=""  data-aos="fade-right"/><br>
                    </div>
                    <div class="add-btn" data-aos="fade-right">
                    <input  type="submit" value="Add Product" name="add"  data-aos="fade-right"/>
                    </div>
                    <div class="add-msg">
                        <div class="warning">
                            <strong>NOTE: Incorrect input field</strong>
                        </div>
                        <div class="success">
                            <strong>Success</strong>
                        </div>
                        <div class="fail">
                            <strong>Fail</strong>
                        </div>
                    </div>
                </div>   
            </form>
        </div>
   </div>
</div>
<script>
  function submitForm(form){
    
    var url = $('#form').attr("action");
    
    var formData = $('#form').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 0){
      alert('Product is added');
    }else{
      alert('Product is not added');
    }
    });
}
</script> 
