<div class="wrapper">
    <div class="row">
        <div class="order-dashboard-main">
        <h1 data-aos="fade-right"data-aos-duration="1500">Add New Deal</h1>
    </div>
    <div class="add-new-deal" data-aos="zoom-in-up" data-aos-duration="600">
        <form action="<?= $controller; ?>" method="post" enctype="multipart/form-data" id="form"> 
            <div class="add-new-deal-content">
                <div class="add-new-deal-content1">
                    <div class="new-content">
                        <div class="add-new-deal-content-head">
                            Title
                        </div>
                        <div class="add-new-deal-content-input">
                            <input type="text" name="title">
                        </div>
                    </div>
                    <div class="new-content">
                        <div class="add-new-deal-content-head">
                            Product Image(400x400) .PNG Only
                        </div>
                        <div class="add-new-deal-content-input">
                            <input type="file" name="banner">
                        </div>
                    </div>
                </div>
                <div class="add-new-deal-content1">
                    <div class="add-new-deal-content-head">
                        Short Discribtion
                    </div>
                    <div class="add-new-deal-content-input">
                        <textarea name="discribtion" id="" cols="30" rows="10"></textarea>
                    </div>
                </div>
                <div class="add-new-deal-content-btn">
                    <input type="button" value="Save" onclick="submitForm()">
                </div>
            </div>
        </form>
    </div>
</div>
</div>
<script>
  function submitForm(form){
    
    var url = $('#form').attr("action");
    
    var formData = $('#form').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 0){
      alert('New Deal is added');
    }else{
      alert('New Deal is not added');
    }
    });
}
</script> 