<div class="wrapper">
    <div class="row">
        <div class="order-dashboard-main">
        <h1 data-aos="fade-right"data-aos-duration="1500">Add New Deal</h1>
    </div>
    <div class="add-new-category" data-aos="zoom-in-up" data-aos-duration="600">
        <form action="">
            <div class="add-new-cat-head">
                Flash Deal Information
            </div>
            <div class="add-new-cat-content">
                <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                        Title
                    </div>
                    <div class="add-new-cat-content-input">
                        <input type="text">
                    </div>
                </div>
                <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                        Banner(1920x500)
                    </div>
                    <div class="add-new-cat-content-input">
                        <input type="file">
                    </div>
                </div>
                 <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                        Start Date
                    </div>
                    <div class="add-new-cat-content-input">
                        <input type="date">
                    </div>
                </div>
                <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                        End Date
                    </div>
                    <div class="add-new-cat-content-input">
                        <input type="date">
                    </div>
                </div>
                <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                        Page link
                    </div>
                    <div class="add-new-cat-content-input">
                        <input type="text">
                    </div>
                </div>
                <div class="add-new-cat-content-btn">
                    <input type="button" value="Save">
                </div>
            </div>
        </form>
    </div>
</div>
</div>