<div class="wrapper">
    <div class="row">
        <div class="order-dashboard-main">
        <h1 data-aos="fade-right"data-aos-duration="1500">Add New Coupon</h1>
    </div>
    <div class="add-new-category" data-aos="zoom-in-up" data-aos-duration="600">
        <form action="">
            <div class="add-new-cat-head">
            Coupon Information Adding
            </div>
            <div class="add-new-cat-content">
                <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                        Coupon Type
                    </div>
                    <div class="add-new-cat-content-input">
                        <select name="" id="">
                            <option value="1">for Product</option>
                            <option value="2">for Total Order</option>
                        </select>
                    </div>
                </div>
                <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                        Coupon code
                    </div>
                    <div class="add-new-cat-content-input">
                        <input type="text">
                    </div>
                </div>
                 <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                        Minimum Shopping
                    </div>
                    <div class="add-new-cat-content-input">
                        <input type="text">
                    </div>
                </div>
                <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                        Discount
                    </div>
                    <div class="add-new-cat-content-input">
                        <input type="text">
                        <select name="" id="">
                            <option value="1">Amount</option>
                            <option value="2">Percent</option>
                        </select>
                    </div>
                </div>
                <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                        Products
                    </div>
                    <div class="add-new-cat-content-input">
                        <select name="" id="">
                            <option value="1">1</option>
                            <option value="2">2</option>
                        </select>
                    </div>
                </div>
                <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                        Maximum Discount Amount
                    </div>
                    <div class="add-new-cat-content-input">
                        <input type="text">
                    </div>
                </div>
                <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                        Date
                    </div>
                    <div class="add-new-cat-content-input">
                        <input type="date">
                    </div>
                </div>
                <div class="add-new-cat-content-btn">
                    <input type="button" value="Save">
                </div>
            </div>
        </form>
    </div>
</div>
</div>