<div class="wrapper">
    <div class="row">
        <div class="order-dashboard-main">
        <h1 data-aos="fade-right"data-aos-duration="1500">Add New Staff</h1>
    </div>
    <div class="add-new-category" data-aos="zoom-in-up" data-aos-duration="600">
        <form action="<?= $controller; ?>" id="newStaff">
            <div class="add-new-cat-head">
            Staff Information
            </div>
            <div class="add-new-cat-content">
                <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                        Name
                    </div>
                    <div class="add-new-cat-content-input">
                       <input type="text" name="staff_name" value="<?= $name ?>" <?= $update ?> required>
                    </div>
                </div>
                <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                        E-mail
                    </div>
                    <div class="add-new-cat-content-input">
                        <input type="E-mail" name="staff_email" value="<?= $email ?>" <?= $update ?> required>
                    </div>
                </div>
                 <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                        Phone
                    </div>
                    <div class="add-new-cat-content-input">
                        <input type="number" name="staff_phone" value="<?= $phone ?>" <?= $update ?> required>
                    </div>
                </div>
                  <div class="add-new-cat-content1">
                    <div class="add-new-cat-content-head">
                        Role
                    </div>
                    <div class="add-new-cat-content-input">
                        <select name="staff_role" id="">
                           <?php
                            foreach ($data as $key => $value) {
                                if($value['title'] != 'Admin' && $value['title'] != 'Branch' && $value['title'] != 'Vendor' &&  $value['title'] != 'User'){
                                if($type == $value['title']){
                                        $selected = 'SELECTED';
                                }else{
                                    $selected = null;
                                }
                                ?>
                                <option value="<?= $value['id'] ?>" <?= $selected ?> ><?= $value['title']?></option>
                                <?php
                          }  }

                           ?>
                        </select>
                    </div>
                </div>
                <div class="add-new-cat-content-btn">
                    <input type="button" value="Save" onclick="submitForm()">
                </div>
            </div>
        </form>
    </div>
</div>
</div>
<script>
  function submitForm(form){
    
    var url = $('#newStaff').attr("action");
    
    var formData = $('#newStaff').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 0){
      alert('New Staff is added');
    }else{
      alert('New Staff is not added');
    }
    });
}
</script> 