<div class="wrapper">
    <div class="supplier-content">
        <div class="sup-content-info">
            <div class="sup-heading">
                Supplier info
            </div>
            <form action="" class="content-form">
                <div class="content-form-1">
                    <div class="content-form-heading"><i class="fa fa-id-badge" aria-hidden="true"></i> Name.</div>
                    <div class="content-form-input">
                        <input type="text">
                    </div>
                </div>
                <div class="content-form-2">
                    <div class="content-form-heading"><i class="fa fa-envelope-o" aria-hidden="true"></i> E-mail.</div>
                    <div class="content-form-input">
                        <input type="email">
                    </div>
                </div>
                <div class="content-form-3">
                    <div class="content-form-heading"><i class="fa fa-phone" aria-hidden="true"></i> Phone.</div>
                    <div class="content-form-input">
                        <input type="number">
                    </div>
                </div>
                <div class="content-form-4">
                    <div class="content-form-heading"><i class="fa fa-map-marker" aria-hidden="true"></i> Address.</div>
                    <div class="content-form-input">
                        <textarea name="" id="" cols="30" rows="10"></textarea>
                    </div>
                </div>
                <div class="content-form-5">
                    <div class="content-form-heading"><i class="fa fa-id-card-o" aria-hidden="true"></i> Detail Of supplier.</div>
                    <div class="content-form-input">
                        <textarea name="" id="" cols="30" rows="10"></textarea>
                    </div>
                </div>
                <div class="content-form-6">
                    <div class="content-form-heading"><i class="fa fa-calendar" aria-hidden="true"></i> Product Supplied.</div>
                    <div class="content-form-input">
                        <input type="text">
                    </div>
                </div>
                <div class="content-form-7">
                    <input type="button" value="Add">
                </div>
            </form>
        </div>
    </div>
</div>