<div class="wrapper">
    <div class="row">
        <div class="order-dashboard-main">
        <h1 data-aos="fade-right"data-aos-duration="1500">All Notification</h1>
    </div>

    <div class="noti-table">
        <table class="noti-table-content">
        <caption>Notification Info Table</caption>
            <tr>
                <th>Notification Title <i class="fa fa-book" aria-hidden="true"></i></th>
                <th>Notification Message <i class="fa fa-comment" aria-hidden="true"></i></th>
                <th>Option <i class="fa fa-cogs" aria-hidden="true"></i></th>
            </tr>
            <tr>
                <td>Purchase</td>
                <td>Congratulations! there is new order from zubairayuub</td>
                <td>
                    <a href="#">View <i class="fa fa-eye" aria-hidden="true"></i></a>
                </td>
            </tr>
        </table>
    </div>
    
</div>
</div>
