<div class="wrapper">
    <div class="row">
        <div class="allstaff-dashboard-main">
        <h1 data-aos="fade-right"data-aos-duration="1500">All Staff </h1>
        <form action="" data-aos="fade-left"data-aos-duration="1500">
            <a href="?page=addnewstaff_dashboard">
               <input type="button" value="Add New Staff">
            </a> 
        </form>
    </div>
    <div class="staff-dashboard-main" data-aos="zoom-in-up" data-aos-duration="600">
        <form action="">
            <table>
                <tr>
                    <th>Serial No.</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Role</th>
                    <th>Options</th>
                </tr>
                <tr>
                    <td>1</td>
                    <td>Muzzamil Qureshi</td>
                    <td>bunnix007@gmail.com</td>
                    <td>+92-00000000</td>
                    <td>Manager</td>
                    <td class="option">
                        <a href="?page=addnewstaff_dashboard">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit
                        </a>
                        <a href="#">
                            <i class="fa fa-trash" aria-hidden="true"></i> Remove
                        </a>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>
</div>