<div class="wrapper">
    <div class="row">
        <div class="allstaff-dashboard-main">
        <h1>All Staff </h1>
        <form action="">
            <input type="button" value="Add New Staff">
        </form>
    </div>
    <div class="staff-dashboard-main">
        <form action="">
            <table>
                <tr>
                    <th>Serial No.</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Role</th>
                    <th>Options</th>
                </tr>
                <tr>
                    <td>1</td>
                    <td>Muzzamil Qureshi</td>
                    <td>bunnix007@gmail.com</td>
                    <td>+92-00000000</td>
                    <td>Manager</td>
                    <td>
                        <a href="#">1</a>
                        <a href="#">2</a>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>
</div>