<div class="wrapper">
    <div class="row">
        <div class="allstaff-dashboard-main">
        <h1 data-aos="fade-right"data-aos-duration="1500">All Staff </h1>
        <form action="" data-aos="fade-left" data-aos-duration="1500">
            <a href="?page=addnewstaff_dashboard">
               <input type="button" value="Add New Staff">
            </a> 
        </form>
    </div>
    <div class="staff-dashboard-main" data-aos="zoom-in-up" data-aos-duration="600">
        <form action="">
            <table>
                <tr>
                    <th>Serial No.</th>
                  
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Role</th>
                    <th>Options</th>
                </tr>

                <?php 
                $count = 1;
                foreach ($data as $key => $value) {
                   $user_data  = getuserinfo($value['user']);
                   $user_type  = getusertypes($value['type']);

                    ?>
                <tr>
                    <td><?= $count ?></td>
                 
                    <td><?= $user_data[0]['email_id'] ?></td>
                    <td><?= $user_data[0]['contact_no'] ?></td>
                    <td><?= $user_type[0]['title'] ?></td>
                    <td class="option">
                        <a href="?page=addnewstaff_dashboard&name=<?= $user_data[0]['first_name'] ?>&email=<?= $user_data[0]['email_id'] ?>&phone=<?= $user_data[0]['contact_no'] ?>&type=<?= $user_type[0]['title'] ?>">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit
                        </a>
                        <a href="#">
                            <i class="fa fa-trash" aria-hidden="true"></i> Remove
                        </a>
                    </td>
                </tr>

                    <?php
                $count ++; 
            } ?>
             
            </table>
        </form>
    </div>
</div>
</div>