<div class="wrapper">
		<div class="row">
			<div class="dashboard-theme-main">
            <h1 data-aos="fade-right" data-aos-duration="1500">Appearance</h1>
        </div>
 <div class="theme-selection">

        <?php
foreach ($data as $key => $value) {
$datatheme = getthemebybranchid($branch_id);
$theme_id = $datatheme[0]['theme_id'];

if($theme_id == $value['id']){
$text = 'Activated';
$class_theme = '';

}else{
    $class_theme = '';
    $text = 'Activate';
}

    ?>

             <div class="theme-seclection-box" data-aos="fade-right" data-aos-duration="1000">
                <div class="theme-heading"><?= $value['title'] ?></div>
                <div class="theme-dis"><?= $value['description'] ?></div>
                <div class="theme-type">Website Type:<span><?= $value['type'] ?></span></div>
                <div class="theme-btn">
                    <input type="button" class="<?= $class_theme ?> " value="<?= $text?>">    
                </div>
            </div>



    <?php
}

        ?>
       
          
        </div>
</div>
</div>
