<div class="wrapper">
		<div class="row">
			<div class="col-3 col-m-6 col-sm-6">
            <h1>Send Bluk SMS</h1>
        </div>
        <div class="bluk-sms-main">
            <form>
                <div class="bluk-sms-form1">
                    <label>Mobile Users</label>
                    <select name="" id="">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                    </select>
                </div>
                <div class="bluk-sms-form2">
                    <label>SMS Subject</label>
                    <input type="text">
                </div>
                <div class="bluk-sms-form2">
                    <label>SMS Content</label>
                    <textarea name="" id="" cols="30" rows="10"></textarea>
                </div>
                <div class="bluk-sms-btn">
                    <input type="button">
                </div>
            </form>
        </div>
</div>
</div>