<div class="wrapper">
		<div class="row">
			<h1 data-aos="fade-right" data-aos-duration="1500">Category</h1>
			<div class="category-dashboard-main" data-aos="fade-left" data-aos-duration="900" >
				<form action="<?php echo $controller ?>" method="post" id="form">
				<div class="cat-dashboard-1">
						<div class="cat-dashboard-name">
							<label>Category name :</label>
							<input name="category" value="" type="text" require>
						</div>
					<!-- 	<div class="cat-dashboard-id">
							<label>Category ID :</label>
							<input name="categoryid" value="" type="text">
						</div>
						<div class="cat-dashboard-2nd">
							<label>Category 2nd Level :</label>
							<input name="subcategory" value="" type="text">
						</div> -->
					</div>
					<div class="cat-dashboard-btn">
						<input type="button" name="addbtn" value="Add Category" onclick="submitForm()" >
					</div>
				</form>
			</div>
            <div class="cat-dashboard-table"  data-aos="flip-right" data-aos-duration="900">
					  <fieldset>
					  <table class="table table-bordered" id="clientstable">
						<thead class="bg-info">
							<th>Category ID</th>
							<th>Category</th>
                            <th>2nd Level Category</th>
							<th></th>
							<th></th>
                        </thead>
					   <tbody>
						 <?php
								
									if (!empty($getcategory)){
								foreach($getcategory as $categorylist){
									
                           ?>	
								<tr>
								<td><?php echo $categorylist["category_id"]; ?></td>
								<td><?php echo $categorylist["name"]; ?></td>
								<td><a href="?page=subcategorytwo_dashboard&id=<?php echo $categorylist["category_id"]; ?>" >Add</a></td>								
                                <td><a href="?page=editcategory_dashboard&id=<?php echo $categorylist["category_id"]; ?>&name=<?php echo $categorylist["name"]?>">Edit</a></td>
								<td><a href="<?php echo $controller  ?>?id=<?php echo $categorylist["category_id"]; ?>" onclick="return confirm('Are you sure?')">Delete</a></td>
								
							   </tr>
								<?php }
									} else {
										echo "No Record Found";
									}
								
						   ?>
					   </tbody>	
							
					</table>
					  </fieldset>
            </div>
            
</div>
</div>


<script>
	function submitForm(form){
		
    var url = $('#form').attr("action");
		
    var formData = $('#form').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
			        alert('category added');
			        location.reload(); 
		}else{
			alert('category not added');
		}
    });
}
</script>
