<div class="wrapper">
    <div class="row">
        <div class="chat-main">
        <h1 data-aos="fade-right"data-aos-duration="1500">Chat (Support Desk)</h1>
    </div>
    <div class="chat-dashboard-main" data-aos="zoom-in-up" data-aos-duration="600">
        <form action="">
            <table>
                <tr>
                    <th>Serial No.</th>
                    
                    <th>Sender</th>
                   
                    <th>Options</th>
                </tr>
                <?php
                $count  = 1; 
                if(count($data) > 0){
foreach ($data as $key => $value) {
    $userdata = getuserinfo($value['user_id'],'');
    if(empty($userdata[0]['first_name'])){
$username = 'Guest';
    }else{
        $username = $userdata[0]['first_name'];
    }

                ?>
                <tr>
                    <td><?= $count ;?></td>
                   
                    <td><?= $username ?></td>
                   
                    <td class="option">
                        <a href="?page=viewchat_dashboard&user_id=<?= $value['user_id'] ?>">
                        <i class="fa fa-eye" aria-hidden="true"></i> View
                        </a>
                      
                  </td>
                </tr>
                <?php
                $count ++;
            }
        }
            ?>
              </table>
        </form>
    </div>
</div>
</div>