<div class="wrapper">
    <div class="row">
        <div class="col-3 col-m-6 col-sm-6">
        <h1>Chat (Support Desk)</h1>
    </div>
    <div class="chat-dashboard-main">
        <form action="">
            <table>
                <tr>
                    <th>Serial No.</th>
                    <th>Date</th>
                    <th>Title</th>
                    <th>Sender</th>
                    <th>Receiver</th>
                    <th>Options</th>
                </tr>
                <tr>
                    <td>1</td>
                    <td>01/01/2021</td>
                    <td>Nex</td>
                    <td>Muzzamil</td>
                    <td>Admin</td>
                    <td>
                        <a href="#">1</a>
                        <a href="#">2</a>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>
</div>