<div class="wrapper">
    <div class="row">
        <div class="chat-main">
        <h1 data-aos="fade-right"data-aos-duration="1500">Chat (Support Desk)</h1>
    </div>
    <div class="chat-dashboard-main" data-aos="zoom-in-up" data-aos-duration="600">
        <form action="">
            <table>
                <tr>
                    <th>Serial No.</th>
                    <th>Date</th>
                    <th>Title</th>
                    <th>Sender</th>
                    <th>Receiver</th>
                    <th>Options</th>
                </tr>
                <?php
                $count  = 1; 
foreach ($data as $key => $value) {
    # code...

                ?>
                <tr>
                    <td><?= $count ;?></td>
                    <td>23/12/2020</td>
                    <td>Nex</td>
                    <td>John Adams</td>
                    <td>Admin</td>
                    <td class="option">
                        <a href="?page=viewchat_dashboard">
                        <i class="fa fa-eye" aria-hidden="true"></i> view
                        </a>
                        <a href="#">
                              <i class="fa fa-trash" aria-hidden="true"></i> Remove
                        </a>
                  </td>
                </tr>
                <?php
                $count ++;
            }
            ?>
              </table>
        </form>
    </div>
</div>
</div>