<div class="wrapper">
    <div class="row">
        <div class="coupons-dashboard-main">
        <h1 data-aos="fade-right"data-aos-duration="1500"><?php 
echo getlang('','Coupons',getlangcookie()); 
?>  </h1>
        <form action=""data-aos="fade-left"data-aos-duration="1500">
           <a href="?page=addnewcoupon_dashboard">
               <input type="button" value="<?php 
echo getlang('','Add New Coupon',getlangcookie()); 
?> ">
            </a>
        </form>
    </div>
    <div class="coupons-main" data-aos="fade-up"data-aos-duration="600">
        <form action="">
            <table>
                <tr>
                    <th><?php 
echo getlang('','Serial.No',getlangcookie()); 
?>  </th>

           <th><?php 
echo getlang('','Name',getlangcookie()); 
?>  </th>

                    <th><?php 
echo getlang('','Code',getlangcookie()); 
?>  </th>
                    <th><?php 
echo getlang('','Type',getlangcookie()); 
?>  </th>
                    <th><?php 
echo getlang('','Start Date',getlangcookie()); 
?>  </th>
                    <th><?php 
echo getlang('','End Date',getlangcookie()); 
?>  </th>
                    <th><?php 
echo getlang('','Options',getlangcookie()); 
?>  </th>
                </tr>
                <?php
                $count = 0;
foreach ($data as $key => $value) {
 $count ++;
 if($value['type'] == 1){
$type_coupon = 'Amount';
 }else{
$type_coupon = 'Percantage';
 }
    ?>

                <tr>
                    <td><?= $count ; ?></td>
                    <td><?= $value['name']?></td>
                    <td><?= $value['code']?></td>
                    <td><?= $type_coupon ?></td>
                    <td><?= $value['start_date'] ?></td>
                    <td><?= $value['end_date'] ?></td>
                    <td class="option">
                        <a href="?page=addnewcoupon_dashboard&id=<?= $value['id'] ?>">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i><?php 
echo getlang('','Edit',getlangcookie()); 
?> 
                        </a>
                        <a href="?page=addnewcoupon_dashboard&id=<?= $value['id'] ?>&action=remove">
                            <i class="fa fa-trash" aria-hidden="true"></i><?php 
echo getlang('','Remove',getlangcookie()); 
?> 
                        </a>
                    </td>
                </tr>



    <?php
}

                ?>
            </table>
        </form>
    </div>
</div>
</div>