<div class="wrapper">
    <div class="row">
        <div class="col-3 col-m-6 col-sm-6">
        <h1>coupons</h1>
        <form action="">
            <input type="button" value="Add New Coupon">
        </form>
    </div>
    <div class="coupons-main">
        <form action="">
            <table>
                <tr>
                    <th>Serial.No</th>
                    <th>Code</th>
                    <th>Type</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>Options</th>
                </tr>
                <tr>
                    <td>1</td>
                    <td>0001</td>
                    <td>Cart Base</td>
                    <td>03/01/2021</td>
                    <td>03/01/2021</td>
                    <td>
                        <a href="#">1</a>
                        <a href="#">2</a>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>
</div>