<div class="wrapper">
    <div class="row">
        <div class="coupons-dashboard-main">
        <h1 data-aos="fade-right"data-aos-duration="1500"><?php 
echo getlang('','Coupons',getlangcookie()); 
?>  </h1>
        <form action=""data-aos="fade-left"data-aos-duration="1500">
           <a href="?page=addnewcoupon_dashboard">
               <input type="button" value="<?php 
echo getlang('','Add New Coupon',getlangcookie()); 
?> ">
            </a>
        </form>
    </div>
    <div class="coupons-main" data-aos="fade-up"data-aos-duration="600">
        <form action="">
            <table>
                <tr>
                    <th><?php 
echo getlang('','Serial.No',getlangcookie()); 
?>  </th>
                    <th><?php 
echo getlang('','Code',getlangcookie()); 
?>  </th>
                    <th><?php 
echo getlang('','Type',getlangcookie()); 
?>  </th>
                    <th><?php 
echo getlang('','Start Date',getlangcookie()); 
?>  </th>
                    <th><?php 
echo getlang('','End Date',getlangcookie()); 
?>  </th>
                    <th><?php 
echo getlang('','Options',getlangcookie()); 
?>  </th>
                </tr>
                <tr>
                    <td>1</td>
                    <td>0001</td>
                    <td>Cart Base</td>
                    <td>03/01/2021</td>
                    <td>03/01/2021</td>
                    <td class="option">
                        <a href="?page=addnewcoupon_dashboard">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i><?php 
echo getlang('','Edit',getlangcookie()); 
?> 
                        </a>
                        <a href="#">
                            <i class="fa fa-trash" aria-hidden="true"></i><?php 
echo getlang('','Remove',getlangcookie()); 
?> 
                        </a>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>
</div>