<div class="wrapper">
    <div class="row">
        <div class="currency-dashboard-main">
            <h1 data-aos="fade-right"data-aos-duration="1500">Currency</h1>
        </div>
        <div class="currency-main">
            <div class="sys-currency-dash">
                <form action='<?= $controller; ?>' id="currencyForm"> 
                    <input type="hidden" name="defaultCurrency">
                    <div class="sys-box" data-aos="fade-right"data-aos-duration="900">
                        <div class="sys-box-head">System Default Currency</div>
                        <div class="sys-box-dis">
                            <div class="sys-dis-sub-head">System Default Currency</div>
                            <div class="sys-dis-sub-input">
                                <select name="def_currency" id="">
                                    <?php
foreach ($data as $key => $value) {
    ?>

<option value='<?= $value['id']?>' ><?= $value['name']; ?></option>
    <?php
}
                                    ?>
                                </select>
                                <input type="button" value="SAVE" onclick="submitDefaultForm()">
                            </div>
                        </div>
                    </div>
                </form>
               
            </div>
            <div class="sys-dashboard-btn" data-aos="fade-left"data-aos-duration="700">
                <a href="?page=addnewcurrency_dashboard">
                    <input type="button" value="Add New Currency">
                </a> 
            </div>
            <div class="currency-table" data-aos="zoom-in-up" data-aos-duration="800">
                <div class="table-heading">
                    <input type="text" value="Search">
                </div>
                <form action="<?= $controller; ?>">
                    <table>
                        <tr>
                            <th>Serial.No</th>
                            <th>Currency Name</th>
                            <th>Currency Symbol</th>
                            <th>Currency Code</th>
                            <th>Exchange Rate (1 USD=?)</th>
                       
                            <th>Option</th>
                        </tr>
                        <?php 
                        $count = 0;
foreach ($data as $key => $value) {
    $count ++;
    ?>

                        <tr>
                            <td><?= $count ; ?></td>
                            <td><?= $value['name'] ; ?></td>
                            <td><?= $value['symbol'] ; ?></td>
                            <td><?= $value['code'] ; ?></td>
                            <td><?= $value['rate'] ; ?></td>
                          
                            <td class="option">
                                <a href="?page=addnewcurrency_dashboard&id= <?= $value['id'] ; ?>">
                                    <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit
                                </a>
                                <a href="#">
                                    <i class="fa fa-trash" aria-hidden="true"></i> Remove
                                </a>
                            </td>
                        </tr>

    <?php
}
                        ?>
                    </table>
                </form>
            </div>
        </div>
    </div>
</div>


<script>
  function submitDefaultForm(form){
    
        url = $('#currencyForm').attr("action");
        formData = $('#currencyForm').serializeArray();

        $.post(url, formData).done(function (data) {
        if(data == 1){
            alert('success');
        }else{
            alert('error');
        }
    });
  }
  function submitSymbolForm(form){
    
    url = $('#symbolForm').attr("action");
    formData = $('#symbolForm').serializeArray();

    $.post(url, formData).done(function (data) {
    if(data == 1){
        alert('success');
    }else{
        alert('error');
    }
});
}
  </script>
