<!-- Datatables CSS & JS-->
	
    <link href="../vendors/datatables/css/jquery.dataTables.min.css" rel="stylesheet">
	    <link href="https://cdn.datatables.net/rowreorder/1.2.5/css/rowReorder.dataTables.min.css" rel="stylesheet">
	
	<link rel="stylesheet" href="../vendors/datatables-responsive/dataTables.responsive.css">
  <link rel="stylesheet" href="../vendors/css/vendor.bundle.base.css">
<div class="wrapper">
		<div class="row">
			<div class="customer-list-dashboard-main">
            <h1 data-aos="fade-right" data-aos-duration="1500">Customers List</h1>
                    </div>
            <div class="customer-list-dashboard" data-aos="fade-up" data-aos-duration="900">
            
					  <fieldset>
					  <table class="table table-bordered" id="clientstable">
					
						<thead class="bg-info">
							<th>First Name</th>
							<th>Last Name</th>
                            <th>Purchased Item</th>
							<th></th>
							<th></th>
                        </thead>
                   
					   <tbody>
						 <?php
								foreach($getcustomers as $customerlist){
                           ?>
                        
						 
											
								
								<tr>
								<td><?php echo $customerlist["first_name"]; ?></td>
								<td><?php echo $customerlist["last_name"]; ?></td>
								<td><?php echo $customerlist["name"]; ?></td>								
                               
							   </tr>
								<?php } ?>
					   </tbody>	
							
					</table>
					  </fieldset>
            </div>
            
</div>
</div>
<!-- Datatables enable script / Server side datatable-->
  <script src="../vendors/datatables/js/jquery.dataTables.min.js"></script>
  
    <script src="https://cdn.datatables.net/rowreorder/1.2.5/js/dataTables.rowReorder.min.js"></script>
    <script src="../vendors/datatables-responsive/dataTables.responsive.js"></script>

<script>
	function submitForm(form){
		
    var url = $('#form').attr("action");
		
    var formData = $('#form').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
			        alert('added');
		}else{
			alert('not added');
		}
    });
}
</script>
