<!-- Datatables CSS & JS-->
	
    <link href="../vendors/datatables/css/jquery.dataTables.min.css" rel="stylesheet">
	    <link href="https://cdn.datatables.net/rowreorder/1.2.5/css/rowReorder.dataTables.min.css" rel="stylesheet">
	
	<link rel="stylesheet" href="../vendors/datatables-responsive/dataTables.responsive.css">
  <link rel="stylesheet" href="../vendors/css/vendor.bundle.base.css">
<div class="wrapper">
		<div class="row">
			<div class="customer-list-dashboard-main">
            <h1 data-aos="fade-right" data-aos-duration="1500">Customers List</h1>
                    </div>
            <div class="customer-list-dashboard" data-aos="fade-up" data-aos-duration="900">
            
					  <fieldset>
					  <table class="table table-bordered" id="clientstable">
					
						<thead class="bg-info">
							<th>Serial No.</th>
							<th>Name <i class="fa fa-user" aria-hidden="true"></i></th>
							<th>Email <i class="fa fa-envelope" aria-hidden="true"></i></th>
							<th>Phone <i class="fa fa-mobile" aria-hidden="true"></i></th>
							<th>Brand <i class="fa fa-product-hunt" aria-hidden="true"></i></th>
							<th>Vendor <i class="fa fa-building-o" aria-hidden="true"></i></th>
							<th>Option <i class="fa fa-cogs" aria-hidden="true"></i></th>
                           
                        </thead> 
                   
					   <tbody>
					   <?php

					   if(!empty($data)){

					   	$count = 1;

					   foreach ($data as $key => $value) {
					   	$user_data = getuserinfo($value['user_id'],'');
					    $branch_data = getbranchbybranchid('',$value['branch_id']);
					   	$vendor_data = getvendors('',$value['Vendor_id'],'FALSE');
					   
					   	if(empty($user_data[0]['first_name'])){

					   		$username = 'Guest';

					   	}else{
					   			$username = $user_data[0]['first_name'];
					   	}

					   	if(empty($user_data[0]['contact_no'])){

					   		$contact_no = '00-00-0000';

					   	}else{
					   			$contact_no = $user_data[0]['contact_no'];
					   	}


					   	
					   	
					  ?>

<tr>

	<td><?= $count ?></td>
	<td><?= $username ?></td>
	<td><?= $user_data[0]['email_id'] ?></td>
	<td><?= $contact_no;?></td>
	<!-- <td>Nike</td> -->
	<td><?= $vendor_data[0]['name'] ?></td>
	<td><?= $branch_data[0]['name'] ?></td>
	<td>
		<a href="?page=viewcustomer_dashboard&name=<?= $username?>&email=<?= $user_data[0]['email_id']?>&phone=<?= $contact_no?>&country=<?= $user_data[0]['country']?>&dob=<?= $user_data[0]['dob']?>&address=<?= $user_data[0]['address'].$user_data[0]['address_2']?>">view</a>
		<!-- <a href="?page=viewcustomer_dashboard">Edit</a> -->
	</td>
	

</tr>
					  <?php
					  $count ++;
					   }
}
					   ?> 	
						
					   </tbody>	
							
					</table>
				</fieldset>
            </div>
	<div class="customer-list-btn-section">
		<a href="#">Export List</a>
	</div>
</div>
</div>
<!-- Datatables enable script / Server side datatable-->
  <script src="../vendors/datatables/js/jquery.dataTables.min.js"></script>
  
    <script src="https://cdn.datatables.net/rowreorder/1.2.5/js/dataTables.rowReorder.min.js"></script>
    <script src="../vendors/datatables-responsive/dataTables.responsive.js"></script>

<script>
	function submitForm(form){
		
    var url = $('#form').attr("action");
		
    var formData = $('#form').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
			        alert('added');
		}else{
			alert('not added');
		}
    });
}
</script>
