

<div class="dashboard">

	<!-- main content -->
	<div class="wrapper">
        <div class="dashboard-detail-main">
            
            <div class="dashboard-detail-content-1">
                <?= $first_row ?>
                <?= $second_row ?>
            </div>
            <div class="dashboard-detail-content-2">
                <div class="dashboard-detail-content-upper">
                    <h4><?PHP IF(!empty($userstatus)){ ECHO '<span> Welcome,</span> <br>'. $userstatus; }?></h4>
                </div>
                <div class="dashboard-detail-content-lower">
                    <div class="dashboard-detail-content-lower-content">
                        <div class="dashboard-detail-heading">Quick Navigation Tab</div>
                        <div class="dashboard-detail-heading-main-row">
                            <a href="?page=viewvendor_dashboard" class="dashboard-detail-cards" data-tilt>
                                <div class="icon"><i class="fa fa-user" aria-hidden="true"></i></div>
                                <div class="label">Go to Vendor</div>
                            </a >
                            <a href="?page=viewbranch_dashboard" class="dashboard-detail-cards" data-tilt>
                                <div class="icon"><i class="fa fa-shopping-bag" aria-hidden="true"></i></div>
                                <div class="label">Go to Branches</div>
                            </a >
                        </div>
                        <div class="dashboard-detail-heading-main-row" >
                            <a href="?page=staffpermission_dashboard" class="dashboard-detail-cards"data-tilt>
                                <div class="icon"><i class="fa fa-user-plus" aria-hidden="true"></i></div>
                                <div class="label">Staff Roles</div>
                            </a >
                            <a href="?page=generalsetting_dashboard" class="dashboard-detail-cards" data-tilt>
                                <div class="icon"><i class="fa fa-cogs" aria-hidden="true"></i></div>
                                <div class="label">general Setting</div>
                            </a >
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="div-shap-animation1"></div>
        <div class="div-shap-animation2"></div>
        <div class="div-shap-animation3"></div>
		
		<div class="row">
			<div class="col-8 col-m-12 col-sm-12">
				<div class="card">
					<div class="card-header">
						<h3>
							Recent Orders:
						</h3>
					</div>
					<div class="card-content">
						 <table class="dashboard_table_main">
                <tr class="dashboard_product_table">
                    <th class="dashboard_product_1">Serial.No</th>
                    <th class="dashboard_product_2">Order Code</th>
                    <th class="dashboard_product_3">Customer</th>
                    <th class="dashboard_product_4">Amount</th>
                    <th class="dashboard_product_5">Delivery Status</th>
                    <th class="dashboard_product_6">Payment Status</th>
                    <th class="dashboard_product_7">Option</th>
                </tr>
                
                    <?php  

                        if (!empty($recent_orders)){
                            $count = 1;
                            
                    foreach ($recent_orders as $key => $value) { 
                    	if($count < 5){
                           $orderdata =  getordersdetailsbyid('',$value['id'],$value['branch_id']);
                           if(!empty($orderdata)){
                           $product_data = getproductnamebyid($orderdata[0]['product_id']);
                           $customer_data = getuserinfo($value['user_id'],'');
                           $invoice_datails = getorderamountbyorderid('',$value['id']);
                          $status_datails =  getorderstatusbyorderid('',$value['id']);
                           if($invoice_datails[0]['status'] == 0){
                            $status_payment = 'Unpaid';

                           }else{

                           $status_payment = 'Paid';

                           }


                           if($customer_data[0]['first_name'] == ''){
$customer_name =   'Guest User' ;

                           }else{

                          $customer_name =   $customer_data[0]['first_name'] .' '. $customer_data[0]['last_name'] ;
                           }
                          ?> 
                    <tr class="dashboard_table_data">   
                        <td class="dashboard_table_row_1"><?php echo $count;?></td>
                        <td class="dashboard_table_row_2"><?php echo $value['id'];?></td>
                        <td class="dashboard_table_row_3"><?php echo  $customer_name ;?></td>
                        <td class="dashboard_table_row_4"><?php echo $invoice_datails[0]['amount'];?></td>
                        <td class="dashboard_table_row_5"><?php echo $status_datails[0]['title'];?></td>
                        <td class="dashboard_table_row_6"><?php echo $status_payment; ?></td>
                        <td class="option dashboard_table_row_7">
                            <a href="?page=orderview_dashboard&order_id=<?= $value['id'] ?>&user_id=<?= $value['user_id'] ?>&date=<?= $value['datetime']?>">
                            <i class="fa fa-eye" aria-hidden="true"></i> view
                            </a>
                            <a href="#">
                                <i class="fa fa-trash" aria-hidden="true"></i> Remove
                            </a>
                        </td>
                </tr>
                       
                    <?php  
                    $count ++;
                } }else{
                	   break;
                } } } ?>
                    
               
            </table>
					</div>
				</div>
			</div>
			<div class="col-4 col-m-12 col-sm-12">
				<div class="card">
					<div class="card-header">
						<h3>
							Progress bar
						</h3>
					</div>
					<?= $weekly_sales ;?>
				</div>
            </div>
            <!-- <div class="card">
                <div class="card-header">
                    <h3>
                        Chartjs
                    </h3>
                </div>
                <div class="card-content">
                    <canvas id="myChart"></canvas>
                </div>
            </div> -->
        </div>
	</div>

    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>