

<div class="dashboard">

	<!-- main content -->
	<div class="wrapper">
		<div class="row">
			<div class="col-3 col-m-6 col-sm-6">
				<div class="counter bg-warning">
					<p>
						<i class="fa fa-spinner" aria-hidden="true" style="color:white; font-size:20px;"></i>
					</p>
					<h3>132</h3>
					<p>Order Placed</p>
				</div>
			</div>
			<div class="col-3 col-m-6 col-sm-6">
				<div class="counter bg-success">
					<p>
						<i class="fa fa-check" aria-hidden="true" style="color:white; font-size:20px;"></i>
					</p>
					<h3>156</h3>
					<p>Number of Visitors</p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-8 col-m-12 col-sm-12">
				<div class="card">
					<div class="card-header">
						<h3>
							Placed Order:
						</h3>
						<i class="fa fa-ellipsis-h"></i>
					</div>
					<div class="card-content">
						<table>
							<thead>
								<tr>
									<th>#</th>
									<th>Product Name</th>
									<th>Product Description</th>
									<th>Price</th>
									<th>Quantity Ordered</th>
									<th>Quantity In Stock</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>1</td>
									<td>t-shirt</td>
									<td>Red color</td>
									<td>
                                        $20
									</td>
									<td>2</td>
									<td>20</td>
								</tr>
								<tr>
									<td>2</td>
									<td>jeans</td>
									<td>Gray shadded</td>
									<td>
                                        $35
									</td>
									<td>11</td>
									<td>50</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
			<div class="col-4 col-m-12 col-sm-12">
				<div class="card">
					<div class="card-header">
						<h3>
							Progress bar
						</h3>
						<i class="fa fa-ellipsis-h"></i>
					</div>
					<div class="card-content">
						<div class="progress-wrapper">
							<p>
								Weekly Sales 
								<span class="float-right">321 $</span>
							</p>
						</div>
						<div class="progress-wrapper">
							<p>
								Delivered
								<span class="float-right"> 70%</span>
							</p>
							<div class="progress">
								<div class="bg-primary" style="width:70%"></div>
							</div>
						</div>
						<div class="progress-wrapper">
							<p>
								On the way to Client
								<span class="float-right"> 80%</span>
							</p>
							<div class="progress">
								<div class="bg-primary" style="width:80%"></div>
							</div>
						</div>
						<div class="progress-wrapper">
							<p>
								Returned
								<span class="float-right"> 10%</span>
							</p>
							<div class="progress">
								<div class="bg-primary" style="width:10%"></div>
							</div>
						</div>
						<div class="progress-wrapper">
							<p>
								Pickup in Store
								<span class="float-right"> ( 20 / 18)</span>
							</p>
							<div class="progress">
								<div class="bg-primary" style="width:70%"></div>
							</div>
						</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		
	</div>

	</div>