
<div class="wrapper">
  <div class="row">
    <div class="edit-cat-dashboard-main">
      <h1>Edit Catagory</h1>
    </div>
    <div class="edit-cat-dashboard">
      <label>Category name :</label>
      <form action="<?php echo $controller ?>" method="post" >
      <?php 
        if(isset($_GET['id'])){
          $id = $_GET['id'];
          $name = $_GET['name'];
        }
      ?>
        <input name="categoryid"  type="text" value="<?php echo $id; ?>" hidden>
        <input class="edit_input" name="category"  type="text" value="<?php echo $name; ?>">
        <input class="edit_input-btn" type="submit" name="addbtn" value="Update Category">
      </form>
    </div>          
  </div>
</div>


<script>
	function submitForm(form){
		
    var url = $('#form').attr("action");
		
    var formData = $('#form').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
			        window.location.replace("?page=category_dashboard");
		}else{
			alert('not added');
		}
    });
}
</script>
