<!-- Datatables CSS & JS-->
	
   
<div class="wrapper">
		<div class="row">
			<div class="col-3 col-m-6 col-sm-6">
            <h1>edit Sub Category 2 level</h1>
              <label>Category name :</label>
                <form action="<?php echo $controller ?>" method="post" >
               
                    <?php 
                    
                      $id = $_GET["id"];
                      $name = $_GET["name"];
                      if(isset($_GET["cat_id"])){
                      $cat_id = $_GET["cat_id"];
                    }
                    
                    ?>
                   <input name="cat_id"  type="text" value="<?php echo $cat_id; ?>" hidden>
                    <input name="categoryid"  type="text" value="<?php echo $id; ?>" hidden>
                    <input name="category"  type="text" value="<?php echo $name; ?>">
                <input type="submit" name="addbtn" value="Update Category"  >
        </form>
                    </div>
            
</div>
</div>


<script>
	function submitForm(form){
		
    var url = $('#form').attr("action");
		
    var formData = $('#form').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
			        window.location.replace("?page=subcategorytwo_dashboard");
		}else{
			alert('not added');
		}
    });
}
</script>
