<!-- Datatables CSS & JS-->
	
   
<div class="wrapper">
  <div class="row">
    <div class="edit-cat-2-dashboard-main" data-aos="zoom-out-right" data-aos-duration="1000">
      <h1>edit Sub Category level 2</h1>
    </div>
    <div class="edit-cat-2-dashboard" data-aos="zoom-out-up" data-aos-duration="1000">
      <label>Category name :</label>
      <form action="<?php echo $controller ?>" method="post" >  
          <?php 
            $id = $_GET["id"];
            $name = $_GET["name"];
            if(isset($_GET["cat_id"])){
            $cat_id = $_GET["cat_id"];
          }
          ?>
        <input name="cat_id"  type="text" value="<?php echo $cat_id; ?>" hidden>
        <input name="categoryid"  type="text" value="<?php echo $id; ?>" hidden>
        <input class="edit2text" name="category"  type="text" value="<?php echo $name; ?>">
        <input class="edit2btn" type="submit" name="addbtn" value="Update Category"  >
      </form>
    </div>          
  </div>
</div>


<script>
	function submitForm(form){
		
    var url = $('#form').attr("action");
		
    var formData = $('#form').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
			        window.location.replace("?page=subcategorytwo_dashboard");
		}else{
			alert('not added');
		}
    });
}
</script>
