<div class="wrapper">
		<div class="row">
			<div class="bluk-sms-dashboard">
            <h1 data-aos="fade-right"data-aos-duration="1500"><?php 
echo getlang('','E-mail',getlangcookie()); 
?>  </h1>
        </div>
        <div class="bluk-sms-main" data-aos="zoom-in-up" data-aos-duration="600">
            <form action="<?= $controller; ?>" id="form">
                <div class="bluk-sms-form4">
                    <label ><?php 
echo getlang('','Email To',getlangcookie()); 
?>  </label>
                    <input type="email" name="email" required>
                </div>
                <div class="bluk-sms-form2">
                    <label><?php 
echo getlang('','Title',getlangcookie()); 
?>  </label>
                    <input type="text" name="email_title" required>
                </div>
                <div class="bluk-sms-form3">
                    <label><?php 
echo getlang('','Massage',getlangcookie()); 
?>  </label>
                    <textarea class="tinymce" id="myTextArea" name="email_msg" required></textarea>
                </div>
                <div class="bluk-sms-btn">
                    <input type="button" value="<?php 
echo getlang('','SEND',getlangcookie()); 
?>  " onclick="submitForm()">
                </div>
            </form>
        </div>
</div>
</div>


<script>
  function submitForm(form){
    
    var url = $('#form').attr("action");
    var myContent = tinymce.get("myTextArea").getContent();
      $('#myTextArea').html(myContent);
    
    var formData = $('#form').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
      alert('success');
    }else{
      alert('error');
    }
    });
}
</script>