<div class="wrapper">
		<div class="row">
			<div class="bluk-sms-dashboard">
            <h1 data-aos="fade-right"data-aos-duration="1500">E-mail</h1>
        </div>
        <div class="bluk-sms-main" data-aos="zoom-in-up" data-aos-duration="600">
            <form>
                <div class="bluk-sms-form4">
                    <label >E-mail</label>
                    <input type="email">
                </div>
                <div class="bluk-sms-form2">
                    <label>Title</label>
                    <input type="text">
                </div>
                <div class="bluk-sms-form3">
                    <label>Massage</label>
                    <textarea name="" id="" cols="30" rows="10"></textarea>
                </div>
                <div class="bluk-sms-btn">
                    <input type="button" value="SEND">
                </div>
            </form>
        </div>
</div>
</div>