<div class="wrapper">
    <div class="row">
        <div class="feature-dashboard-main">
            <h1 data-aos="fade-right"data-aos-duration="1500">Feature activation</h1>
        </div>
        <div class="feature-main">
            <div class="feature-hhtps">
                <div class="feature-hhtps-heading" data-aos="fade-left"data-aos-duration="1000">
                    HTTPS Activation
                </div>
                <div class="feature-hhtps-box">
                    <div class="f-box-content" data-aos="fade-right"data-aos-duration="900">
                        <div class="f-box-head">HTTPS Activation</div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                </div>  
            </div>
            <div class="feature-maintenance">
                <div class="feature-maintenance-heading" data-aos="fade-left"data-aos-duration="1000">
                    Maintenance Mode
                </div>
                <div class="feature-maintenance-box">
                    <div class="f-box-content" data-aos="fade-right"data-aos-duration="900">
                        <div class="f-box-head">Maintenance Mode Activation</div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                </div>  
            </div>
            <div class="feature-classified">
                <div class="feature-classified-heading" data-aos="fade-left"data-aos-duration="1000">
                    Classified Product
                </div>
                <div class="feature-classified-box">
                    <div class="f-box-content" data-aos="fade-right"data-aos-duration="900">
                        <div class="f-box-head">Classified Product Activate</div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                </div>  
            </div>
            <div class="feature-business">
                <div class="feature-business-heading" data-aos="fade-left"data-aos-duration="1500">
                    Business Related
                </div>
                <div class="feature-business-box">
                    <div class="f-box-content" data-aos="flip-right" data-aos-duration="900">
                        <div class="f-box-head">Vendor System Activation</div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                    <div class="f-box-content"  data-aos="flip-right" data-aos-duration="900">
                        <div class="f-box-head">Wallet System Activation</div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                    <div class="f-box-content"  data-aos="flip-right" data-aos-duration="900">
                        <div class="f-box-head">Coupon System Activation</div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                    <div class="f-box-content"  data-aos="flip-right" data-aos-duration="900">
                        <div class="f-box-head">Pickup Point Activation</div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                    <div class="f-box-content"  data-aos="flip-right" data-aos-duration="900">
                        <div class="f-box-head">Conversation Activation</div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                    <div class="f-box-content"  data-aos="flip-right" data-aos-duration="900">
                        <div class="f-box-head">Guest Checkout Activation</div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                    <div class="f-box-content"  data-aos="flip-right" data-aos-duration="900">
                        <div class="f-box-head">Category-based Commission</div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                    <div class="f-box-content"  data-aos="flip-right" data-aos-duration="900">
                        <div class="f-box-head">Email Verification</div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                </div>  
            </div>
            <div class="feature-Payment">
                <div class="feature-Payment-heading" data-aos="fade-left"data-aos-duration="1500">
                    Payment Related
                </div>
                <div class="feature-Payment-box">
                    <div class="f-box-content"  data-aos="flip-left" data-aos-duration="900">
                        <div class="f-box-head">Paypal Payment Activation</div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                    <div class="f-box-content"  data-aos="flip-left" data-aos-duration="900">
                        <div class="f-box-head">Stripe Payment Activation</div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                    <div class="f-box-content"  data-aos="flip-left" data-aos-duration="900">
                        <div class="f-box-head">SSlCommerz Activation</div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                    <div class="f-box-content"  data-aos="flip-left" data-aos-duration="900">
                        <div class="f-box-head">Instamojo Payment Activation</div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                    <div class="f-box-content"  data-aos="flip-left" data-aos-duration="900">
                        <div class="f-box-head">Maintenance Mode Activation</div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                    <div class="f-box-content"  data-aos="flip-left" data-aos-duration="900">
                        <div class="f-box-head">PayStack Activation</div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                    <div class="f-box-content"  data-aos="flip-left" data-aos-duration="900">
                        <div class="f-box-head">VoguePay Activation</div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                    <div class="f-box-content"  data-aos="flip-left" data-aos-duration="900">
                        <div class="f-box-head">Payhere Activation</div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                    <div class="f-box-content"  data-aos="flip-left" data-aos-duration="900">
                        <div class="f-box-head">Cash Payment Activation</div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                </div>  
            </div>
            <div class="feature-Login">
                <div class="feature-Login-heading" data-aos="fade-left"data-aos-duration="1000">
                    Social Media Login
                </div>
                <div class="feature-login-main">
                    <div class="feature-Login-box">
                        <div class="f-box-content" data-aos="zoom-in" data-aos-duration="900">
                            <div class="f-box-head">Facebook login</div>
                            <div class="f-box-switch">
                                <label class="switch">
                                    <input type="checkbox">
                                    <span class="slider round"></span>
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="feature-Login-box">
                        <div class="f-box-content" data-aos="zoom-in" data-aos-duration="900">
                            <div class="f-box-head">Google login</div>
                            <div class="f-box-switch">
                                <label class="switch">
                                    <input type="checkbox">
                                    <span class="slider round"></span>
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="feature-Login-box">
                        <div class="f-box-content" data-aos="zoom-in" data-aos-duration="900">
                            <div class="f-box-head">Twitter login</div>
                            <div class="f-box-switch">
                                <label class="switch">
                                    <input type="checkbox">
                                    <span class="slider round"></span>
                                </label>
                            </div>
                        </div>
                    </div>
                </div>  
            </div>
        </div>
    </div>
</div>
    