<div class="wrapper">
    <div class="row">
        <div class="feature-dashboard-main">
            <h1 data-aos="fade-right"data-aos-duration="1500"><?php 
echo getlang('','Feature activation',getlangcookie()); 
?>  </h1>
        </div>
        <div class="feature-main">
            <div class="feature-hhtps">
                <div class="feature-hhtps-heading" data-aos="fade-left"data-aos-duration="1000">
                    <?php 
echo getlang('','HTTPS Activation',getlangcookie()); 
?>  
                </div>
                <div class="feature-hhtps-box">
                    <div class="f-box-content" data-aos="fade-right"data-aos-duration="900">
                        <div class="f-box-head"><?php 
echo getlang('','HTTPS Activation',getlangcookie()); 
?>  </div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                </div>  
            </div>
            <div class="feature-maintenance">
                <div class="feature-maintenance-heading" data-aos="fade-left"data-aos-duration="1000">
                    <?php 
echo getlang('','Maintenance Mode',getlangcookie()); 
?>  
                </div>
                <div class="feature-maintenance-box">
                    <div class="f-box-content" data-aos="fade-right"data-aos-duration="900">
                        <div class="f-box-head"><?php 
echo getlang('','Maintenance Mode Activation',getlangcookie()); 
?>  </div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                </div>  
            </div>
            <div class="feature-classified">
                <div class="feature-classified-heading" data-aos="fade-left"data-aos-duration="1000">
                    <?php 
echo getlang('','Classified Product',getlangcookie()); 
?>  
                </div>
                <div class="feature-classified-box">
                    <div class="f-box-content" data-aos="fade-right"data-aos-duration="900">
                        <div class="f-box-head"><?php 
echo getlang('','Classified Product Activate',getlangcookie()); 
?>  </div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                </div>  
            </div>
            <div class="feature-business">
                <div class="feature-business-heading" data-aos="fade-left"data-aos-duration="1500">
                    <?php 
echo getlang('','Business Related',getlangcookie()); 
?>  
                </div>
                <div class="feature-business-box">
                    <div class="f-box-content" data-aos="flip-right" data-aos-duration="900">
                        <div class="f-box-head"><?php 
echo getlang('','Vendor System Activation',getlangcookie()); 
?>  </div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                    <div class="f-box-content"  data-aos="flip-right" data-aos-duration="900">
                        <div class="f-box-head"><?php 
echo getlang('','Wallet System Activation',getlangcookie()); 
?>  </div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                    <div class="f-box-content"  data-aos="flip-right" data-aos-duration="900">
                        <div class="f-box-head"><?php 
echo getlang('','Coupon System Activation',getlangcookie()); 
?>  </div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                    <div class="f-box-content"  data-aos="flip-right" data-aos-duration="900">
                        <div class="f-box-head"><?php 
echo getlang('','Pickup Point Activation',getlangcookie()); 
?>  </div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                    <div class="f-box-content"  data-aos="flip-right" data-aos-duration="900">
                        <div class="f-box-head"><?php 
echo getlang('','Conversation Activation',getlangcookie()); 
?>  </div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                    <div class="f-box-content"  data-aos="flip-right" data-aos-duration="900">
                        <div class="f-box-head"><?php 
echo getlang('','Guest Checkout Activation',getlangcookie()); 
?>  </div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                    <div class="f-box-content"  data-aos="flip-right" data-aos-duration="900">
                        <div class="f-box-head"><?php 
echo getlang('','Category-based Commission',getlangcookie()); 
?>  </div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                    <div class="f-box-content"  data-aos="flip-right" data-aos-duration="900">
                        <div class="f-box-head"><?php 
echo getlang('','Email Verification',getlangcookie()); 
?>  </div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                </div>  
            </div>
            <div class="feature-Payment">
                <div class="feature-Payment-heading" data-aos="fade-left"data-aos-duration="1500">
                    <?php 
echo getlang('','Payment Related',getlangcookie()); 
?>  
                </div>
                <div class="feature-Payment-box">
                    <div class="f-box-content"  data-aos="flip-left" data-aos-duration="900">
                        <div class="f-box-head"><?php 
echo getlang('','Paypal Payment Activation',getlangcookie()); 
?>  </div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                    <div class="f-box-content"  data-aos="flip-left" data-aos-duration="900">
                        <div class="f-box-head"><?php 
echo getlang('','Stripe Payment Activation',getlangcookie()); 
?>  </div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                    <div class="f-box-content"  data-aos="flip-left" data-aos-duration="900">
                        <div class="f-box-head"><?php 
echo getlang('','SSlCommerz Activation',getlangcookie()); 
?>  </div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                    <div class="f-box-content"  data-aos="flip-left" data-aos-duration="900">
                        <div class="f-box-head"><?php 
echo getlang('','Instamojo Payment Activation',getlangcookie()); 
?>  </div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                    <div class="f-box-content"  data-aos="flip-left" data-aos-duration="900">
                        <div class="f-box-head"><?php 
echo getlang('','Maintenance Mode Activation',getlangcookie()); 
?>  </div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                    <div class="f-box-content"  data-aos="flip-left" data-aos-duration="900">
                        <div class="f-box-head"><?php 
echo getlang('','PayStack Activation',getlangcookie()); 
?>  </div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                    <div class="f-box-content"  data-aos="flip-left" data-aos-duration="900">
                        <div class="f-box-head"><?php 
echo getlang('','VoguePay Activation',getlangcookie()); 
?>  </div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                    <div class="f-box-content"  data-aos="flip-left" data-aos-duration="900">
                        <div class="f-box-head"><?php 
echo getlang('','Payhere Activation',getlangcookie()); 
?>  </div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                    <div class="f-box-content"  data-aos="flip-left" data-aos-duration="900">
                        <div class="f-box-head"><?php 
echo getlang('','Cash Payment Activation',getlangcookie()); 
?>  </div>
                        <div class="f-box-switch">
                            <label class="switch">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                </div>  
            </div>
            <div class="feature-Login">
                <div class="feature-Login-heading" data-aos="fade-left"data-aos-duration="1000">
                    <?php 
echo getlang('','Social Media Login',getlangcookie()); 
?>  
                </div>
                <div class="feature-login-main">
                    <div class="feature-Login-box">
                        <div class="f-box-content" data-aos="zoom-in" data-aos-duration="900">
                            <div class="f-box-head"><?php 
echo getlang('','Facebook login',getlangcookie()); 
?>  </div>
                            <div class="f-box-switch">
                                <label class="switch">
                                    <input type="checkbox">
                                    <span class="slider round"></span>
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="feature-Login-box">
                        <div class="f-box-content" data-aos="zoom-in" data-aos-duration="900">
                            <div class="f-box-head"><?php 
echo getlang('','Google login',getlangcookie()); 
?>  </div>
                            <div class="f-box-switch">
                                <label class="switch">
                                    <input type="checkbox">
                                    <span class="slider round"></span>
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="feature-Login-box">
                        <div class="f-box-content" data-aos="zoom-in" data-aos-duration="900">
                            <div class="f-box-head"><?php 
echo getlang('','Twitter login',getlangcookie()); 
?>  </div>
                            <div class="f-box-switch">
                                <label class="switch">
                                    <input type="checkbox">
                                    <span class="slider round"></span>
                                </label>
                            </div>
                        </div>
                    </div>
                </div>  
            </div>
        </div>
    </div>
</div>
    