<div class="wrapper">
    <div class="row">
        <div class="flashdeal-dashboard-main">
        <h1 data-aos="fade-right" data-aos-duration="1500">Flash Deal</h1>
        <!-- <form data-aos="fade-down" data-aos-duration="1500">
            <input type="text">
            <input class="s-btn" type="button" value="Search">
        </form> -->
        <div class="flash-new-deal-btn">
            <a href="?page=addnewdeal_dashboard" data-aos="fade-left" data-aos-duration="1500">Add New Deal</a>
        </div>
    </div>
    <div class="Flashdeal-table-main" data-aos="zoom-out-up" data-aos-duration="600">
        <form action="">
            <table>
                <tr>
                    <th>Serial.No</th>
                    <th>title</th>
                    <th>Banner</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>Status</th>
                    <th>Featured</th>
                    <th>Page Link</th>
                    <th>Option</th>
                </tr>
                <tr>
                    <td>1</td>
                    <td>Winter Deal</td>
                    <td>
                        <img src="https://demo.sirv.com/chair.jpg?scale.width=71  " alt="">
                    </td>
                    <td>03/01/2021</td>
                    <td>03/01/2021</td>
                    <td> 
                        <label class="switch">
                        <input type="checkbox">
                        <span class="slider round"></span>
                        </label>
                    </td>
                    <td>
                        <label class="switch">
                        <input type="checkbox">
                        <span class="slider round"></span>
                        </label>
                    </td>
                    <td>
                        <a href="#">www.google.com</a>
                    </td>
                    <td class="option">
                        <a href="?page=addnewdeal_dashboard">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit
                        </a>

                        <a href="#">
                            <i class="fa fa-trash" aria-hidden="true"></i> Remove
                        </a>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>
</div>

order&order_id=<?= $value['id'] ?>