	<!-- sidebar -->
	<div class="sidebar" style="overflow:scroll;">
		
		<ul class="sidebar-nav">
			<?php 
			foreach ($menu as $key => $value) {

				$count = count(checkpermission_menu(1,$value['menu_id']));


				if($count > 0){
				if($value['url'] == '#'){

					$url = $value['url'];

				}else{

					$url = '?page='.$value['url'];
				}




			?>

				<li class="sidebar-nav-item sub-menu">
				<a href="<?php echo $url;?> " class="sidebar-nav-link">
					<div>
                    <i class="fa fa-<?php echo $value['icon'];?> " aria-hidden="true"></i>
					</div>
					<span>
                        <?php echo $value['title'];?>  
					</span>
				</a>

					<?PHP
			$submenu = getsubmenu($value['menu_id']);
				if (!empty($submenu)) {


						
					?>
				
				<ul class="sub">
					<?php 
					foreach ($submenu as $key => $value) {
				$subcount  	=	count(checkpermission_submenu(1,$value['sm_id']));
     				if($subcount > 0){
						?>
     				

<li>
						<a href="?page=<?php echo $value['sm_url'];?> ">
						<div class="sub-menu-inner-icon">
							<i class="fa fa- <?php echo $value['sm_icon'];?> " aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							 <?php echo $value['sm_title'];?>  
						</div>
						</a>
					</li>

						<?php
					}
					}

					?>
					
					
				</ul>
				<?php  

}
				?>
			</li>

			<?php

}
			}

			?>
			
		<!-- 	<li  class="sidebar-nav-item sub-menu">
				<a href="#" class="sidebar-nav-link">
					<div>
						<i class="fa fa-usd" aria-hidden="true"></i>
					</div>
					<span>Sales</span>
				</a>
				<ul class="sub">
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							orders
						</div>
						</a>
					</li>
					<li>
						<a href="?page=Account_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							account
						</div>
						</a>
					</li>
				</ul>
			</li>
			<li  class="sidebar-nav-item sub-menu">
				<a href="#" class="sidebar-nav-link">
					<div>
                        <i class="fa fa-eye" aria-hidden="true"></i>
					</div>
					<span>Order View</span>
				</a>
				<ul class="sub">
					<li>
						<a href="?page=addnewproduct_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							add new product
						</div>
						</a>
					</li>
					<li>
						<a href="?page=blukimport_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							bulk import		
						</div>
						</a>
					</li>
					<li>
						<a href="?page=blukexport_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							bulk export
						</div>
						</a>
					</li>
					<li>
						<a href="?page=category_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							category
						</div>
						</a>
					</li>
					<li>
						<a href="?page=subcategory_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							subcategory
						</div>
						</a>
					</li>
					<li>
						<a href="?page=brand_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							brand
						</div>
						</a>
					</li>
					<li>
						<a href="?page=attibute_dashboard#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							attibute
						</div>
						</a>
					</li>
					<li>
						<a href="?page=productreview_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							product reviews
						</div>
						</a>
					</li>
					
                    <li>
						<a href="?page=signupvendor_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							Become Vendor
						</div>
						</a>
					</li>
					<li>
						<a href="?page=vendorprofile_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							Vendor Profile
						</div>
						</a>
					</li>
                      <li>
						<a href="?page=requestbranch_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							request branch
						</div>
						</a>
					</li>
				</ul>
            </li>
            <li class="sidebar-nav-item sub-menu">
				<a href="#" class="sidebar-nav-link">
					<div>
                        <i class="fa fa-user" aria-hidden="true"></i>
					</div>
					<span>Customers</span>
				</a>
				<ul class="sub">
					<li>
						<a href="?page=customerlist_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							Customer list
						</div>
						</a>
					</li>
				</ul>
			</li>
			<li class="sidebar-nav-item sub-menu">
				<a href="#" class="sidebar-nav-link">
					<div>
						<i class="fa fa-connectdevelop" aria-hidden="true"></i>
					</div>
					<span>Branches</span>
				</a>
				<ul class="sub">
					<li>
						<a href="?page=branchlist_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							branch list
						</div>
						</a>
					</li>
				</ul>
			</li>
			<li  class="sidebar-nav-item sub-menu">
				<a href="#" class="sidebar-nav-link">
					<div>
                        <i class="fa fa-list-alt" aria-hidden="true"></i>
					</div>
					<span>Reports</span>
				</a>
				<ul class="sub">
					<li>
						<a href="?page=allreports_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							all reports
						</div>
						</a>
					</li>
					<li>
						<a href="?page=productstock_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							products stock
						</div>
						</a>
					</li>
					<li>
						<a href="?page=productwish_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							product whishlist
						</div>
						</a>
					</li>
					<li>
						<a href="?page=usersearches_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							user searches
						</div>
						</a>
					</li>
				</ul>
			</li>
			<li  class="sidebar-nav-item sub-menu">
				<a href="#" class="sidebar-nav-link">
					<div>
						<i class="fa fa-bullhorn" aria-hidden="true"></i>
					</div>
					<span>Marketing</span>
				</a>
				<ul class="sub">
					<li>
						<a href="?page=flashdeal_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							Flash Deals
						</div>
						</a>
					</li>
					<li>
						<a href="?page=newsletter_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							Newsletter
						</div>
						</a>
					</li>
					<li>
						<a href="?page=bluksms_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							bulk sms
						</div>
						</a>
					</li>
					<li>
						<a href="?page=subscrib_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							subscribers
						</div>
						</a>
					</li>
					<li>
						<a href="?page=coupons_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							coupons
						</div>
						</a>
					</li>
					<li>
						<a href="?page=email_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							emails
						</div>
						</a>
					</li>
				</ul>
			</li>
			<li  class="sidebar-nav-item sub-menu">
				<a href="#" class="sidebar-nav-link">
					<div>
						<i class="fa fa-question-circle" aria-hidden="true"></i>
					</div>
					<span>Support</span>
				</a>
				<ul class="sub">
					<li>
						<a href="?page=tickets_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							tickets
						</div>
						</a>
					</li>
					<li>
						<a href="?page=chat_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							Chats
						</div>
						</a>
					</li>
				</ul>
			</li>
			<li  class="sidebar-nav-item sub-menu">
				<a href="#" class="sidebar-nav-link">
					<div>
						<i class="fa fa-users" aria-hidden="true"></i>
					</div>
					<span>Staff</span>
				</a>
				<ul class="sub">
					<li>
						<a href="?page=allstaff_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							All Staff
						</div>
						</a>
					</li>
					<li>
						<a href="?page=staffpermission_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							Staff Permission
						</div>
						</a>
					</li>
				</ul>
			</li>
			<li  class="sidebar-nav-item sub-menu">
				<a href="#" class="sidebar-nav-link">
					<div>
						<i class="fa fa-desktop" aria-hidden="true"></i>
					</div>
					<span>WebSite Setup</span>
				</a>
				<ul class="sub">
					<li>
						<a href="?page=header_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							Header 
						</div>
						</a>
					</li>
					<li>
						<a href="?page=footer_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							Footer
						</div>
						</a>
					</li>
					<li>
						<a href="?page=pages_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							Pages
						</div>
						</a>
					</li>
					<li>
						<a href="?page=appearance_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							Appearance
						</div>
						</a>
					</li>
					<li>
						<a href="?page=knowledgebase_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							knowledge Base
						</div>
						</a>
					</li>
				</ul>
			</li>
			<li  class="sidebar-nav-item sub-menu">
				<a href="#" class="sidebar-nav-link">
					<div>
						<i class="fa fa-cogs" aria-hidden="true"></i>
					</div>
					<span>Setting</span>
				</a>
				<ul class="sub">
					<li>
						<a href="?page=generalsetting_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							general settings
						</div>
						</a>
					</li>
					<li>
						<a href="?page=featureactive_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							features activation
						</div>
						</a>
					</li>
					<li>
						<a href="?page=language_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							languages
						</div>
						</a>
					</li>
					<li>
						<a href="?page=currency_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							currency
						</div>
						</a>
					</li>
					<li>
						<a href="?page=pickuppoint_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							pickup points
						</div>
						</a>
					</li>
					<li>
						<a href="?page=paymentmethod_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							payment methods
						</div>
						</a>
					</li>
					<li>
						<a href="?page=smtpsetting_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							smtp settings
						</div>
						</a>
					</li>
					<li>
						<a href="?page=socialmedia_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							social media link
						</div>
						</a>
					</li>
					<li>
						<a href="?page=shippingconfig_dashboard">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-angle-double-right" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
						shipping configuration
						</div>
						</a>
					</li>
				</ul>
			</li> -->
		</ul>
	</div>
	<!-- end sidebar -->