<?php 
    $footer_about_disc = search_array('footer about dis',$config_system);
    $foote_ad = search_array('address',$config_system);
    $footer_contact = search_array('contact',$config_system);
    $footer_email = search_array('email',$config_system);
    $footer_copyr = search_array('Copyrighttext',$config_system);
    $footer_fb_link = search_array('facebook',$config_system);
    $footer_tw_link = search_array('twitter',$config_system);
    $footer_inst_link = search_array('instagram',$config_system);
    $footer_in_link = search_array('Linkin',$config_system);
?>


<div class="wrapper">
    <div class="row">
        <div class="dashboard-footer">
        <h1 data-aos="fade-right" data-aos-duration="2000" ><?php 
echo getlang('','Footer',getlangcookie()); 
?>  </h1>
    </div>
    <div class="dashboard-footer-about" data-aos="zoom-out-right" data-aos-duration="1000">
        <form action="<?= $controller; ?>" class="d-footer-logo-about" id="form">
            <div class="dashboard-footer-logo">
                <div class="footer-logo-upload-label">
                    <label for=""><?php 
echo getlang('','Footer Logo',getlangcookie()); 
?>  </label>
                </div>
                <div class="footer-logo-upload-content">
                    <input type='file' name="footer_logo" onchange="readURL(this);" require/>
                    <img id="blah" src="http://placehold.it/180" alt="your image" />
                </div>
            </div>
            <div class="dashboard-footer-about-dis">
                <div class="footer-about-upload-label">
                    <label for=""><?php 
echo getlang('','About Discribtion :',getlangcookie()); 
?>  </label>
                </div>
                <div class="footer-about-upload-content">
                    <textarea name="footer_about_desc" id="myTextAreaSec" class="tinymce" require><?php echo $footer_about_disc['value'];?></textarea>
                </div>
            </div>
            <div class="dashboard-footer-about-btn">
                <input type="button" value="<?php 
echo getlang('','Update logo & Discribtion',getlangcookie()); 
?>  " onclick="submitForm()">
            </div>
        </form>
    </div>
<div class="dashboard-footer-section-2">
    <div class="dashboard-footer-contact" data-aos="fade-up-right" data-aos-duration="1000">
        <h1><?php 
echo getlang('','Contact info',getlangcookie()); 
?>  </h1>
        <form action="<?= $controller; ?>" class="d-footer-logo-contact" id="cntForm">
            <div class="dashboard-footer-contact-add">
                <div class="footer-contact-add-head">
                    <label for=""><?php 
echo getlang('','Contact Address',getlangcookie()); 
?>  </label>
                </div>
                <div class="footer-contact-add-input">
                    <input type='text' name="contact_add" value="<?php echo $foote_ad['value'];?>" require/>
                </div>
            </div>
            <div class="dashboard-footer-contact-phone">
                <div class="footer-contact-phone-head">
                    <label for=""><?php 
echo getlang('','Contact Phone',getlangcookie()); 
?>  </label>
                </div>
                <div class="footer-contact-phone-input">
                    <input type='text' name="contact_ph"  value="<?php echo $footer_contact['value'];?>" require/>
                </div>
            </div>
            <div class="dashboard-footer-contact-email">
                <div class="footer-contact-email-head">
                    <label for=""><?php 
echo getlang('','Contact E-mail',getlangcookie()); 
?>  </label>
                </div>
                <div class="footer-contact-email-input">
                    <input type='text' name="contact_email" value="<?php echo $footer_email['value'];?>" require/>
                </div>
            </div>
            <div class="dashboard-footer-contact-btn">
                <input type="button" value="<?php 
echo getlang('','Update',getlangcookie()); 
?>  " onclick="submitFormCnt()">
            </div>
        </form>
    </div>
    <div class="dashboard-footer-bottom" data-aos="fade-left" data-aos-duration="1000" >
        <form action="<?= $controller; ?>" class="dashboard-footer-bottom-content" id="cpyForm">
            <div class="d-footer-copyright">
                <div class="d-footer-copyright-head">
                    <label><?php 
echo getlang('','Copyright Text',getlangcookie()); 
?>  </label>
                </div>
                <div class="d-footer-copyright-input">
                    <input type="text" name="cpy_text" value="<?php echo $footer_copyr['value'];?>">
                </div>
            </div>
            <div class="d-footer-social-media">
                <div class="d-footer-social-link-switcher">
                    <label><?php 
echo getlang('','Show Social Media Links.',getlangcookie()); 
?>  </label>
                    <div class="d-footer-social-switch">
                        <label class="switch">
                        <input type="checkbox" name="social_links">
                        <span class="slider round"></span>
                        </label>
                    </div>
                </div>
                <div class="d-footer-social-links">
                    <div class="d-footer-social-links-head"><?php 
echo getlang('','Social links',getlangcookie()); 
?>  </div>
                    <div class="d-footer-social-icons">
                        <div class="d-footer-icons-main">
                            <div class="d-footer-icons">
                                <i class="fa fa-facebook" aria-hidden="true"></i>
                            </div>
                            <div class="d-footer-icons-links">
                                <input type="text" name="facebook" value="<?php echo $footer_fb_link['value'];?>">
                            </div>
                        </div>
                        <div class="d-footer-icons-main">
                            <div class="d-footer-icons">
                            <i class="fa fa-twitter" aria-hidden="true"></i>
                            </div>
                            <div class="d-footer-icons-links">
                                <input type="text" name="twitter" value="<?php echo $footer_tw_link['value'];?>">
                            </div>
                        </div>
                        <div class="d-footer-icons-main">
                            <div class="d-footer-icons">
                            <i class="fa fa-instagram" aria-hidden="true"></i>
                            </div>
                            <div class="d-footer-icons-links">
                                <input type="text" name="instagram" value="<?php echo $footer_inst_link['value'];?>">
                            </div>
                        </div>
                        <div class="d-footer-icons-main">
                            <div class="d-footer-icons">
                            <i class="fa fa-linkedin" aria-hidden="true"></i>
                            </div>
                            <div class="d-footer-icons-links">
                                <input type="text" name="linkedin" value="<?php echo $footer_in_link['value'];?>">
                            </div>
                        </div>
                    </div>
                    <div class="footer-social-link-icon">
                        <input type="button" value="<?php 
echo getlang('','Update',getlangcookie()); 
?>  " onclick="submitFormCpy()">
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
</div>
</div>

<script>
  function submitForm(form){
    var myContent = tinymce.get("myTextAreaSec").getContent();
      $('#myTextAreaSec').html(myContent);
        url = $('#form').attr("action");
        formData = $('#form').serializeArray();
        $.post(url, formData).done(function (data) {
        if(data == 1){
            alert('success');
            location.reload();
        }else{
            alert('error');
        }
    });
  }
  function submitFormCnt(form){
    
    url = $('#cntForm').attr("action");
    formData = $('#cntForm').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
            alert('success');
            location.reload();
        }else{
            alert('error');
        }
    });
  }
        
  function submitFormCpy(form){
    
    url = $('#cpyForm').attr("action");
    formData = $('#cpyForm').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
            alert('success');
            location.reload();
        }else{
            alert('error');
        }
    });
  }
</script>