	<?php
	// session_start(); 
	if(isset($_SESSION['status'])){

//header('Location: ?page=dashboard');
if($_SESSION['status'] == 'block'){


header('Location: ?page=verification_dashboard');


}else{
$logo_directory =  '../app/upload/logos/';
if($userstatus == 'Branch'){
                                $ustatus = 'Vendor';
                            }elseif ($userstatus == 'Vendor') {
                                $ustatus = 'Brand';
                            }else{
                                $ustatus = $userstatus;
                                $vendor_id = null;
                            }


$vendor_data  = getvendors('',$vendor_id,'FALSE');
if(!empty($vendor_data)){
$vendor_id = $vendor_data[0]['user_id']; 
}
$logo_dashboard = getlogo('',$logo_directory,$vendor_id);



?>

	<!-- sidebar -->
	<div class="sidebar">
		
		<ul class="sidebar-nav" id="accordion">
			<div class="sidebar-head-content">
				<div class="sidebar-head-content-main-upper">
					<a class="content-main-upper-2" href="?page=home"><img src="<?php echo $logo_dashboard;?>" alt="Admin logo" class="logo logo-light"></a>
				</div>
				<div class="sidebar-head-content-main-lower">
					<div class="content-main-lower">
						<h4><?PHP IF(!empty($userstatus)){ ECHO 'Welcome '. $ustatus; }?></h4>
					</div>
				</div>
			</div>
			
			<?php 
			foreach ($menu as $key => $value) {

				$count = count(checkpermission_menu($_SESSION['type'],$value['menu_id']));


				if($count > 0){
				if($value['url'] == '#'){

					$url = $value['url'];

				}else{

					$url = '?page='.$value['url'];
				}




			?>

				<li class="sidebar-nav-item sub-menu">
				<a href="<?php echo $url;?> " class="sidebar-nav-link">
					<div>
                    <i class="fa fa-<?php echo $value['icon'];?> " aria-hidden="true"></i>
					</div>
					<span>
                        <?php echo $value['title'];?>  
					</span>
					
				</a>

					<?PHP
			$submenu = getsubmenu($value['menu_id']);
				if (!empty($submenu)) {


						
					?>
				
				<ul class="sub">
					<?php 
					foreach ($submenu as $key => $value) {
				$subcount  	=	count(checkpermission_submenu($_SESSION['type'],$value['sm_id']));
     				if($subcount > 0){
     					// if($value['sm_url'] == 'viewbranch_dashboard' && empty(getbranches($logInId))){

     					// 	$skip = true;

     					// }else{


     					// 	$skip = false;

     					// }


						?>
     				

<li>
						<a href="?page=<?php echo $value['sm_url'];?> ">
						<div class="sub-menu-inner-icon">
							<i class="fa fa- <?php echo $value['sm_icon'];?> " aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							 <?php echo $value['sm_title'];?>  
						</div>
						</a>
					</li>

						<?php
					
					}
					}

					?>
					
					
				</ul>
				<?php  

}
				?>
			</li>

			<?php

}
			}

			?>
			
	
		</ul>
	</div>
	<!-- end sidebar -->




<?php
}



	}else{


header('Location: ?page=login_dashboard');


	}



	?>


