	<?php
	// session_start(); 
	if(isset($_SESSION['status'])){

//header('Location: ?page=dashboard');
if($_SESSION['status'] == 'block'){


header('Location: ?page=verification_dashboard');

}else{


?>

	<!-- sidebar -->
	<div class="sidebar" style="overflow:scroll;">
		
		<ul class="sidebar-nav">
			<?php 
			foreach ($menu as $key => $value) {

				$count = count(checkpermission_menu($_SESSION['type'],$value['menu_id']));


				if($count > 0){
				if($value['url'] == '#'){

					$url = $value['url'];

				}else{

					$url = '?page='.$value['url'];
				}




			?>

				<li class="sidebar-nav-item sub-menu">
				<a href="<?php echo $url;?> " class="sidebar-nav-link">
					<div>
                    <i class="fa fa-<?php echo $value['icon'];?> " aria-hidden="true"></i>
					</div>
					<span>
                        <?php echo $value['title'];?>  
					</span>
				</a>

					<?PHP
			$submenu = getsubmenu($value['menu_id']);
				if (!empty($submenu)) {


						
					?>
				
				<ul class="sub">
					<?php 
					foreach ($submenu as $key => $value) {
				$subcount  	=	count(checkpermission_submenu(1,$value['sm_id']));
     				if($subcount > 0){
						?>
     				

<li>
						<a href="?page=<?php echo $value['sm_url'];?> ">
						<div class="sub-menu-inner-icon">
							<i class="fa fa- <?php echo $value['sm_icon'];?> " aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							 <?php echo $value['sm_title'];?>  
						</div>
						</a>
					</li>

						<?php
					}
					}

					?>
					
					
				</ul>
				<?php  

}
				?>
			</li>

			<?php

}
			}

			?>
			
	
		</ul>
	</div>
	<!-- end sidebar -->




<?php
}



	}else{


header('Location: ?page=login_dashboard');


	}



	?>


