<div class="wrapper">
    <div class="row">
        <div class="dashboard-footer">
        <h1 data-aos="fade-right" data-aos-duration="2000" >Footer</h1>
    </div>
    <div class="dashboard-footer-about" data-aos="zoom-out-right" data-aos-duration="1000">
        <form action="" class="d-footer-logo-about">
            <div class="dashboard-footer-logo">
                <div class="footer-logo-upload-label">
                    <label for="">Footer Logo :</label>
                </div>
                <div class="footer-logo-upload-content">
                    <input type='file' onchange="readURL(this);" />
                    <img id="blah" src="http://placehold.it/180" alt="your image" />
                </div>
            </div>
            <div class="dashboard-footer-about">
                <div class="footer-about-upload-label">
                    <label for="">About Discribtion :</label>
                </div>
                <div class="footer-about-upload-content">
                    <textarea name="" id="" cols="30" rows="10"></textarea>
                </div>
            </div>
            <div class="dashboard-footer-about-btn">
                <input type="button" value="Upadate">
            </div>
        </form>
    </div>
<div class="dashboard-footer-section-2">
    <div class="dashboard-footer-contact" data-aos="fade-up-right" data-aos-duration="1000">
        <h1>Contact info</h1>
        <form action="" class="d-footer-logo-contact">
            <div class="dashboard-footer-contact-add">
                <div class="footer-contact-add-head">
                    <label for="">Contact Address</label>
                </div>
                <div class="footer-contact-add-input">
                    <input type='text'/>
                </div>
            </div>
            <div class="dashboard-footer-contact-phone">
                <div class="footer-contact-phone-head">
                    <label for="">Contact Phone</label>
                </div>
                <div class="footer-contact-phone-input">
                    <input type='text'/>
                </div>
            </div>
            <div class="dashboard-footer-contact-email">
                <div class="footer-contact-email-head">
                    <label for="">Contact E-mail</label>
                </div>
                <div class="footer-contact-email-input">
                    <input type='text'/>
                </div>
            </div>
            <div class="dashboard-footer-contact-btn">
                <input type="button" value="Upadate">
            </div>
        </form>
    </div>
    <div class="dashboard-footer-bottom" data-aos="fade-left" data-aos-duration="1000" >
        <form class="dashboard-footer-bottom-content">
            <div class="d-footer-copyright">
                <div class="d-footer-copyright-head">
                    <label>Copyright Text</label>
                </div>
                <div class="d-footer-copyright-input">
                    <input type="text">
                </div>
            </div>
            <div class="d-footer-social-media">
                <div class="d-footer-social-link-switcher">
                    <label>Show Social Media Links.</label>
                    <div class="d-footer-social-switch">
                        <label class="switch">
                        <input type="checkbox">
                        <span class="slider round"></span>
                        </label>
                    </div>
                </div>
                <div class="d-footer-social-links">
                    <div class="d-footer-social-links-head">Social links</div>
                    <div class="d-footer-social-icons">
                        <div class="d-footer-icons-main">
                            <div class="d-footer-icons">
                                <i class="fa fa-facebook" aria-hidden="true"></i>
                            </div>
                            <div class="d-footer-icons-links">
                                <input type="text">
                            </div>
                        </div>
                        <div class="d-footer-icons-main">
                            <div class="d-footer-icons">
                            <i class="fa fa-twitter" aria-hidden="true"></i>
                            </div>
                            <div class="d-footer-icons-links">
                                <input type="text">
                            </div>
                        </div>
                        <div class="d-footer-icons-main">
                            <div class="d-footer-icons">
                            <i class="fa fa-instagram" aria-hidden="true"></i>
                            </div>
                            <div class="d-footer-icons-links">
                                <input type="text">
                            </div>
                        </div>
                        <div class="d-footer-icons-main">
                            <div class="d-footer-icons">
                            <i class="fa fa-linkedin" aria-hidden="true"></i>
                            </div>
                            <div class="d-footer-icons-links">
                                <input type="text">
                            </div>
                        </div>
                    </div>
                    <div class="footer-social-link-icon">
                        <input type="button" value="Update">
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
</div>
</div>
