<div class="wrapper">
      <div class="row">
            <div class="general-dashboard-main">
                  <h1 data-aos="fade-right"data-aos-duration="1500"><?php 
echo getlang('','General Setting',getlangcookie()); 
?>  </h1>
            </div>  
            <div class="general-main" data-aos="zoom-in-up" data-aos-duration="600">
                  <form action="<?= $controller; ?>" id="form">
                        <div class="general-input1">
                              <div class="g-input-label"><?php 
echo getlang('','System Name',getlangcookie()); 
?>  </div>
                              <div class="g-input-input">
                                    <input type="text" name="system_name" require>
                              </div>
                        </div>
                        <div class="general-input2">
                              <div class="g-input-label"><?php 
echo getlang('','System Logo',getlangcookie()); 
?>  </div>
                              <div class="g-input-input">
                                    <input type='file' name="system_logo" onchange="readURL(this);" require />
                                    <img id="blah" src="http://placehold.it/100" alt="your image" style="width:100px" />
                              </div>
                        </div>
                        <div class="general-input4">
                              <div class="g-input-label"><?php 
echo getlang('','System timezone',getlangcookie()); 
?>  </div>
                              <div class="g-input-input">
                                    <select name="system_time" id="" require>
                                          <option value="1">1</option>
                                          <option value="2">2</option>
                                          <option value="3">3</option>
                                    </select>
                              </div>
                        </div>
                        <div class="general-input5">
                              <div class="g-input-label"><?php 
echo getlang('','Admin Login Page Background',getlangcookie()); 
?>  </div>
                              <div class="g-input-input">
                                    <input type='file' name="admin_page_background" onchange="readURL(this);" />
                                    <img id="blah" src="http://placehold.it/150" alt="your image" style="width:150px" />
                              </div>
                        </div>
                        <div class="g-btn">
                              <input type="button" value="<?php 
echo getlang('','Update',getlangcookie()); 
?>  " onclick="submitForm()">
                        </div>
                  </form>
            </div>    
      </div>
</div>
<script>
  function submitForm(form){
    
        url = $('#form').attr("action");
        formData = $('#form').serializeArray();

        $.post(url, formData).done(function (data) {
        if(data == 1){
            alert('success');
        }else{
            alert('error');
        }
    });
  }
  </script>
