<?php 
            $guide_title = search_array('guide title',$config_system);
            $guide_short_dis = search_array('guide Short Description',$config_system);
            $guide_code = search_array('guide video',$config_system);
?>

<div class="wrapper">
		<div class="row">
			<div class="bluk-sms-dashboard">
            <h1 data-aos="fade-right"data-aos-duration="1500"><?php 
echo getlang('','Guide',getlangcookie()); 
?></h1>
        </div>
        <div class="bluk-sms-main" data-aos="zoom-in-up" data-aos-duration="600">
            <form action="<?= $controller; ?>" id="form"> 
                <div class="bluk-sms-form2">
                    <label><?php 
echo getlang('','Title',getlangcookie()); 
?></label>
                    <input type="text" name="guid_title" value="<?php echo $guide_title['value'];?>" required>
                </div>
                <div class="bluk-sms-form2">
                    <label><?php 
echo getlang('','Short Description',getlangcookie()); 
?></label>
                    <input type="text" name="guid_short_desc" value="<?php echo $guide_short_dis['value'];?>" required>
                </div>
                <div class="bluk-sms-form2">
                    <label><?php 
echo getlang('','Video',getlangcookie()); 
?></label>
                    <textarea class="tinymce" id="myTextAreaSec" name="guid_video" required></textarea>
                </div>
                <div class="bluk-sms-btn">
                    <input type="button" value="<?php 
echo getlang('','Update',getlangcookie()); 
?>" onclick="submitForm()">
                </div>
            </form>
        </div>
        <!-- <div class="help-center-dashboard-main">
            <form >
                <table>
                    <tr>
                        <th>Serial No.</th>
                        <th>Question</th>
                        <th>Option</th>                
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>whats???</td>
                        <td>
                            <a href="#">
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit
                            </a>
                            <a href="#">
                                <i class="fa fa-trash" aria-hidden="true"></i> Remove
                            </a>
                        </td>
                    </tr>                
                </table>
            </form>
        </div> -->
    </div>
</div>
<script>
  function submitForm(form){
    var url = $('#form').attr("action");
    var myContent = tinymce.get("myTextAreaSec").getContent();
      $('#myTextAreaSec').html(myContent);
    var formData = $('#form').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
      alert('success');
      location.reload();
    }else{
      alert('error');
    }
    });
}
</script>