<?php
$dbcalss = '../app/model/classDatabaseManager.php';
require_once '../app/lib/functions.php';

 if(!empty($_SESSION['logInId'])){
 	

$user_id = $_SESSION['logInId'];

$result = getnotifications($dbcalss,$user_id,'');
}

?>
<body class="overlay-scrollbar light dashboard-body">

<div class="navbar" id="myNav">
		<!-- nav left -->
		<ul class="navbar-nav">
			<li class="nav-item">
				<a class="nav-link" onclick="collapseSidebar()">
					<i class="fa fa-angle-double-left" id="angle" aria-hidden="true" ></i>
				</a>
			</li>
			<li class="nav-item">

			<a href="?page=home">   <i class="fa fa-globe" aria-hidden="true"></i> View Your Site</a>
			</li>
		</ul>
		<!-- end nav left -->
		<!-- form -->
		<div class="navbar-search">

		</div>
		<!-- end form -->
		<!-- nav right -->
		<ul class="navbar-nav nav-right">
			
			<li class="nav-item dropdown">
				<a class="not-link">
          <i class="fa fa-bell dropdown-toggle" aria-hidden="true" data-toggle="notification-menu"></i>
					<span class="navbar-badge"><div id="result"></div> </span>
				</a>
				<ul id="notification-menu" class="dropdown-menu notification-menu">
					<div class="dropdown-menu-header">
						<span>
							Notifications 
						</span>
					</div>
					<div class="dropdown-menu-content overlay-scrollbar scrollbar-hover">
						<?php   

						if(!empty($result)){
							foreach ($result as $key => $value) {
								?>

				<li class="dropdown-menu-item">
							<a href="#" class="dropdown-menu-link">
								<div>
									<i class="fa fa-gift" aria-hidden="true"></i>
								</div>
								<span>
									<?php echo $value['type'] ; ?>
									<br>
									<!-- <span>
										23/10/2020
									</span> -->
								</span>
							</a>
						</li>
								<?php
							}



						}

							

						 ?>
						
						<!-- <li class="dropdown-menu-item">
							<a href="#" class="dropdown-menu-link">
								<div>
									<i class="fa fa-tasks" aria-hidden="true"></i>
								</div>
								<span>
									Nazreen Consulting Demo.
									<br>
									<span>
										23/10/2020
									</span>
								</span>
							</a>
						</li> -->
					</div>
					<div class="dropdown-menu-footer">
						<span>
							View all notifications
						</span>
					</div>
				</ul>
			</li>
			<li class="nav-item avt-wrapper">
				<div class="avt dropdown">

					<img src="<?php echo $image;?>dashboard1.png" alt="User image" class="dropdown-toggle" data-toggle="user-menu">
					<ul id="user-menu" class="dropdown-menu drop-down-menu">
						<li  class="dropdown-menu-item">
							<a href="?page=userprofile_dashboard" class="dropdown-menu-link">
								<div>
									<i class="fas fa-user-tie"></i>
								</div>
								<span>Profile</span>
							</a>
						</li>
						<li  class="dropdown-menu-item">
							<a href="?page=logout" class="dropdown-menu-link">
								<div>
									<i class="fas fa-sign-out-alt"></i>
								</div>
								<span>Logout</span>
							</a>
						</li>
					</ul>
				</div>
			</li>
		</ul>
		<!-- end nav right -->
  </div>
  <div id="result"></div>  
  <script>
	window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 50 || document.documentElement.scrollTop > 50) {
    document.getElementById("myNav").style.background = "rgba(0,0,0,0.4)";
  } else {
    document.getElementById("myNav").style.background = "transparent";
  }
}  
  </script>
  </body>