<div class="wrapper">
		<div class="row">
			<div class="dashboard-header">
            <h1  data-aos="fade-right" data-aos-duration="500">Header</h1>

            <form class="dashboard-header-form" action="" data-aos="fade-right">
                <div class="header-logo-upload" data-aos="fade-right" data-aos-duration="800">
                    <div class="header-logo-upload-label">
                        <label for="">Header Logo :</label>
                    </div>
                    <div class="header-logo-upload-content">
                        <input type='file' onchange="readURL(this);" />
                        <img id="blah" src="http://placehold.it/180" alt="your image" />
                    </div>
                </div>
                
                <div class="header-language-switch" data-aos="fade-right" data-aos-duration="900">
                    <div class="header-language-label">
                        <p>Show language Switch</p>
                    </div>
                    <div class="header-language-content">
                        <label class="switch">
                        <input type="checkbox">
                        <span class="slider round"></span>
                        </label>
                    </div>
                </div>

                <div class="header-currency-switch" data-aos="fade-right" data-aos-duration="1000">
                    <div class="header-currency-label">
                        <p>Show Currency Switch</p>
                    </div>
                    <div class="header-currency-content">
                        <label class="switch">
                        <input type="checkbox">
                        <span class="slider round"></span>
                        </label>
                    </div>
                </div>
                

                <div class="dashboard-header-btn">
                    <input type="button" value="Update">
                </div>
            </form>
        </div>
</div>
</div>
