<?php 
            $help_que = search_array('Help Question',$config_system);
            $help_ans = search_array('Help Ans',$config_system);
?>


<div class="wrapper">
		<div class="row">
			<div class="bluk-sms-dashboard">
            <h1 data-aos="fade-right"data-aos-duration="1500">Help Center</h1>
        </div>
        <div class="bluk-sms-main" data-aos="zoom-in-up" data-aos-duration="600">
            <form action="<?= $controller; ?>" id="form"> 
                <div class="bluk-sms-form2">
                    <label>Questions?</label>
                    <input type="text" name="help_question" value="<?php echo $help_que['value'];?>">
                </div>
                <div class="bluk-sms-form3">
                    <label>Answers</label>
                    <textarea class="tinymce" id="myTextAreaSec" name="help_answers"><?php echo $help_ans['value'];?></textarea>
                </div>
                <div class="bluk-sms-btn">
                    <input type="button" value="Update" onclick="submitForm()">
                </div>
            </form>
        </div>
        <div class="help-center-dashboard-main">
            <form >
                <table>
                    <tr>
                        <th>Serial No.</th>
                        <th>Question</th>
                        <th>Option</th>                
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>whats???</td>
                        <td>
                            <a href="#">
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit
                            </a>
                            <a href="#">
                                <i class="fa fa-trash" aria-hidden="true"></i> Remove
                            </a>
                        </td>
                    </tr>                
                </table>
            </form>
        </div>
    </div>
</div>
<script>
  function submitForm(form){
    var myContent = tinymce.get("myTextAreaSec").getContent();
      $('#myTextAreaSec').html(myContent);
    var url = $('#form').attr("action");
    
    var formData = $('#form').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
      alert('success');
      location.reload();
    }else{
      alert('error');
    }
    });
}
</script>