<?php 
    $k_b_title = search_array('blogtitle',$config_system);
    $k_b_dis = search_array('blogcode',$config_system);
?>

<div class="wrapper">
      <div class="row">
            <div class="general-dashboard-main">
                  <h1 data-aos="fade-right"data-aos-duration="1500"><?php 
echo getlang('','Knowledgebase & Blog',getlangcookie()); 
?>  </h1>
            </div>  
            <div class="general-main" data-aos="zoom-in-up" data-aos-duration="600">
                  <form action="<?= $controller ?>" id="form">
                        <div class="general-input1">
                              <div class="g-input-label"><?php 
echo getlang('','Title',getlangcookie()); 
?>  </div>
                              <div class="g-input-input">
                                    <input type="text" name="title" value="<?php echo $k_b_title['value'];?>" require>
                              </div>
                        </div>
                        <div class="general-input4">
                              <div class="g-input-label"><?php 
echo getlang('','Artical Type',getlangcookie()); 
?>  </div>
                              <div class="g-input-input">
                                    <select name="art_type" id="" >
                                          <option value="Blog"><?php 
echo getlang('','Blog',getlangcookie()); 
?>  </option>
                                          <option value="knowledge base"><?php 
echo getlang('','Knowledge Base',getlangcookie()); 
?>  </option>
                                    </select>
                              </div>
                        </div>
                        <div class="know-art-text-dashboard">
                            <textarea class="tinymce" id="myTextArea" name="blog" require> <?php echo $k_b_dis['value'];?></textarea>
                        </div>
                        <div class="g-btn">
                              <input type="button" value="<?php 
echo getlang('','Update',getlangcookie()); 
?>  " onclick="submitForm()">
                        </div>
                  </form>
            </div>    
      </div>
</div>
<script>
// tinymce.init({
//         selector: '#mytextarea'
//       }); 
  function submitForm(form){  
      var myContent = tinymce.get("myTextArea").getContent();
      $('#myTextArea').html(myContent);
      // $('.tinymce').html($('#tinymce').text() );
    
        url = $('#form').attr("action");
        formData = $('#form').serializeArray();

        $.post(url, formData).done(function (data) {
        if(data == 1){
            alert('success');
            location.reload();
        }else{
            alert('error');
        }
    });
  }
  </script>

