    
    
    <div class="container-login">
    <div class="img"></div>
    <div class="login-content">
       	
        <form action="<?php echo $controller ;?>" method="post" id="form" >
            <h2 class="title">Welcome to ServeWise</h2>
            <div class="input-div one">
              <div class="i">
                <i class="fa fa-user"></i>
              </div>
              <div class="div">
                <h5>E-mail</h5>
                <input type="text" name="email" class="input" required />
              </div>
            </div>
            <div class="input-div pass">
              <div class="i">
                <i class="fa fa-lock"></i>
              </div>
              <div class="div">
                <h5>Password</h5>
                <input type="password" name="password" class="input" required />
              </div>
            </div>
            <div class="login-f-s">
              <a href="?page=signup_dashboard" style='text-align: center;' >Not Registered Yet?</a>
              <a href="?page=forgot_dashboard" style='text-align: center;'>Forgot Password?</a>
            </div>
                  <label class='bg-danger'><?php 
				if(isset($_GET["message"])){
				echo $_GET['message'];
				}
				?></label>
            <input type="button" class="btn-login" name="loginbtn" value="Login" onclick="submitForm()" />
          </form>
             
    </div>
    </div>
    
<script>
	function submitForm(form){
		
    var url = $('#form').attr("action");
		
    var formData = $('#form').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
			        window.location.replace("?page=dashboard");
		}else{
			alert('signin failed');
		}
    });
}
</script>

