 <section class="login-main">
    <div class="logincontent">
        <div class="login-section-right">
            <div class="login-heading">Welcome to ServeWise</div>
            <a herf="#" class="login-btn-google"><i class="fa fa-google" aria-hidden="true"></i> Google</a>
            <a herf="#" class="login-btn-facebook"><i class="fa fa-facebook" aria-hidden="true"></i>Facebook</a>
            <a herf="#" class="login-btn-twitter"><i class="fa fa-twitter" aria-hidden="true"></i>Twitter</a>
            <div class="login-slipt"><div class="span-1"></div>OR LOGIN WITH EMAIL<div class="span-2"></div></div>
            <form action="<?php echo $controller ;?>" method="post" id="form" class="login-form">
                <input class="login-email" name="email" type="text" required>
                <input class="login-password" name="password" type="password" required>
                <div class="form-lower-content">
                    <div class="radio">
                        <input type="checkbox">
                        <label>Keep me logged in</label>
                    </div>
                    <a href="?page=forgot_dashboard">Forget Password</a>
                </div>
                <label class='bg-danger'><?php 
				if(isset($_GET["message"])){
				echo $_GET['message'];
				}
				?></label>
                <div class="login-btn-login">
                    <input class="login-btn" type="button" name="loginbtn" value="Log In" onclick="submitForm()">
                </div>
            </form>
            <div class="login-nav-signup">
                <p>Don't have an account yet? <a href="?page=signup_dashboard">Sign up</a></p>
            </div>
        </div>
        <div class="login-section-left">
            <div class="login-section-upper">
                <div class="login-upper-heading"><a href="#"><img src="<?php echo $image;?>servewis_logo.png" alt="logo"></a></div>
                <div class="login-upper-shap1"></div>
                <div class="login-upper-shap2"><img src="<?php echo $image;?>laptop.png" alt="123"></div>
            </div>
            <div class="login-section-upper"></div>
        </div>
    </div>
</section>

<script>
	function submitForm(form){
		
    var url = $('#form').attr("action");
		
    var formData = $('#form').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
			        window.location.replace("?page=dashboard");
		}else{
			alert('signin failed');
		}
    });
}
</script>



<!--     
    
    <div class="container-login">
    <div class="img"></div>
    <div class="login-content">
       	
        <form action="<?php echo $controller ;?>" method="post" id="form" >
            <h2 class="title">Welcome to ServeWise</h2>
            <div class="input-div one">
              <div class="i">
                <i class="fa fa-user"></i>
              </div>
              <div class="div">
                <h5>E-mail</h5>
                <input type="text" name="email" class="input" required />
              </div>
            </div>
            <div class="input-div pass">
              <div class="i">
                <i class="fa fa-lock"></i>
              </div>
              <div class="div">
                <h5>Password</h5>
                <input type="password" name="password" class="input" required />
              </div>
            </div>
            <div class="login-f-s">
              <a href="?page=signup_dashboard" style='text-align: center;' >Not Registered Yet?</a>
              <a href="?page=forgot_dashboard" style='text-align: center;'>Forgot Password?</a>
            </div>
                  <label class='bg-danger'><?php 
                  if(isset($_GET["message"])){
                  echo $_GET['message'];
                  }
                  ?></label>
            <input type="button" class="btn-login" name="loginbtn" value="Login" onclick="submitForm()" />
          </form>
             
    </div>
    </div>
    
<script>
	function submitForm(form){
		
    var url = $('#form').attr("action");
		
    var formData = $('#form').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
			        window.location.replace("?page=dashboard");
		}else{
			alert('signin failed');
		}
    });
}
</script>
 -->
