<script src="https://apis.google.com/js/platform.js" async defer></script>
<meta name="google-signin-client_id" content="982422029890-q28rmfama5olf3kgtjond6qkkebscebf.apps.googleusercontent.com">
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v9.0&appId=229595958647533&autoLogAppEvents=1" nonce="dEzEjn6Z"></script>
<section class="login-main">
    <div class="logincontent">
        <div class="login-section-right">
            <div class="login-heading">Welcome to ServeWise</div>
            <a herf="#" class="login-btn-google g-signin2" data-onsuccess="onSignIn"><i class="fa fa-google" aria-hidden="true"></i> Google</a>
            <div class="fb-login-button" data-width="" data-size="large" data-button-type="login_with" data-layout="default" data-auto-logout-link="true" data-use-continue-as="true"></div>
            <a herf="#" class="login-btn-facebook"><i class="fa fa-facebook" aria-hidden="true"></i>Facebook</a>
            <a herf="#" class="login-btn-twitter"><i class="fa fa-twitter" aria-hidden="true"></i>Twitter</a>
            <div class="login-slipt"><div class="span-1"></div>OR LOGIN WITH EMAIL<div class="span-2"></div></div>
            <form action="<?php echo $controller ;?>" method="post" id="form" class="login-form">
                <input class="login-email" name="email" type="text" required>
                <input class="login-password" name="password" type="password" required>
                <div class="form-lower-content">
                    <div class="radio">
                        <input type="checkbox">
                        <label>Keep me logged in</label>
                    </div>
                    <a href="?page=forgot_dashboard">Forget Password</a>
                </div>
                <label class='bg-danger'><?php 
				if(isset($_GET["message"])){
				echo $_GET['message'];
				}
				?></label>
                <div class="login-btn-login">
                    <input class="login-btn" type="button" name="loginbtn" value="Log In" onclick="submitForm()">
                </div>
            </form>
            <div class="login-nav-signup">
                <p>Don't have an account yet? <a href="?page=signup_dashboard">Sign up</a></p>
            </div>
        </div>
        <div class="login-section-left">
            <div class="login-section-upper">
                <div class="login-upper-heading"><a href="#"><img src="<?php echo $image;?>servewis_logo.png" alt="logo"></a></div>
                <div class="login-upper-shap1"></div>
                <div class="login-upper-shap2"><img src="<?php echo $image;?>laptop.png" alt="123"></div>
            </div>
            <div class="login-section-upper"></div>
        </div>
    </div>
</section>

<script>
function onSignIn(googleUser) {
  var profile = googleUser.getBasicProfile();
  console.log('ID: ' + profile.getId()); // Do not send to your backend! Use an ID token instead.
  console.log('Name: ' + profile.getName());
  console.log('Image URL: ' + profile.getImageUrl());
  console.log('Email: ' + profile.getEmail()); // This is null if the 'email' scope is not present.
}


  window.fbAsyncInit = function() {
    FB.init({
      appId      : '229595958647533',
      cookie     : true,
      xfbml      : true,
      version    : 'v9.0'
    });
      
    FB.AppEvents.logPageView();   
      
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "https://connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
   FB.getLoginStatus(function(response) {
    statusChangeCallback(response);
  });


	function submitForm(form){
		
    var url = $('#form').attr("action");
		
    var formData = $('#form').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
			        window.location.replace("?page=dashboard");
		}else{
			alert('signin failed');
		}
    });
}
</script>



<!--     
    
    <div class="container-login">
    <div class="img"></div>
    <div class="login-content">
       	
        <form action="<?php echo $controller ;?>" method="post" id="form" >
            <h2 class="title">Welcome to ServeWise</h2>
            <div class="input-div one">
              <div class="i">
                <i class="fa fa-user"></i>
              </div>
              <div class="div">
                <h5>E-mail</h5>
                <input type="text" name="email" class="input" required />
              </div>
            </div>
            <div class="input-div pass">
              <div class="i">
                <i class="fa fa-lock"></i>
              </div>
              <div class="div">
                <h5>Password</h5>
                <input type="password" name="password" class="input" required />
              </div>
            </div>
            <div class="login-f-s">
              <a href="?page=signup_dashboard" style='text-align: center;' >Not Registered Yet?</a>
              <a href="?page=forgot_dashboard" style='text-align: center;'>Forgot Password?</a>
            </div>
                  <label class='bg-danger'><?php 
                  if(isset($_GET["message"])){
                  echo $_GET['message'];
                  }
                  ?></label>
            <input type="button" class="btn-login" name="loginbtn" value="Login" onclick="submitForm()" />
          </form>
             
    </div>
    </div>
    
<script>
	function submitForm(form){
		
    var url = $('#form').attr("action");
		
    var formData = $('#form').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
			        window.location.replace("?page=dashboard");
		}else{
			alert('signin failed');
		}
    });
}
</script>
 -->
