<div class="wrapper">
		<div class="row">
			<div class="newsletter-head-dashboard">
            <h1 data-aos="fade-right"data-aos-duration="1500">News Letter</h1>
        </div>
        <div class="newsletter-main" data-aos="zoom-in-up" data-aos-duration="600">
            <div class="newsletter-head"></div>
            <form action="<?php echo $controller;?>" id='form'>
                <div class="newsletter-form-1-1">
                    <div class="newsletter-form-1">
                        <label>Email (User)</label>
                        <input type="text" value="<?php echo $_SESSION["logIn"]?>">
                    </div>
                    <div class="newsletter-form-2">
                        <label>Email (Subcribers)</label>
                        <select name="email_sub" id="">
                            <option value="1">bunniqureshi007@gmail.com</option>
                            <option value="2">zubairayub@gmail.com</option>
                            <option value="3">daniyal88@gmail.com</option>
                        </select>
                    </div>
                </div>
                <div class="newsletter-form-3">
                    <label>Newsletter Subject :</label>
                    <input type="text" name="news_subject">
                </div>
                <div class="newsletter-form-4">
                    <label>Newsletter Content :</label>
                    <textarea class="tinymce" name="news_content" id="myTextArea"></textarea>
                </div>

                <div class="newsletter-btn">
                    <input type="button" value="SEND" onclick="submitForm()">
                </div>
            </form>
        </div>
</div>
</div>

<script>
  function submitForm(form){
    
    var url = $('#form').attr("action");
    var myContent = tinymce.get("myTextArea").getContent();
      $('#myTextArea').html(myContent);
    
    var formData = $('#form').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
      alert('success');
    }else{
      alert('error');
    }
    });
}
</script>