<div class="wrapper">
    <div class="row">
        <div class="order-dashboard-main">
            <h1 data-aos="fade-right"data-aos-duration="1500">Order Detail</h1>
        </div>
        <div class="orderview-dashboard">
            <div class="order-view-box" data-aos="zoom-in-up" data-aos-duration="600">
                <div class="order-view-upper">
                    <div class="order-view-upper-left">
                        <p><?= $customer_name ?> </p>
                        <p><?= $customer_email ?></p>
                        <p><?= $customer_phone ?></p>
                        <p><?= $customer_address ?></p>
                        <p><?= $customer_country ?></p>
                    </div>
                    <div class="order-view-upper-right">
                        <div class="order-view-upper-right1">
                            <label>Order #</label>
                            <p><?= $order_id ?></p>
                        </div>
                        <div class="order-view-upper-right1">
                            <label>Order Status</label>
                            <p><?= $order_status ?></p>
                        </div>
                        <div class="order-view-upper-right1">
                            <label>Order Date</label>
                            <p><?= $datetime ?></p>
                        </div>
                        <div class="order-view-upper-right1">
                            <label>Total Amount</label>
                            <p><?= $amount ?> $</p>
                        </div>
                        <div class="order-view-upper-right1">
                            <label>Payment Method</label>
                            <p>Flutter</p>
                        </div>
                    </div>
                </div>
                <div class="order-view-table">
                <form action="">
                    <table>
                        <tr>
                            <th>Serial.No</th>
                            <th>Photo</th>
                            <th>Describtion</th>
                            <th>Qty</th>
                            <th>Price</th>
                           
                        </tr>
                        <?php  
                        $count  = 1;
                        $counter = 0;
                            foreach ($orderdata as $key => $value) {
                               $images = getproductsimages($value['product_id']);
                                $product_data = getproductnamebyid($value['product_id']);
                         ?>
<tr>
                            <td><?= $count ?></td>
                            <td><img style='width: 100px; height: 100px;'  src='<?= $product_directory.$images[0]['image_path'] ?>'></td>
                            <td><?= $product_data[0]['name'] ?><span>small</span></td>
                            <td><?= $value['product_quantity'] ?></td>
                            <td><?= $product_data[0]['price']?></td>
                           
                        </tr>

                        <?php 
                        $count ++;  
                         $counter ++;    
                            }
                        ?>
                        
                    </table>
                </form>
                </div>
                <div class="order-view-total">
                   <!--  <div class="order-view-total1">
                        <label>Sub Total :</label>
                        <p>20$</p>
                    </div>
 -->                   <!--  <div class="order-view-total1">
                        <label>Tax :</label>
                        <p>0</p>
                    </div>
                    <div class="order-view-total1">
                        <label>Shipping :</label>
                        <p>10$</p>
                    </div> -->
                    <div class="order-view-total1">
                        <label>Total :</label>
                        <p><?= $amount ?> $</p>
                    </div>
                </div>
                <div class="order-view-btn">
                    <input type="button" value="Print">
                </div>
            </div>
        </div>
    </div>
</div>