<div class="wrapper">
    <div class="row">
        <div class="order-dashboard-main">
        <h1 data-aos="fade-right"data-aos-duration="1500">All Order</h1>
        <form data-aos="fade-left"data-aos-duration="1500">
            <input type="text">
            <input class="s-btn" type="button" value="Search">
        </form>
    </div>
    <div class="order-table-main" data-aos="zoom-in-up" data-aos-duration="600">
        <form action="">
            <table>
                <tr>
                    <th>Serial.No</th>
                    <th>Order Code</th>
                    <th>No. of Product</th>
                    <th>Customer</th>
                    <th>Amount</th>
                    <th>Delivery Status</th>
                    <th>Payment Status</th>
                    <th>Option</th>
                </tr>
                <tr>
                    <td>1</td>
                    <td>0001</td>
                    <td>01</td>
                    <td>Griffin</td>
                    <td>20$</td>
                    <td>Pending</td>
                    <td>Unpaid</td>
                    <td class="option">
                        <a href="?page=orderview_dashboard">
                        <i class="fa fa-eye" aria-hidden="true"></i> view
                        </a>
                        <a href="#">
                            <i class="fa fa-trash" aria-hidden="true"></i> Remove
                        </a>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>
</div>