<div class="wrapper">
    <div class="row">
        <div class="order-dashboard-main">
        <h1 data-aos="fade-right"data-aos-duration="1500">All Order</h1>
        <form data-aos="fade-left"data-aos-duration="1500">
            <input type="text">
            <input class="s-btn" type="button" value="Search">
        </form>
    </div>
    <div class="order-table-main" data-aos="zoom-in-up" data-aos-duration="600">
        <form action="">
            <table>
                <tr>
                    <th>Serial.No</th>
                    <th>Order Code</th>
                    <th>No. of Product</th>
                    <th>Customer</th>
                    <th>Amount</th>
                    <th>Delivery Status</th>
                    <th>Payment Status</th>
                    <th>Option</th>
                </tr>
                
                    <?php  
                        if (!empty($data)){
                            $count = 1;
                    foreach ($data as $key => $value) {  
                            $product_name = getproductnamebyid($value['product_id']);
                            $order_status = getorderstatus($value['op_id']);
                            $payment_status = getordersalestatus($order_status[0]['orders_id']);
                        ?> 
                        <tr>
                        <td><?php echo $count;?></td>
                    <td><?php echo $value['op_id'];?></td>
                    <td><?php echo $value['quantity'];?></td>
                    <td><?php echo $product_name[0]['name'] ;?></td>
                    <td><?php echo $value['totalprice'];?></td>
                    <td><?php echo $order_status[0]['order_status'];?></td>
                    <td><?php echo $payment_status[0]['sale_status']; ?></td>
                    <td class="option">
                        <a href="?page=orderview_dashboard">
                        <i class="fa fa-eye" aria-hidden="true"></i> view
                        </a>
                        <a href="#">
                            <i class="fa fa-trash" aria-hidden="true"></i> Remove
                        </a>
                    </td>
                </tr>
                       
                    <?php  
                    $count ++;
                } }  ?>
                    
               
            </table>
        </form>
    </div>
</div>
</div>