<div class="wrapper">
    <div class="row">
        <div class="order-dashboard-main">
        <h1 data-aos="fade-right"data-aos-duration="1500">All Order</h1>
        <form data-aos="fade-left"data-aos-duration="1500">
            <input type="text">
            <a class="s-btn" href="#">
                <i class="fa fa-search" aria-hidden="true">Search</i>
            </a>
        </form>
    </div>
    <div class="order-table-main" data-aos="zoom-in-up" data-aos-duration="600">
        <form action="">
            <table>
                <tr>
                    <th>Serial.No</th>
                    <th>Order Code</th>
                 
                    <th>Customer</th>
                    <th>Amount</th>
                    <th>Delivery Status</th>
                    <th>Payment Status</th>
                    <th>Option</th>
                </tr>
                
                    <?php  

                        if (!empty($data)){
                            $count = 1;
                            
                    foreach ($data as $key => $value) { 
                           $orderdata =  getordersdetailsbyid('',$value['id'],$value['branch_id']);
                           if(!empty($orderdata)){
                           $product_data = getproductnamebyid($orderdata[0]['product_id']);
                           $customer_data = getuserinfo($value['user_id'],'');
                           $invoice_datails = getorderamountbyorderid('',$value['id']);
                          $status_datails =  getorderstatusbyorderid('',$value['id']);
                           if($invoice_datails[0]['status'] == 0){
                            $status_payment = 'Unpaid';

                           }else{

                           $status_payment = 'Paid';

                           }


                           if($customer_data[0]['first_name'] == ''){
$customer_name =   'Guest User' ;

                           }else{

                          $customer_name =   $customer_data[0]['first_name'] .' '. $customer_data[0]['last_name'] ;
                           }
                          ?> 
                        <tr>
                        <td><?php echo $count;?></td>
                    <td><?php echo $value['id'];?></td>
                   
                    <td><?php echo  $customer_name ;?></td>
                    <td><?php echo $invoice_datails[0]['amount'];?></td>
                    <td><?php echo $status_datails[0]['title'];?></td>
                    <td><?php echo $status_payment; ?></td>
                    <td class="option">
                        <a href="?page=orderview_dashboard&order_id=<?= $value['id'] ?>&user_id=<?= $value['user_id'] ?>&date=<?= $value['datetime']?>">
                        <i class="fa fa-eye" aria-hidden="true"></i> view
                        </a>
                        <a href="#">
                            <i class="fa fa-trash" aria-hidden="true"></i> Remove
                        </a>
                    </td>
                </tr>
                       
                    <?php  
                    $count ++;
                } } } ?>
                    
               
            </table>
        </form>
    </div>
</div>
</div>