<div class="wrapper">
    <div class="row">
        <div class="order-dashboard-main">
            <h1 data-aos="fade-right"data-aos-duration="1500">Order Detail</h1>
        </div>
        <div class="orderview-dashboard">
            <div class="order-view-box" data-aos="zoom-in-up" data-aos-duration="600">
                <div class="order-view-upper">
                    <div class="order-view-upper-left">
                        <p>Muzzamil</p>
                        <p>bunniqureshi007@gmail.com</p>
                        <p>+92-0000000000</p>
                        <p>abc flat, xyz street , 123 state.</p>
                        <p>Pakistan</p>
                    </div>
                    <div class="order-view-upper-right">
                        <div class="order-view-upper-right1">
                            <label>Order #</label>
                            <p>12345</p>
                        </div>
                        <div class="order-view-upper-right1">
                            <label>Order Status</label>
                            <p>Pending</p>
                        </div>
                        <div class="order-view-upper-right1">
                            <label>Order Date</label>
                            <p>05/01/2021 03:00 PM</p>
                        </div>
                        <div class="order-view-upper-right1">
                            <label>Total Amount</label>
                            <p>20$</p>
                        </div>
                        <div class="order-view-upper-right1">
                            <label>Payment Method</label>
                            <p>Cash on Delivery</p>
                        </div>
                    </div>
                </div>
                <div class="order-view-table">
                <form action="">
                    <table>
                        <tr>
                            <th>Serial.No</th>
                            <th>Photo</th>
                            <th>Describtion</th>
                            <th>Delivery Type</th>
                            <th>Qty</th>
                            <th>Price</th>
                            <th>Total</th>
                        </tr>
                        <tr>
                            <td>1</td>
                            <td></td>
                            <td>Fashion Nova <span>small</span></td>
                            <td>Home Delivery</td>
                            <td>1</td>
                            <td>20$</td>
                            <td>20$</td>
                        </tr>
                    </table>
                </form>
                </div>
                <div class="order-view-total">
                    <div class="order-view-total1">
                        <label>Sub Total :</label>
                        <p>20$</p>
                    </div>
                    <div class="order-view-total1">
                        <label>Tax :</label>
                        <p>0</p>
                    </div>
                    <div class="order-view-total1">
                        <label>Shipping :</label>
                        <p>10$</p>
                    </div>
                    <div class="order-view-total1">
                        <label>Total :</label>
                        <p>30$</p>
                    </div>
                </div>
                <div class="order-view-btn">
                    <input type="button" value="Print">
                </div>
            </div>
        </div>
    </div>
</div>