<div class="wrapper">
    <div class="row">
        <div class="dashboard-footer">
            <h1 data-aos="fade-right" data-aos-duration="2000" >Partners</h1>
        </div>
        <div class="dashboard-footer-about" data-aos="zoom-out-right" data-aos-duration="1000">
            <form action="<?= $controller; ?>" class="d-footer-logo-about" id="formFAQ">
                <input type="hidden" name="formFAQ">
                <div class="dashboard-footer-about">
                    <div class="footer-about-upload-label">
                        <label for="">FAQ Question ?</label>
                    </div>
                    <div class="footer-about-upload-content">
                        <input type="text" name='partner_faq'>
                    </div>
                    <div class="footer-about-upload-label">
                        <label for="">FAQ Answer :</label>
                    </div>
                    <div class="footer-about-upload-content">
                        <textarea name="partner_faq_ans" id="myTextAreaSec" class="tinymce" name='faq_answers'></textarea>
                    </div>
                </div>
                <div class="dashboard-footer-about-btn">
                    <input type="button" value="Upadate" onclick="submitFormFAQ()">
                </div>
            </form>
        </div>
        <div class="about-us-dashboard-main">
            <form >
                <label>FAQ Table</label>
                <table>
                    <tr>
                        <th>Serial No.</th>
                        <th>FAQ Question</th>                
                        <th>Option</th>                
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>What is ServeWise?</td>
                        <td>
                            <a href="#">
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit
                            </a>
                            <a href="#">
                                <i class="fa fa-trash" aria-hidden="true"></i> Remove
                            </a>
                        </td>
                    </tr>                
                </table>
            </form>
        </div>
        <div class="about-us-dashboard-main2">
        <div class="dashboard-footer-section-2">
            <div class="dashboard-footer-contact" data-aos="fade-up-right" data-aos-duration="1000">
                <h1>Packages</h1>
                <form action="<?= $controller; ?>" class="d-footer-logo-contact" id="pckgForm">
                    <input type="hidden" name="pckgForm">
                    <div class="dashboard-footer-contact-add">
                        <div class="footer-contact-add-head">
                            <label for="">Package Name </label>
                        </div>
                        <div class="footer-contact-add-input">
                            <input type='text' name="partner_package_name" />
                        </div>
                    </div>
                    <div class="dashboard-footer-contact-phone">
                        <div class="footer-contact-phone-head">
                            <label for="">Package Price</label>
                        </div>
                        <div class="footer-contact-phone-input">
                            <input type='text' name="partner_package_price" />
                        </div>
                    </div>
                    <div class="dashboard-footer-contact-phone">
                        <div class="footer-contact-phone-head">
                            <label for="">Package Heading</label>
                        </div>
                        <div class="footer-contact-phone-input">
                            <input type='text' name="partner_package_heading" />
                        </div>
                    </div>
                    <div class="dashboard-footer-contact-email">
                        <div class="footer-contact-email-head">
                            <label for="">Package Description</label>
                        </div>
                        <div class="footer-contact-email-input">
                            <textarea class="tinymce" id="myTextAreaDis" name="partner_package_desc"></textarea>
                        </div>
                    </div>
                    <div class="dashboard-footer-contact-btn">
                        <input type="button" value="Upadate" onclick="submitFormPckg()">
                    </div>
                </form>
            </div>
        </div>
        <div class="dashboard-footer-bottom" data-aos="fade-left" data-aos-duration="1000" >
            <form action="<?= $controller; ?>" class="dashboard-footer-bottom-content" id="heroForm">
                <input type="hidden" name="heroForm">
                <div class="d-footer-copyright">
                    <div class="d-footer-copyright-head">
                        <label>Partner Hero Head</label>
                    </div>
                    <div class="d-footer-copyright-input">
                        <input type="text" name="partner_hero_heading">
                    </div>
                    <div class="d-footer-copyright-head">
                        <label>Partner Hero Discribtion</label>
                    </div>
                    <div class="d-footer-copyright-input">
                        <textarea class="tinymce" id="myTextArea" name="partner_discribtion"></textarea>
                    </div>
                </div>
                <div class="d-footer-social-media">
                    <div class="d-footer-social-links">
                        <div class="footer-social-link-icon">
                            <input type="button" value="Update" onclick="submitFormHero()">
                        </div>
                    </div>
                </div>
            </form>
        </div>
        </div>
        <div class="about-us-dashboard-main">
            <form >
                <label>Package Table</label>
                <table>
                    <tr>
                        <th>Serial No.</th>
                        <th>Package Name</th>
                        <th>Package Price</th>                
                        <th>Package Heading</th>                
                        <th>Option</th>                
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>gold</td>
                        <td>20$</td>
                        <td>ServeWise Golden Package</td>
                        <td>
                            <a href="#">
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit
                            </a>
                            <a href="#">
                                <i class="fa fa-trash" aria-hidden="true"></i> Remove
                            </a>
                        </td>
                    </tr>                
                </table>
            </form>
        </div>
    </div>
</div>
</div>
<script>
  function submitFormFAQ(form){
    var myContent = tinymce.get("myTextAreaSec").getContent();
      $('#myTextAreaSec').html(myContent);
    var url = $('#formFAQ').attr("action");
    
    var formData = $('#formFAQ').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
      alert('success');
    }else{
      alert('error');
    }
    });
}
function submitFormPckg(form){
    var myContent = tinymce.get("myTextAreaDis").getContent();
      $('#myTextAreaDis').html(myContent);
    var url = $('#pckgForm').attr("action");
    
    var formData = $('#pckgForm').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
      alert('success');
    }else{
      alert('error');
    }
    });
}
function submitFormHero(form){
    var myContent = tinymce.get("myTextArea").getContent();
      $('#myTextArea').html(myContent);
    var url = $('#heroForm').attr("action");
    
    var formData = $('#heroForm').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
      alert('success');
    }else{
      alert('error');
    }
    });
}

</script>


