<div class="wrapper">
    <div class="row">
        <div class="payment-method-dashboard-main">
            <h1 data-aos="fade-right"data-aos-duration="1500">Payment Method</h1>
        </div>
    </div>
    <div class="pay-me-dashboard">
        <div class="pay-me-box" data-aos="fade-right"data-aos-duration="900">
            <div class="pay-me-box-head">Paypal Credential</div>
            <div class="pay-me-box-dis">
                <div class="pay-me-dis-1">
                    <div class="pay-me-dis-head">Paypal Client Id</div>
                    <div class="pay-me-dis-input">
                        <input type="text">
                    </div>
                </div>
                <div class="pay-me-dis-1">
                    <div class="pay-me-dis-head">Paypal Client Secret</div>
                    <div class="pay-me-dis-input">
                        <input type="text">
                    </div>
                </div>
                <div class="pay-me-dis-1">
                    <div class="pay-me-dis-head">Paypal Sandbox Mode</div>
                    <div class="pay-me-dis-input">
                        <label class="switch">
                            <input type="checkbox">
                            <span class="slider round"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="pay-me-box-btn">
                <input type="button" value="SAVE">
            </div>
        </div>
        <div class="pay-me-box" data-aos="fade-left"data-aos-duration="900">
            <div class="pay-me-box-head">Sslcommerz Credential</div>
            <div class="pay-me-box-dis">
                <div class="pay-me-dis-1">
                    <div class="pay-me-dis-head">Sslcz Store Id</div>
                    <div class="pay-me-dis-input">
                        <input type="text">
                    </div>
                </div>
                <div class="pay-me-dis-1">
                    <div class="pay-me-dis-head">Sslcz store password</div>
                    <div class="pay-me-dis-input">
                        <input type="text">
                    </div>
                </div>
                <div class="pay-me-dis-1">
                    <div class="pay-me-dis-head">Sslcommerz Sandbox Mode</div>
                    <div class="pay-me-dis-input">
                        <label class="switch">
                            <input type="checkbox">
                            <span class="slider round"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="pay-me-box-btn" >
                <input type="button" value="SAVE">
            </div>
        </div>
        <div class="pay-me-box" data-aos="fade-right"data-aos-duration="900">
            <div class="pay-me-box-head">Stripe Credential</div>
            <div class="pay-me-box-dis">
                <div class="pay-me-dis-1">
                    <div class="pay-me-dis-head">Stripe Key</div>
                    <div class="pay-me-dis-input">
                        <input type="text">
                    </div>
                </div>
                <div class="pay-me-dis-1">
                    <div class="pay-me-dis-head">Stripe Secret</div>
                    <div class="pay-me-dis-input">
                        <input type="text">
                    </div>
                </div>
            </div>
            <div class="pay-me-box-btn">
                <input type="button" value="SAVE">
            </div>
        </div>
        <div class="pay-me-box" data-aos="fade-left"data-aos-duration="900">
            <div class="pay-me-box-head">RazorPay Credential</div>
            <div class="pay-me-box-dis">
                <div class="pay-me-dis-1">
                    <div class="pay-me-dis-head">RAZOR KEY</div>
                    <div class="pay-me-dis-input">
                        <input type="text">
                    </div>
                </div>
                <div class="pay-me-dis-1">
                    <div class="pay-me-dis-head">RAZOR SECRET</div>
                    <div class="pay-me-dis-input">
                        <input type="text">
                    </div>
                </div>
            </div>
            <div class="pay-me-box-btn">
                <input type="button" value="SAVE">
            </div>
        </div>
        <div class="pay-me-box" data-aos="fade-right"data-aos-duration="900">
            <div class="pay-me-box-head">Instamojo Credential</div>
            <div class="pay-me-box-dis">
                <div class="pay-me-dis-1">
                    <div class="pay-me-dis-head">API KEY</div>
                    <div class="pay-me-dis-input">
                        <input type="text">
                    </div>
                </div>
                <div class="pay-me-dis-1">
                    <div class="pay-me-dis-head">AUTH TOKEN</div>
                    <div class="pay-me-dis-input">
                        <input type="text">
                    </div>
                </div>
                <div class="pay-me-dis-1">
                    <div class="pay-me-dis-head">Instamojo Sandbox Mode</div>
                    <div class="pay-me-dis-input">
                        <label class="switch">
                            <input type="checkbox">
                            <span class="slider round"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="pay-me-box-btn" >
                <input type="button" value="SAVE">
            </div>
        </div>
        <div class="pay-me-box" data-aos="fade-left"data-aos-duration="900">
            <div class="pay-me-box-head">PayStack Credential</div>
            <div class="pay-me-box-dis">
                <div class="pay-me-dis-1">
                    <div class="pay-me-dis-head">PUBLIC KEY</div>
                    <div class="pay-me-dis-input">
                        <input type="text">
                    </div>
                </div>
                <div class="pay-me-dis-1">
                    <div class="pay-me-dis-head">SECRET KEY</div>
                    <div class="pay-me-dis-input">
                        <input type="text">
                    </div>
                </div>
                <div class="pay-me-dis-1">
                    <div class="pay-me-dis-head">MERCHANT EMAIL</div>
                    <div class="pay-me-dis-input">
                        <input type="text">
                    </div>
                </div>
            </div>
            <div class="pay-me-box-btn">
                <input type="button" value="SAVE">
            </div>
        </div>
        <div class="pay-me-box" data-aos="fade-right"data-aos-duration="900">
            <div class="pay-me-box-head">VoguePay Credential</div>
            <div class="pay-me-box-dis">
                <div class="pay-me-dis-1">
                    <div class="pay-me-dis-head">MERCHANT ID</div>
                    <div class="pay-me-dis-input">
                        <input type="text">
                    </div>
                </div>
                <div class="pay-me-dis-1">
                    <div class="pay-me-dis-head">Sandbox Mode</div>
                    <div class="pay-me-dis-input">
                        <label class="switch">
                            <input type="checkbox">
                            <span class="slider round"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="pay-me-box-btn">
                <input type="button" value="SAVE">
            </div>
        </div>
        <div class="pay-me-box" data-aos="fade-left"data-aos-duration="900">
            <div class="pay-me-box-head">Payhere Credential</div>
            <div class="pay-me-box-dis">
                <div class="pay-me-dis-1">
                    <div class="pay-me-dis-head">PAYHERE MERCHANT ID</div>
                    <div class="pay-me-dis-input">
                        <input type="text">
                    </div>
                </div>
                <div class="pay-me-dis-1">
                    <div class="pay-me-dis-head">PAYHERE SECRET</div>
                    <div class="pay-me-dis-input">
                        <input type="text">
                    </div>
                </div>
                <div class="pay-me-dis-1">
                    <div class="pay-me-dis-head">PAYHERE CURRENCY</div>
                    <div class="pay-me-dis-input">
                        <input type="text">
                    </div>
                </div>
                <div class="pay-me-dis-1">
                    <div class="pay-me-dis-head">Payhere Sandbox Mode</div>
                    <div class="pay-me-dis-input">
                        <label class="switch">
                            <input type="checkbox">
                            <span class="slider round"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="pay-me-box-btn">
                <input type="button" value="SAVE">
            </div>
        </div>
        <div class="pay-me-box" data-aos="fade-left"data-aos-duration="900">
            <div class="pay-me-box-head">Ngenius Credential</div>
            <div class="pay-me-box-dis">
                <div class="pay-me-dis-1">
                    <div class="pay-me-dis-head">NGENIUS OUTLET ID</div>
                    <div class="pay-me-dis-input">
                        <input type="text">
                    </div>
                </div>
                <div class="pay-me-dis-1">
                    <div class="pay-me-dis-head">NGENIUS API KEY</div>
                    <div class="pay-me-dis-input">
                        <input type="text">
                    </div>
                </div>
                <div class="pay-me-dis-1">
                    <div class="pay-me-dis-head">NGENIUS CURRENCY</div>
                    <div class="pay-me-dis-input">
                        <input type="text">
                    </div>
                </div>
            </div>
            <div class="pay-me-box-btn">
                <input type="button" value="SAVE">
            </div>
        </div>
    </div>
</div>
