<div class="wrapper">
    <div class="row">
        <div class="payment-method-dashboard-main">
            <h1 data-aos="fade-right"data-aos-duration="1500">Payment Method</h1>
        </div>
    </div>
    <div class="pay-me-dashboard">
        <!-- Paypal Form start -->
        <form action="<?= $controller; ?>" id="paypalForm">
            <input type="hidden" name="paypalForm" value="Paypal Form">
            <div class="pay-me-box" data-aos="fade-right"data-aos-duration="900">
                <div class="pay-me-box-head">Flutter Wave Credential</div>
                <div class="pay-me-box-dis">
                    <div class="pay-me-dis-1">
                        <div class="pay-me-dis-head">Flutter Wave Public key</div>
                        <div class="pay-me-dis-input">
                            <input type="text" name="paypal_id" require>
                        </div>
                    </div>
                    <div class="pay-me-dis-1">
                        <div class="pay-me-dis-head">Flutter Wave Client Secret</div>
                        <div class="pay-me-dis-input">
                            <input type="text" name="paypal_secret" require>
                        </div>
                    </div>
                    <div class="pay-me-dis-1">
                        <div class="pay-me-dis-head">Flutter Wave Sandbox Mode</div>
                        <div class="pay-me-dis-input">
                            <label class="switch">
                                <input type="checkbox" name="paypal_mode">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="pay-me-box-btn">
                    <input type="button" value="SAVE" onclick="submitFormPaypal()">
                </div>
            </div>
        </form>
        <!-- Paypal Form end -->

        <!-- sslcommerz Form Start -->
        <form action="<?= $controller; ?>" id="sslczForm">
            <input type="hidden" name="sslczForm" value="Sslcommerz Form">
            <div class="pay-me-box" data-aos="fade-left"data-aos-duration="900">
                <div class="pay-me-box-head">Pesapal Credential</div>
                <div class="pay-me-box-dis">
                    <div class="pay-me-dis-1">
                        <div class="pay-me-dis-head">Pesapal Store Id</div>
                        <div class="pay-me-dis-input">
                            <input type="text" name="sslcz_store_id" require>
                        </div>
                    </div>
                    <div class="pay-me-dis-1">
                        <div class="pay-me-dis-head">Pesapal store password</div>
                        <div class="pay-me-dis-input">
                            <input type="text" name="sslcz_store_pass" require>
                        </div>
                    </div>
                    <div class="pay-me-dis-1">
                        <div class="pay-me-dis-head">Pesapal Sandbox Mode</div>
                        <div class="pay-me-dis-input">
                            <label class="switch">
                                <input type="checkbox" name="sslcz_mode">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="pay-me-box-btn" >
                    <input type="button" value="SAVE" onclick="submitFormSslcz()">
                </div>
            </div>
        </form>
        <!-- sslcommerz Form End -->

        <!-- Stripe Form Start -->
        <form action="<?= $controller; ?>" id="stripeForm">
            <input type="hidden" name="stripeForm" value="Stripe Form">
            <div class="pay-me-box" data-aos="fade-right"data-aos-duration="900">
                <div class="pay-me-box-head">Paystack Credential</div>
                <div class="pay-me-box-dis">
                    <div class="pay-me-dis-1">
                        <div class="pay-me-dis-head">Paystack Key</div>
                        <div class="pay-me-dis-input">
                            <input type="text" name="st_key" require>
                        </div>
                    </div>
                    <div class="pay-me-dis-1">
                        <div class="pay-me-dis-head">Paystack Secret</div>
                        <div class="pay-me-dis-input">
                            <input type="text" name="st_secret" require>
                        </div>
                    </div>
                </div>
                <div class="pay-me-box-btn">
                    <input type="button" value="SAVE" onclick="submitFormStripe()">
                </div>
            </div>
        </form>
        <!-- Stripe Form End -->

        <!-- RazorPay Form Start -->
        <form action="<?= $controller; ?>" id="razForm">
            <input type="hidden" name="razForm" value="RazorPay Form">
            <div class="pay-me-box" data-aos="fade-left"data-aos-duration="900">
                <div class="pay-me-box-head">mpesa Credential</div>
                <div class="pay-me-box-dis">
                    <div class="pay-me-dis-1">
                        <div class="pay-me-dis-head">mpesa KEY</div>
                        <div class="pay-me-dis-input">
                            <input type="text" name="raz_key" require>
                        </div>
                    </div>
                    <div class="pay-me-dis-1">
                        <div class="pay-me-dis-head">mpesa SECRET</div>
                        <div class="pay-me-dis-input">
                            <input type="text" name="raz_secret" require>
                        </div>
                    </div>
                </div>
                <div class="pay-me-box-btn">
                    <input type="button" value="SAVE" onclick="submitFormRaz()">
                </div>
            </div>
        </form>
        <!-- RazorPay Form End -->

     

    </div>
</div>

<script>

  function submitFormPaypal(form){
    
        url = $('#paypalForm').attr("action");
        formData = $('#paypalForm').serializeArray();

        $.post(url, formData).done(function (data) {
        if(data == 1){
            alert('success');
        }else{
            alert('error');
        }
    });
  }

  function submitFormSslcz(form){
    
        url = $('#sslczForm').attr("action");
        formData = $('#sslczForm').serializeArray();

        $.post(url, formData).done(function (data) {
        if(data == 1){
            alert('success');
        }else{
            alert('error');
        }
    });
  }
  
  function submitFormStripe(form){
    
    url = $('#stripeForm').attr("action");
    formData = $('#stripeForm').serializeArray();

    $.post(url, formData).done(function (data) {
    if(data == 1){
        alert('success');
    }else{
        alert('error');
    }
});
}

function submitFormRaz(form){
    
    url = $('#razForm').attr("action");
    formData = $('#razForm').serializeArray();

    $.post(url, formData).done(function (data) {
    if(data == 1){
        alert('success');
    }else{
        alert('error');
    }
});
}

function submitFormInsta(form){
    
    url = $('#instaForm').attr("action");
    formData = $('#instaForm').serializeArray();

    $.post(url, formData).done(function (data) {
    if(data == 1){
        alert('success');
    }else{
        alert('error');
    }
});
}

function submitFormPaystack(form){
    
    url = $('#paystackForm').attr("action");
    formData = $('#paystackForm').serializeArray();

    $.post(url, formData).done(function (data) {
    if(data == 1){
        alert('success');
    }else{
        alert('error');
    }
});
}

function submitFormVogue(form){
    
    url = $('#vogueForm').attr("action");
    formData = $('#vogueForm').serializeArray();

    $.post(url, formData).done(function (data) {
    if(data == 1){
        alert('success');
    }else{
        alert('error');
    }
});
}

function submitFormPayhere(form){
    
    url = $('#payhereForm').attr("action");
    formData = $('#payhereForm').serializeArray();

    $.post(url, formData).done(function (data) {
    if(data == 1){
        alert('success');
    }else{
        alert('error');
    }
});
}

function submitFormNgenius(form){
    
    url = $('#ngeniusForm').attr("action");
    formData = $('#ngeniusForm').serializeArray();

    $.post(url, formData).done(function (data) {
    if(data == 1){
        alert('success');
    }else{
        alert('error');
    }
});
}
</script>