<div class="wrapper">
    <div class="row">
        <div class="pickup-dashboard-main">
            <h1 data-aos="fade-right"data-aos-duration="1500">Pickup Point</h1>
            <!-- <form data-aos="fade-left"data-aos-duration="1500">
                <input type="text">
                <input class="s-btn" type="button" value="Search">
            </form> -->
        </div>
        <div class="pickup-table-main" data-aos="zoom-in-up" data-aos-duration="600">
            <form action="">
                <table>
                    <tr>
                        <th><?php 
echo getlang('','Serial.No',getlangcookie()); 
?>  </th>
                        <th><?php 
echo getlang('','Order Code',getlangcookie()); 
?>  </th>
                        <th><?php 
echo getlang('','Add Category',getlangcookie()); 
?>  </th>
                        <th><?php 
echo getlang('','Customer',getlangcookie()); 
?>  </th>
                        <th><?php 
echo getlang('','Amount',getlangcookie()); 
?>  </th>
                        <th><?php 
echo getlang('','Delivery Status',getlangcookie()); 
?>  </th>
                        <th><?php 
echo getlang('','Payment Status',getlangcookie()); 
?>  </th>
                        <th><?php 
echo getlang('','Option',getlangcookie()); 
?>  </th>
                    </tr>
                
                <?php  
                    if (!empty($data)){
                        $count = 1;
                foreach ($data as $key => $value) {  
                        $product_name = getproductnamebyid($value['product_id']);
                        $order_status = getorderstatus($value['op_id']);
                        $customer_name = getuserinfo($value['user_id']);
                        //  $payment_status = getordersalestatus($order_status[0]['orders_id']);
                        //var_dump($value);
                    ?> 
                    <tr>
                        <td><?= $count; ?></td>
                        <td>0001</td>
                        <td><?= $value['quantity']; ?></td>
                        <td><?= $customer_name[0]['first_name']; ?></td>
                        <td>20$</td>
                        <td>Pending</td>
                        <td>Unpaid</td>
                        <td class="option">
                            <a href="#">
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit
                            </a>
                            <a href="#">
                                <i class="fa fa-trash" aria-hidden="true"></i> Remove
                            </a>
                        </td>
                    </tr>
                       
                       <?php  
                       $count ++;
                   } }  ?>
                </table>
            </form>
        </div>
    </div>
</div>