<div class="wrapper">
    <div class="row">
        <div class="bluk-sms-dashboard">
            <h1 data-aos="fade-right"data-aos-duration="1500">Privacy Policy</h1>
        </div>
        <div class="bluk-sms-main" data-aos="zoom-in-up" data-aos-duration="600">
            <form action="<?= $controller; ?>" id="form"> 
                
                <div class="bluk-sms-form3">
                    <label>Write Your Privacy Policy</label>
                    <textarea class="tinymce"></textarea>
                </div>
                <div class="bluk-sms-btn">
                    <input type="button" value="Update" onclick="submitForm()">
                </div>
            </form>
        </div>
    </div>
</div>