<div class="wrapper">
    <div class="row">
        <div class="pickup-dashboard-main">
            <h1 data-aos="fade-right"data-aos-duration="1500">Product Stock</h1>
            <!-- <form data-aos="fade-left"data-aos-duration="1500">
                <input type="text">
                <input class="s-btn" type="button" value="Search">
            </form> -->
        </div>
        <div class="pickup-table-main" data-aos="zoom-in-up" data-aos-duration="600">
            <form action="">
                <table>
                    <tr>
                        <th>Serial.No</th>
                        <th>Product Name</th>
                   
                        <th>Purchase Price</th>
                        <th>Purchased from</th>
                        <th>Selling Price</th>
                        <th>Quantity purchased</th>
                        <th>Stock left</th> 
                        <th>Branch</th>
                        <th>Vendor</th>

                    </tr>
                    <?php
                    $count = 1;
                    foreach ($data as $key => $value) {
                  $branch_data =      getbranchbybranchid('',$value['vb_id']) ;
                  if(!empty($branch_data))
                  {
                    $branchname = $branch_data[0]['name'];
                    $vendor_data = getvendors('',$branch_data[0]['vendor_id'],'FALSE');
                    $vendor_name = $vendor_data[0]['name'];
                  }else{
                    $branchname = NULL;
                    $vendor_name = null;
                  }
                        ?>
                  
                  
 <tr>
                        <td><?= $count ?></td>
                        <td><?= $value['name'] ?></td>
                        <td><?= $value['purchase_price'] ?></td>
                        <td><?=  $vendor_name ?></td>
                        <td><?= $value['price'] ?></td>
                        <td><?= $value['quantity_purchase'] ?></td>
                         <td><?= $value['quantity'] ?></td>
                       <td> <?= $branchname; ?></td>
                        <td><?=  $vendor_name;?></td>
                    </tr>

                        <?php
                      $count ++;
                    }
                    ?>
                   
                    
                </table>
            </form>
        </div>
    </div>
</div>