
	  <?php //require $footer;
      ?>	
	<!-- main content -->
	<div class="wrapper">
        <h1 data-aos="fade-right"
     data-aos-duration="1500">Request Branch</h1>
		<div class="row">
			<div class="reqbranch-main" >
				<div class="container-content">
					<form class="req-form" action="<?php echo $controller ?>" method="post"  id="form" >
                    <div class="reqbranch-content" >	
                    <div class="req-choose-vendor" data-aos="fade-right" data-aos-duration="1000">
                            <label for="vendor">Choose a vendor:</label>

                            <select name="vendor" id="vendor">					
						<?php  foreach($getvendors as $vendorlist){

						?>
						
  							<option value="<?php echo $vendorlist["vendor_id"];?>"><?php echo $vendorlist["name"];  ?></option>
  							
						
						<?php 
                    } 
                        ?>
                        </select>
                        </div>
						<div class="user-detail1 req-n-c-e" data-aos="fade-left" data-aos-duration="1000">
                            <label>Name.</label>
                            <input name="name" type="text" >
                           
                            <label>contact No.</label>
                            <input name="contactno" type="number" >
							 <label>email id.</label>
                            <input name="email" type="text" >
                        </div>
                        <div class="user-detail1" data-aos="fade-up-left" data-aos-duration="1000">
                            <div class="req-address">
                                <div class="req-add-1">
                                    <label>Address.</label>
                                    <input name="address" type="text" >
                                </div>
                                <div class="req-add-1">
                                    <label>Address2.</label>
                                    <input name="address2" type="text" >
                                </div>
                            </div>
                            <div class="frmDronpDown">
        <div class="row">
            <label>Country:</label><br /> <select name="country"
                id="country-list" 
                onChange="getStateforbranch(this.value);">
                <option value disabled selected>Select Country</option>
<?php
foreach ($getcountries as $country) {
    ?>
<option value="<?php echo $country["id"]; ?>" ><?php echo $country["name"]; ?></option>
<?php
}
?>
</select>
        </div>
        <div class="row">
            <label>State:</label><br /> <select name="state"
                id="state-list" 
                onChange="getCityforbranch(this.value);">
                <option value="NULL" >Select State</option>
          
            </select>
        </div>
        <div class="row">
            <label>City:</label><br /> <select name="city"
                id="city-list" >
                <option value="NULL">Select City</option>
            </select>
        </div>
    </div>
							
                        </div >
						
						<div class="user-detail1 req-btn"  data-aos="zoom-in" data-aos-duration="1000">
							<input type="button" name="signupbtn" value="Request" onclick="submitForm()" >
						</div>
						
                    </div>
							</form>
                </div>
				
			</div>		
				
		</div>
	</div>
	<!-- end main content -->
<script>
  function submitForm(form){
    
    var url = $('#form').attr("action");
    
    var formData = $('#form').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
      alert('branch is created');
    }else if(data == 2){
alert('Branch for this city already created');
    }else if(data == 3){
alert('Branch for this state already created');
    }else if(data == 4){
        alert('Branch for this country already created');
    }else{
      alert('branch not created');
    }
    });
}
</script> 