<div class="wrapper">
    <div class="row">
        <div class="dashboard-footer">
            <h1 data-aos="fade-right" data-aos-duration="2000" >(Resturant) About Us</h1>
        </div>
        <div class="dashboard-footer-about" data-aos="zoom-out-right" data-aos-duration="1000">
            <form action="<?= $controller; ?>" class="d-footer-logo-about" id="form">
                <div class="dashboard-footer-about">
                    <div class="footer-about-upload-label">
                        <label for="">About Discribtion :</label>
                    </div>
                    <div class="footer-about-upload-content">
                        <textarea name="about_desc" class="tinymce"></textarea>
                    </div>
                </div>
                <div class="dashboard-footer-about-btn">
                    <input type="button" value="Upadate" onclick="submitForm()">
                </div>
            </form>
        </div>
    </div>
</div>

