<section class="signup-main">
    <div class="signupcontent">
        <div class="signup-section-right">
            <div class="login-section-upper">
                <div class="login-upper-heading"><a href="#"><img src="img/servewis_logo.png" alt="logo"></a></div>
                <div class="login-upper-shap1"></div>
                <div class="login-upper-shap2"><img src="img/signup-model.png" alt="123"></div>
            </div>
            <div class="login-section-upper"></div>
        </div>
        <div class="signup-section-left">
        <div class="login-heading">Get Started</div>
            <form class="login-form" action="<?php echo $controller ;?>" method="POST" id="form">
                <input class="login-email" type="text" name="email" placeholder="Your Email" required>
                <input class="login-password"  type="password" name="password" id="Password" placeholder="Password" required>
                <input class="login-password" name="confirm_Password" type="password" id="confirmPassword" placeholder="Confirm Password" required>
                <span id="message"></span>
                <div class="form-lower-content">
                    <div class="radio">
                        <input type="checkbox">
                        <label>I agreed to the <a href="#"> Terms of Services</a> & <a href="#">Privacy Policy</a>.</label>
                    </div>
                </div>
                <div class="login-btn-login">
                    <input class="login-btn" type="button" value="Sign up" name="signupbtn" onclick="submitForm()">
                </div>
            </form>
        </div>
    </div>
</section>


<script>
  function submitForm(form){
    
    var url = $('#form').attr("action");
    
    var formData = $('#form').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
       window.location.replace("?page=verification_dashboard");
    }else if (data== 0){
      alert('sign up failed');
    } else {
        alert("email already registered");
    }
    });
}
</script>


<!-- <?php //require $footer;
?>	
    <div class="container-varification">
    <div class="login-content">
        <form action="<?php echo $controller ;?>" method="POST" id="form">
            <h2 class="title">Sign Up</h2>
            <div class="input-div one">
              <div class="i">
                <i class="fa fa-user"></i>
              </div>
              <div class="div">
                <h5>E-mail</h5>
                <input type="text" name="email" class="input" required />
              </div>
            </div>
            <div class="input-div pass">
              <div class="i">
                <i class="fa fa-lock"></i>
              </div>
              <div class="div">
                <h5>Password</h5>
                <input type="password" class="input" name="password" id="password" required />
              </div>
              
            </div>
            <div class="input-div pass">
                <div class="i">
                  <i class="fa fa-unlock-alt"></i>
                </div>
                <div class="div">
                  <h5>Confirm Password</h5>
                  <input type="password" name="confirm_Password" class="input" id="confirmPassword" required />
                  <input type="hidden" name="type" class="input" id="confirmPassword" value="2" />
                </div>
            </div>
            <span id="message"></span>
           
            <input type="button" class="btn" value="Sign Up" name="signupbtn" onclick="submitForm()" />
            
          </form>
          
            
    </div>
    </div>

 <script>
  function submitForm(form){
    
    var url = $('#form').attr("action");
    
    var formData = $('#form').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
       window.location.replace("?page=verification_dashboard");
    }else if (data== 0){
      alert('sign up failed');
    } else {
        alert("email already registered");
    }
    });
}
</script> -->