<?php require $footer;?>	
    <div class="container-varification">
    <div class="login-content">
        <form action="<?php echo $controller ;?>" method="POST" id="form">
            <h2 class="title">Sign Up</h2>
            <div class="input-div one">
              <div class="i">
                <i class="fa fa-user"></i>
              </div>
              <div class="div">
                <h5>E-mail</h5>
                <input type="text" name="email" class="input" required />
              </div>
            </div>
            <div class="input-div pass">
              <div class="i">
                <i class="fa fa-lock"></i>
              </div>
              <div class="div">
                <h5>Password</h5>
                <input type="password" class="input" name="password" id="password" required />
              </div>
              
            </div>
            <div class="input-div pass">
                <div class="i">
                  <i class="fa fa-unlock-alt"></i>
                </div>
                <div class="div">
                  <h5>Confirm Password</h5>
                  <input type="password" name="confirm_Password" class="input" id="confirmPassword" required />
                </div>
            </div>
            <span id="message"></span>
           
            <input type="buttton" class="btn" value="Sign Up" name="signupbtn" onclick="submitForm()" />
            
          </form>
          
            
    </div>
    </div>

 <script>
  function submitForm(form){
    
    var url = $('#form').attr("action");
    
    var formData = $('#form').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
       window.location.replace("?page=verification_dashboard");
    }else if (data== 0){
      alert('sign up failed');
    } else {
        alert("email already registered");
    }
    });
}
</script>