<div class="wrapper">
    <div class="row">
        <div class="smtp-dashboard-main">
            <h1>SMTP Setting</h1>
        </div>
        <div class="smtp-dashboard">
            <div class="smtp-d-box">
                <div class="smtp-head">SMTP Settings</div>
                <div class="smtp-content">
                    <div class="smtp-content1">
                        <div class="smtp-head-c">Type</div>
                        <div class="smtp-head-input">
                            <select name="" id="">
                                <option value="1">Send Mail</option>
                                <option value="2">SMTP</option>
                                <option value="3">Mailgun</option>
                            </select>
                        </div>
                    </div>
                    <div class="smtp-content1">
                        <div class="smtp-head-c">MAIL HOST</div>
                        <div class="smtp-head-input">
                            <input type="text">
                        </div>
                    </div>
                    <div class="smtp-content1">
                        <div class="smtp-head-c">MAIL PORT</div>
                        <div class="smtp-head-input">
                            <input type="text">
                        </div>
                    </div>
                    <div class="smtp-content1">
                        <div class="smtp-head-c">MAIL USERNAME</div>
                        <div class="smtp-head-input">
                            <input type="text">
                        </div>
                    </div>
                    <div class="smtp-content1">
                        <div class="smtp-head-c">MAIL PASSWORD</div>
                        <div class="smtp-head-input">
                            <input type="text">
                        </div>
                    </div>
                    <div class="smtp-content1">
                        <div class="smtp-head-c">MAIL ENCRYPTION</div>
                        <div class="smtp-head-input">
                            <input type="text">
                        </div>
                    </div>
                    <div class="smtp-content1">
                        <div class="smtp-head-c">MAIL FROM ADDRESS</div>
                        <div class="smtp-head-input">
                            <input type="text">
                        </div>
                    </div>
                    <div class="smtp-content1">
                        <div class="smtp-head-c">MAIL FROM NAME</div>
                        <div class="smtp-head-input">
                            <input type="text">
                        </div>
                    </div>
                </div>
                <div class="smtp-btn">
                    <input type="button" value="SAVE">
                </div>
            </div>
        </div>
        <div class="smtp-dashboard-note">
            <div class="smtp-dashboard-note-box">
                <div class="smtp-dashboard-note-box-head">Instruction</div>
            </div>
            <div class="smtp-dashboard-note-box-dis">
                <p>Please be carefull when you are configuring SMTP. For incorrect configuration you will get error at the time of order place, new registration, sending newsletter.</p>
                <div class="smtp-dashboard-note-box-dis1">
                    <div class="smtp-dashboard-note-box-dis1-head">For Non-SSL</div>
                    <div class="smtp-dashboard-note-box-dis1-dis">
                        <p>Select sendmail for Mail Driver if you face any issue after configuring smtp as Mail Driver</p>
                        <p>Set Mail Host according to your server Mail Client Manual Settings</p>
                        <p>Set Mail port as 587</p>
                        <p>Set Mail Encryption as ssl if you face issue with tls</p>
                    </div>
                </div>
                <div class="smtp-dashboard-note-box-dis1">
                    <div class="smtp-dashboard-note-box-dis1-head">For SSL</div>
                    <div class="smtp-dashboard-note-box-dis1-dis">
                        <p>Select sendmail for Mail Driver if you face any issue after configuring smtp as Mail Driver</p>
                        <p>Set Mail Host according to your server Mail Client Manual Settings</p>
                        <p>Set Mail port as 465</p>
                        <p>Set Mail Encryption as ssl</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
