<div class="wrapper">
    <div class="row">
        <div class="social-media-dashboard-main">
            <h1 data-aos="fade-right"data-aos-duration="1500">Social Media</h1>
        </div>
        <div class="social-media-dashboard">
            <!-- Google Form Start -->
            <form action="<?= $controller; ?>" id="googleForm">
                <input type="hidden" name="googleForm" value="Google Form">
                <div class="social-media-dashboard-box" data-aos="fade-right"data-aos-duration="900">
                    <div class="social-media-dashboard-box-head">Google Login Credential</div>
                    <div class="social-media-dashboard-box-dis">
                        <div class="social-media-dashboard-box-dis-head">Client ID</div>
                        <div class="social-media-dashboard-box-dis-dis">
                            <input type="text" name="gclient_id">
                        </div>
                    </div>
                    <div class="social-media-dashboard-box-dis">
                        <div class="social-media-dashboard-box-dis-head">Client Secret</div>
                        <div class="social-media-dashboard-box-dis-dis">
                            <input type="text" name="gclient_secret">
                        </div>
                    </div>
                    <div class="social-media-dashboard-box-btn">
                        <input type="button" value="Save" onclick="submitFormGoogle()">
                    </div>
                </div>
            </form>
            <!-- Google Form End -->

            <!-- Facebook Form Start -->
            <form action="<?= $controller; ?>" id="facebookForm">
                <input type="hidden" name="facebookForm" value="Facebook Form">
                <div class="social-media-dashboard-box"data-aos="fade-left"data-aos-duration="900">
                    <div class="social-media-dashboard-box-head">Facebook Login Credential</div>
                    <div class="social-media-dashboard-box-dis">
                        <div class="social-media-dashboard-box-dis-head">App ID</div>
                        <div class="social-media-dashboard-box-dis-dis">
                            <input type="text" name="facebook_app_id">
                        </div>
                    </div>
                    <div class="social-media-dashboard-box-dis">
                        <div class="social-media-dashboard-box-dis-head">App Secret</div>
                        <div class="social-media-dashboard-box-dis-dis">
                            <input type="text" name="facebook_app_secret">
                        </div>
                    </div>
                    <div class="social-media-dashboard-box-btn">
                        <input type="button" value="Save" onclick="submitFormFacebook()">
                    </div>
                </div>
            </form>
            <!-- Facebook Form End -->

            <!-- Twitter Form Start -->
            <form action="<?= $controller; ?>" id="twitterForm">
                <input type="hidden" name="twitterForm" value="Twitter Form">
                <div class="social-media-dashboard-box" data-aos="fade-up"data-aos-duration="900">
                    <div class="social-media-dashboard-box-head">Twitter Login Credential</div>
                    <div class="social-media-dashboard-box-dis">
                        <div class="social-media-dashboard-box-dis-head">Client ID</div>
                        <div class="social-media-dashboard-box-dis-dis">
                            <input type="text" name="twitter_client_id">
                        </div>
                    </div>
                    <div class="social-media-dashboard-box-dis">
                        <div class="social-media-dashboard-box-dis-head">Client Secret</div>
                        <div class="social-media-dashboard-box-dis-dis">
                            <input type="text" name="twitter_client_secret">
                        </div>
                    </div>
                    <div class="social-media-dashboard-box-btn">
                        <input type="button" value="Save" onclick="submitFormTwitter()">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script>

  function submitFormGoogle(form){
    
        url = $('#googleForm').attr("action");
        formData = $('#googleForm').serializeArray();

        $.post(url, formData).done(function (data) {
        if(data == 1){
            alert('success');
        }else{
            alert('error');
        }
    });
  }

  function submitFormFacebook(form){
    
    url = $('#facebookForm').attr("action");
    formData = $('#facebookForm').serializeArray();

    $.post(url, formData).done(function (data) {
    if(data == 1){
        alert('success');
    }else{
        alert('error');
    }
});
}
  function submitFormTwitter(form){
    
    url = $('#twitterForm').attr("action");
    formData = $('#twitterForm').serializeArray();

    $.post(url, formData).done(function (data) {
    if(data == 1){
        alert('success');
    }else{
        alert('error');
    }
});
}
</script>