<div class="wrapper">
    <div class="row">
        <div class="social-media-dashboard-main">
            <h1>Social Media</h1>
        </div>
        <div class="social-media-dashboard">
            <div class="social-media-dashboard-box">
                <div class="social-media-dashboard-box-head">Google Login Credential</div>
                <div class="social-media-dashboard-box-dis">
                    <div class="social-media-dashboard-box-dis-head">Client ID</div>
                    <div class="social-media-dashboard-box-dis-dis">
                        <input type="text">
                    </div>
                </div>
                <div class="social-media-dashboard-box-dis">
                    <div class="social-media-dashboard-box-dis-head">Client Secret</div>
                    <div class="social-media-dashboard-box-dis-dis">
                        <input type="text">
                    </div>
                </div>
                <div class="social-media-dashboard-box-btn">
                    <input type="button">
                </div>
            </div>
            <div class="social-media-dashboard-box">
                <div class="social-media-dashboard-box-head">Facebook Login Credential</div>
                <div class="social-media-dashboard-box-dis">
                    <div class="social-media-dashboard-box-dis-head">App ID</div>
                    <div class="social-media-dashboard-box-dis-dis">
                        <input type="text">
                    </div>
                </div>
                <div class="social-media-dashboard-box-dis">
                    <div class="social-media-dashboard-box-dis-head">App Secret</div>
                    <div class="social-media-dashboard-box-dis-dis">
                        <input type="text">
                    </div>
                </div>
                <div class="social-media-dashboard-box-btn">
                    <input type="button">
                </div>
            </div>
            <div class="social-media-dashboard-box">
                <div class="social-media-dashboard-box-head">Twitter Login Credential</div>
                <div class="social-media-dashboard-box-dis">
                    <div class="social-media-dashboard-box-dis-head">Client ID</div>
                    <div class="social-media-dashboard-box-dis-dis">
                        <input type="text">
                    </div>
                </div>
                <div class="social-media-dashboard-box-dis">
                    <div class="social-media-dashboard-box-dis-head">Client Secret</div>
                    <div class="social-media-dashboard-box-dis-dis">
                        <input type="text">
                    </div>
                </div>
                <div class="social-media-dashboard-box-btn">
                    <input type="button">
                </div>
            </div>
        </div>
    </div>
</div>

