<div class="wrapper">
	<div class="row">
		<div class="sub-cat-two-dashboard-main">
			<h1 data-aos="fade-right" data-aos-duration="1500"><?php 
				echo getlang('','3rd Level Category',getlangcookie()); 
				?></h1>
			<a href="?page=category_dashboard" data-aos="fade-left" data-aos-duration="1500" class="sub-cat-two-back"><?php 
echo getlang('','Go Back to Main Categories',getlangcookie()); 
?></a>
		</div>
		<div class="sub-cat-three-dashboard" data-aos="zoom-in-right" data-aos-duration="1000">
			<label><?php 
echo getlang('','Category name',getlangcookie()); 
?>:</label>
			<form action="<?php echo $controller ?>" method="post" id="form">
				<?php 
					if(isset($_GET["id"])){
						$id = $_GET["id"];
					}
				?>
				<input name="categoryid"  type="text" value="<?php echo $id; ?>" hidden >
				<input class="sub-cat-three-input" name="category" value="" type="text" required>
				<input class="sub-cat-three-btn" type="button" name="addbtn" value="<?php 
echo getlang('','Add Category',getlangcookie()); 
?>" onclick="submitForm()" >
        	</form>
		</div>
		<div class="sub-cat-three-table" data-aos="zoom-out-up" data-aos-duration="1000">    
			<fieldset>
				<table class="table table-bordered" id="clientstable">		
					<thead class="bg-info">
						<th><?php 
				echo getlang('','Category ID',getlangcookie()); 
				?></th>
						<th><?php 
				echo getlang('','Category',getlangcookie()); 
				?></th>
						<th></th>
						<th></th>
					</thead>
					<tbody>
						<?php
							foreach($getcategory as $categorylist){
						?>		
						<tr>			
							<td><?php echo $categorylist["ssc_id"]; ?></td>
							<td><?php echo $categorylist["ss_category"]; ?></td>								
							<td><a href="?page=editcategorythree_dashboard&cat_id=<?php echo $id ?>&id=<?php echo $categorylist["ssc_id"]; ?>&name=<?php echo $categorylist["ss_category"]?>"><?php 
				echo getlang('','Edit',getlangcookie()); 
				?></a></td>
							<td><a href="<?php echo $controller  ?>?id=<?php echo $categorylist["ssc_id"]; ?>" onclick="return confirm('Are you sure?')"><?php 
				echo getlang('','Delete',getlangcookie()); 
				?></a></td>
						</tr>
						<?php } ?>
					</tbody>					
				</table>
			</fieldset>
		</div>            
	</div>
</div>


<script>
	function submitForm(form){
	var  validInput = $('input[name=category]').val();
    var url = $('#form').attr("action");
    var formData = $('#form').serializeArray();
	if(validInput == ""){
			alert('this field is required');
		}else{
    $.post(url, formData).done(function (data) {
       if(data == 1){
			        alert('sub category added');
			            location.reload(); 
		}else{
			alert('sub category not added');
		}
    });
}
}
</script>
