<div class="wrapper">
		<div class="row">
			<div class="col-3 col-m-6 col-sm-6">
            <h1>3rd level Category</h1>
              <label>Category name :</label>
                <form action="<?php echo $controller ?>" method="post" id="form">
                <?php 
                    if(isset($_GET["id"])){
                      $id = $_GET["id"];
                    }
                    
                    ?>
                    <input name="categoryid"  type="text" value="<?php echo $id; ?>" hidden >
					<input name="category" value="" type="text">
                <input type="button" name="addbtn" value="Add Category" onclick="submitForm()" >
        </form>
                    </div>
            <div>
            
					  <fieldset>
					  <table class="table table-bordered" id="clientstable">
					
						<thead class="bg-info">
							<th>Category ID</th>
							<th>Category</th>
							<th></th>
							<th></th>
                        </thead>
                   
					   <tbody>
						 <?php
								foreach($getcategory as $categorylist){
                           ?>
                        
						 
											
								
								<tr>
									
								<td><?php echo $categorylist["ssc_id"]; ?></td>
								<td><?php echo $categorylist["ss_category"]; ?></td>								
                                <td><a href="?page=editcategorythree_dashboard&cat_id=<?php echo $id ?>&id=<?php echo $categorylist["ssc_id"]; ?>&name=<?php echo $categorylist["ss_category"]?>">Edit</a></td>
								<td><a href="<?php echo $controller  ?>?id=<?php echo $categorylist["ssc_id"]; ?>" onclick="return confirm('Are you sure?')">Delete</a></td>
								
							   </tr>
								<?php } ?>
					   </tbody>	
							
					</table>
					  </fieldset>
            </div>
            
</div>
</div>


<script>
	function submitForm(form){
		
    var url = $('#form').attr("action");
		
    var formData = $('#form').serializeArray();
    $.post(url, formData).done(function (data) {
       if(data == 1){
			        alert('sub category added');
			            location.reload(); 
		}else{
			alert('sub category not added');
		}
    });
}
</script>
