<div class="wrapper">
    <div class="row">
        <div class="sub-dashboard-main">
        <h1 data-aos="fade-right"data-aos-duration="1500"><?php 
echo getlang('','All Subscribers',getlangcookie()); 
?>  </h1>
    </div>
    <div class="subs-main" data-aos="zoom-in-up" data-aos-duration="600">
        <form action="" method="POST">
            <table>
                <tr>
                    <th><?php 
echo getlang('','Serial.No',getlangcookie()); 
?>  </th>
                    <th><?php   
echo getlang('','E-mail',getlangcookie()); 
?>  </th>
                    <th><?php 
echo getlang('','Date',getlangcookie()); 
?>  </th>
                </tr>
                <tr>
                    <td>1</td>
                    <td>Muzzamilqureshi007@gmail.com</td>
                    <td>01/01/2021</td>
                </tr>
                <!-- <input type="submit" name="submit" value="Submit"> -->
            </table>
        </form>
    </div>        
</div>

    <div class="customer-list-btn-section">
<form method="POST">
        
<button name="submit">Export Data
</button>
    </div>
    </form>
</div>
<?php
if (isset($_POST['submit'])) {
    
    $myfile = fopen("subsriber.xls", "w") or die("Unable to open file!"); 
    $txt = "ID  | Customer Email |   Date | \n";
    fwrite($myfile, $txt);
    $txt = '1   Muzzamilqureshi007@gmail.com  01/01/2021';
    fwrite($myfile, $txt);
    fclose($myfile);

}



  ?>



