<div class="wrapper">
    <div class="row">
        <div class="sub-dashboard-main">
        <h1 data-aos="fade-right"data-aos-duration="1500">All Subscribers</h1>
    </div>
    <div class="subs-main" data-aos="zoom-in-up" data-aos-duration="600">
        <form action="">
            <table>
                <tr>
                    <th>Serial.No</th>
                    <th>E-main</th>
                    <th>Date</th>
                </tr>
                <tr>
                    <td>1</td>
                    <td>Muzzamilqureshi007@gmail.com</td>
                    <td>01/01/2021</td>
                </tr>
            </table>
        </form>
    </div>        
</div>
</div>

