<div class="wrapper">
    <div class="row">
        <div class="col-3 col-m-6 col-sm-6">
        <h1>All Subscribers</h1>
    </div>
    <div class="subs-main">
        <form action="">
            <table>
                <tr>
                    <th>Serial.No</th>
                    <th>E-main</th>
                    <th>Date</th>
                </tr>
                <tr>
                    <td>1</td>
                    <td>Muzzamilqureshi007@gmail.com</td>
                    <td>01/01/2021</td>
                </tr>
            </table>
        </form>
    </div>        
</div>
</div>

