<div class="wrapper">
    <div class="row">
        <div class="bluk-sms-dashboard">
            <h1 data-aos="fade-right"data-aos-duration="1500">Terms Of Service</h1>
        </div>
        <div class="bluk-sms-main" data-aos="zoom-in-up" data-aos-duration="600">
            <form action="<?= $controller; ?>" id="form"> 
                
                <div class="bluk-sms-form3">
                    <label>Write Your Terms of Service</label>
                    <textarea class="tinymce" id="myTextAreaSec" name="tos"></textarea>
                </div>
                <div class="bluk-sms-btn">
                    <input type="button" value="Update" onclick="submitForm()">
                </div>
            </form>
        </div>
    </div>
</div>
<script>
  function submitForm(form){
    var myContent = tinymce.get("myTextAreaSec").getContent();
      $('#myTextAreaSec').html(myContent);
    var url = $('#form').attr("action");
    
    var formData = $('#form').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
      alert('success');
    }else{
      alert('error');
    }
    });
}
</script>