<div class="wrapper">
    <div class="row">
        <div class="dashboard-footer">
            <h1 data-aos="fade-right" data-aos-duration="2000" >About Us</h1>
        </div>
        <div class="dashboard-footer-about" data-aos="zoom-out-right" data-aos-duration="1000">
            <form action="<?= $controller; ?>" class="d-footer-logo-about" id="formAbout">
                <input type="hidden" name="formAbout">
                <div class="dashboard-footer-about">
                    <div class="footer-about-upload-label">
                        <label for="">About Description :</label>
                    </div>
                    <div class="footer-about-upload-content">
                        <textarea name="theme_about_desc" id="myTextArea" class="tinymce"></textarea>
                    </div>
                </div>
                <div class="dashboard-footer-about-btn">
                    <input type="button" value="Upadate" onclick="submitFormAbout()">
                </div>
            </form>
        </div>
        
        </div>
    </div>
</div>
</div>
<script>
  function submitFormAbout(form){
    
    var url = $('#formAbout').attr("action");
    var myContent = tinymce.get("myTextArea").getContent();
      $('#myTextArea').html(myContent);
    
    var formData = $('#formAbout').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
      alert('success');
    }else{
      alert('error');
    }
    });
}
function submitFormVision(form){
    
    var url = $('#visionForm').attr("action");
    var myContent = tinymce.get("myTextAreaSec").getContent();
      $('#myTextAreaSec').html(myContent);
    
    var formData = $('#visionForm').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
      alert('success');
    }else{
      alert('error');
    }
    });
}
</script>
