<div class="wrapper">
    <div class="row">
        <div class="ticket-dashboard-main">
        <h1 data-aos="fade-right"data-aos-duration="1500"><?php 
echo getlang('','Ticket (Support Desk)',getlangcookie()); 
?>  </h1>
        <div class="ticket-view-table">
            <a href="?page=tickettable_dashboard"><?php 
echo getlang('','View Table',getlangcookie()); 
?>   <i class="fa fa-angle-right" aria-hidden="true"></i></a>
        </div>
    </div>
    <form class="ticket-content" action='<?= $controller; ?>' id="ticketForm">
        <div class="ticket-content">
            <div class="tk-content">
                <label><?php 
echo getlang('','Send Ticket to',getlangcookie()); 
?>  </label>
                <select>
                    <option value="1">Jhon</option>
                    <option value="2">Mike</option>
                    <option value="3">Jack</option>
                </select>
            </div>
        </div>
        <div class="ticket-content">
            <div class="tk-conetnt">
                <div class="ticket-div">
                    <label><?php 
echo getlang('','Ticket Title',getlangcookie()); 
?>  </label>
                    <input type="text">
                </div>
                <div class="ticket-div">
                    <label><?php 
echo getlang('','Ticket Discribtion',getlangcookie()); 
?>  </label>
                    <input type="text">
                </div>
            </div>
        </div>
        <div class="ticket-content">
            <div class="tk-btn">
                <input type="Button" value="<?php 
echo getlang('','Send',getlangcookie()); 
?>  ">
            </div>
        </div>
    </form>


</div>
</div>

<script>
    function submitticketForm(form){
    
    url = $('#ticketForm').attr("action");
    formData = $('#ticketForm').serializeArray();

    $.post(url, formData).done(function (data) {
    if(data == 1){
        alert('success');
    }else{
        alert('error');
    }
});
}

</script>