<div class="wrapper">
    <div class="row">
        <div class="ticket-dashboard-main">
            <h1 data-aos="fade-right"data-aos-duration="1500">Ticket Table</h1>
        </div>
        <div class="ticket-table">
            <table style="width:100%">
                <tr>
                    <th>Ticket Title <i class="fa fa-i-cursor" aria-hidden="true"></i></th>
                    <th>Ticket Form <i class="fa fa-reply-all" aria-hidden="true"></i></th>
                    <th>Options <i class="fa fa-cogs" aria-hidden="true"></i></th>
                </tr>
                <tr>
                    <td>Demo</td>
                    <td>Demo</td>
                    <td><a href="?page=ticketchat_dashboard">View <i class="fa fa-eye" aria-hidden="true"></i></a></td>
                </tr>
            </table>
        </div>


    </div>
</div>