<div class="wrapper">
    <div class="row">
        <div class="ticket-dashboard-main">
            <h1 data-aos="fade-right"data-aos-duration="1500">Ticket Chat</h1>
        </div>
        <div class="chat-dashboard-main" data-aos="zoom-in-up" data-aos-duration="600">
        <div id="wrapper">

          

            <div class="chat-content">
            <div id="menuChat">
                <p class="welcome">Welcome <br></p>

               
            </div>
 
            <div id="chatbox">
            Coversations
            </div>
            </div>
            <form class="chat-inner-btn" name="message" action="">
                <input class="chat-text-box" name="usermsg" type="text" id="usermsg" />
                <input class="chat-text-button" name="submitmsg" type="submit" id="submitmsg" value="Send" />
            </form>
        </div>
    </div>
</div>
</div>


    </div>
</div>