<div class="wrapper">
    <div class="row">
        <div class="ticket-dashboard-main">
        <h1 data-aos="fade-right"data-aos-duration="1500">Ticket (Support Desk)</h1>
        <div class="ticket-view-table">
            <a href="?page=tickettable_dashboard">View Table <i class="fa fa-angle-right" aria-hidden="true"></i></a>
        </div>
    </div>
    <form class="ticket-content" action='<?= $controller; ?>' id="ticketForm">
        <div class="ticket-content">
            <div class="tk-content">
                <label>Send Ticket to</label>
                <select name="sendto_ticket">
                    <option value="1">Jhon</option>
                    <option value="2">Mike</option>
                    <option value="3">Jack</option>
                </select>
            </div>
        </div>
        <div class="ticket-content">
            <div class="tk-conetnt">
                <div class="ticket-div">
                    <label>Ticket Title</label>
                    <input type="text" name="ticket_title">
                </div>
                <div class="ticket-div">
                    <label>Ticket Discribtion</label>
                    <input type="text" name="ticket-dis">
                </div>
            </div>
        </div>
        <div class="ticket-content">
            <div class="tk-btn">
                <input type="Button" value="Send" onclick="submitticketForm()">
            </div>
        </div>
    </form>


</div>
</div>

<script>
    function submitticketForm(form){
    
    url = $('#ticketForm').attr("action");
    formData = $('#ticketForm').serializeArray();

    $.post(url, formData).done(function (data) {
    if(data == 1){
        alert('success');
    }else{
        alert('error');
    }
});
}

</script>