<div class="wrapper">
    <div class="row">
        <div class="col-3 col-m-6 col-sm-6">
        <h1>Ticket (Support Desk)</h1>
    </div>
    <div class="ticket-main">
        <form action="">
            <table>
                <tr>
                    <th>Ticket ID</th>
                    <th>Sending Code</th>
                    <th>Subject</th>
                    <th>User</th>
                    <th>Status</th>
                    <th>Last Reply</th>
                    <th>Options</th>
                </tr>
                <tr>
                    <td>1234</td>
                    <td>01/01/2021</td>
                    <td>Delivery</td>
                    <td>Muzzamil</td>
                    <td>Pending</td>
                    <td>hi....</td>
                    <td>
                        <a href="#">1</a>
                        <a href="#">2</a>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>
</div>