
	  
	<!-- main content -->
	<div class="wrapper">
		<div class="row">
            <div class="dashboard-footer user-profile-header">
                <h1 data-aos="fade-right" data-aos-duration="2000" >User Profile</h1> 
                <div class="user-profile-upper">
                    <a href="?page=useredit_dashboard">Edit</a>
                </div>
            </div>
			<div class="user-profile-main-dashboard">
				<div class="container-content">
                   
                    <div class="user-profile-dis">
                       
                        <div class="user-detail1">
                            <div class="user-detail-content">
                                <label><i class="fa fa-id-card-o" aria-hidden="true"></i> First Name.</label>
                                <p class="first-name"> <?php if(isset($olddetails)){echo $olddetails[0]['first_name']; } ?></p>
                            </div>
                            <div class="user-detail-content">
                                <label><i class="fa fa-id-card" aria-hidden="true"></i> last Name.</label>
                                <p class="last-name">  <?php if(isset($olddetails)){echo $olddetails[0]['last_name']; } ?></p>
                            </div>
                            <div class="user-detail-content">
                                <label><i class="fa fa-mobile" aria-hidden="true"></i> contact No.</label>
                                <p class="Contact-no"><?php if(isset($olddetails)){echo $olddetails[0]['contact_no']; } ?></p>
                            </div>
                        </div>
                        <div class="user-detail2">
                            <div class="user-detail-content">
                                <label><i class="fa fa-map" aria-hidden="true"></i> Address.</label>
                                <p class="address-1"><?php if(isset($olddetails)){echo $olddetails[0]['address']; } ?></p>
                            </div>
                            <div class="user-detail-content">
                                <label><i class="fa fa-map-o" aria-hidden="true"></i> Address2.</label>
                                <p class="address-2"><?php if(isset($olddetails)){echo $olddetails[0]['address_2']; } ?></p>
                            </div>
                            <div class="user-detail-content">
                                <label><i class="fa fa-map-pin" aria-hidden="true"></i> City.</label>
                                <p class="city"><?php if(isset($olddetails)){echo $olddetails[0]['city']; } ?></p>
                            </div>
                            <div class="user-detail-content">
                                <label><i class="fa fa-map-marker" aria-hidden="true"></i> State.</label>
                                <p class="state"><?php if(isset($olddetails)){echo $olddetails[0]['state']; } ?></p>
                            </div>
                            <div class="user-detail-content">
                                <label><i class="fa fa-street-view" aria-hidden="true"></i> Zip Code.</label>
                                <p class="Zip-code"><?php if(isset($olddetails)){echo $olddetails[0]['zip']; } ?></p>
                            </div>
                            <div class="user-detail-content">
                                <label><i class="fa fa-globe" aria-hidden="true"></i> Country.</label>
                                <p class="Country"><?php if(isset($olddetails)){echo $olddetails[0]['country']; } ?></p>
                            </div>
                        </div>
                    </div>
                </div>
			</div>		
		</div>
	</div>
	<!-- end main content -->
