
	<!-- main content -->
	<?php require $footer;?>		
	<div class="wrapper">
		<div class="row">
            <div class="dashboard-footer user-profile-header">
                <h1 data-aos="fade-right" data-aos-duration="2000" >User Profile</h1> 
                <div class="user-profile-upper">
                    <input type="button" class="editbtn1" name="updatebtn" value="update" onclick="submitForm()"  />
                    <a class="editbtn2" href="?page=userprofile_dashboard">Cancel</a>
                </div>
            </div>
            
			<div class="user-edit-profile-main">
				<div class="user-content">
                    <div class="user-content-upper"></div>
                    <div class="user-content-dis">
                        <div class="container-content">
                            <form action="<?php echo $controller; ?>" method="POST" id="form">
                            
                            <div class="user-profile-dis">
                               
                                <div class="user-detail1">
                                    <label>First Name.</label>
                                    <input type="text" name="fname" value="<?php if(isset($olddetails)){echo $olddetails[0]['first_name']; } ?>">
                                    
                                    <label>last Name.</label>
                                    <input type="text" name="lname" value="<?php if(isset($olddetails)){echo $olddetails[0]['last_name']; } ?>">
                                    
                                    <label>contact No.</label>
                                    <input type="text" name="contactno" value="<?php if(isset($olddetails)){echo $olddetails[0]['contact_no']; } ?>">
                                </div>
                                <div class="edit-detail">
                                    <label>Address.</label>
                                    <input type="text" name="address" value="<?php if(isset($olddetails)){echo $olddetails[0]['address']; } ?>">
                                    <label>Address2.</label>
                                    <input type="text" name="address2" value="<?php if(isset($olddetails)){echo $olddetails[0]['address_2']; } ?>">
                                    <label>City.</label>
                                   <input type="text" name="city" value="<?php if(isset($olddetails)){echo $olddetails[0]['city']; } ?>">
                                    <label>State.</label>
                                   <input type="text" name="state" value="<?php if(isset($olddetails)){echo $olddetails[0]['state']; } ?>">
                                    <label>Zip Code.</label>
                                   <input type="text" name="zip" value="<?php if(isset($olddetails)){echo $olddetails[0]['zip']; } ?>">
                                    <label>Country.</label>
                                    <input type="text" name="country" value="<?php if(isset($olddetails)){echo $olddetails[0]['country']; } ?>">
                                </div>
                            </div>
                            </form>
                        </div>
                    </div>
                </div>
			</div>		
		</div>
	</div>
	<!-- end main content -->
<script>
	function submitForm(form){
		
    var url = $('#form').attr("action");
		
    var formData = $('#form').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
			alert("Updated Successfully");        
            window.location.replace("?page=userprofile_dashboard");
		}else if (data == 0){
			alert('User Record Not Updated');
		}
    });
}
</script>
