<div class="wrapper">
    <div class="row">
        <div class="pickup-dashboard-main">
            <h1 data-aos="fade-right"data-aos-duration="1500"><?php 
echo getlang('','User Search',getlangcookie()); 
?>  </h1>
            <!-- <form data-aos="fade-left"data-aos-duration="1500">
                <input type="text">
                <input class="s-btn" type="button" value="Search">
            </form> -->
        </div>
        <div class="pickup-table-main" data-aos="zoom-in-up" data-aos-duration="600">
            <form action="">
                <table>
                    <tr>
                        <th><?php 
echo getlang('','Serial.No',getlangcookie()); 
?>  </th>
                        <th><?php 
echo getlang('','Search by',getlangcookie()); 
?>   </th>
                        <th><?php 
echo getlang('','No. of Search',getlangcookie()); 
?>  </th>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>hoodie</td>
                        <td>11</td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>Pepsi</td>
                        <td>32</td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
</div>