
	<!-- main content -->
	<?php require $footer;?>		
	<div class="wrapper">
		<div class="row">
			<div class="col-12 col-m-12 col-sm-12">
				<div class="user-content">
                    <div class="user-content-upper"></div>
                    <div class="user-content-dis">
                        <div class="container-content">
                            <form action="<?php echo $controller; ?>" method="POST" id="form">
                            <div class="user-profile-upper">
                                 <input type="button" class="editbtn1" name="updatebtn" value="update" onclick="submitForm()"  />
                                <a class="editbtn2" href="?page=userprofile_dashboard">Cancel</a>
                            </div>
                            <div class="user-profile-dis">
                               
                                <div class="user-detail1">
                                    <label>First Name.</label>
                                    <input type="text" name="name" value="<?php if(isset($olddetails)){echo $olddetails[0]['name']; } ?>">
                                    
                                    <label>Email ID.</label>
                                    <input type="text" name="email" value="<?php if(isset($olddetails)){echo $olddetails[0]['email_id']; } ?>">
                                    
                                    <label>contact No.</label>
                                    <input type="text" name="contactno" value="<?php if(isset($olddetails)){echo $olddetails[0]['contact_no']; } ?>">
                                </div>
                                <div class="edit-detail">
                                    <label>Address.</label>
                                    <input type="text" name="address" value="<?php if(isset($olddetails)){echo $olddetails[0]['address']; } ?>">
                                    <label>Address2.</label>
                                    <input type="text" name="address2" value="<?php if(isset($olddetails)){echo $olddetails[0]['address_2']; } ?>">
                                    <label>City.</label>
                                   <input type="text"  value="<?php if(isset($olddetails)){echo $olddetails[0]['city']; } ?>">
                                    <label>State.</label>
                                   <input type="text"  value="<?php if(isset($olddetails)){echo $olddetails[0]['state']; } ?>">
                                    <label>Country.</label>
                                    <input type="text"  value="<?php if(isset($olddetails)){echo $olddetails[0]['country']; } ?>">
									<div class="frmDronpDown">
        <div class="row">
            <label>Country:</label><br /> <select name="country"
                id="country-list" 
                onChange="getStateforvendorprofile(this.value);">
                <option value disabled selected>Select Country</option>
<?php
foreach ($getcountries as $country) {
    ?>
<option value="<?php echo $country["id"]; ?>" ><?php echo $country["name"]; ?></option>
<?php
}
?>
</select>
        </div>
        <div class="row">
            <label>State:</label><br /> <select name="state"
                id="state-list" 
                onChange="getCityforvendorprofile(this.value);">
                <option value="">Select State</option>
          
            </select>
        </div>
        <div class="row">
            <label>City:</label><br /> <select name="city"
                id="city-list" >
                <option>Select City</option>
            </select>
        </div>
    </div>		
                                </div>
                            </div>
                            </form>
                        </div>
                    </div>
                </div>
			</div>		
		</div>
	</div>
	<!-- end main content -->
<script>
	function submitForm(form){
		
    var url = $('#form').attr("action");
		
    var formData = $('#form').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
			alert("Updated Successfully");        
            window.location.replace("?page=vendorprofile_dashboard");
		}else if (data == 0){
			alert('User Record Not Updated');
		}
    });
}
</script>
