<?php 
    $video_title = search_array('video Title',$config_system);
    $video_short_dis = search_array('video short dis',$config_system);
    $video_dis = search_array('video dis',$config_system);
?>

<div class="wrapper">
		<div class="row">
			<div class="bluk-sms-dashboard">
            <h1 data-aos="fade-right"data-aos-duration="1500">Video</h1>
        </div>
        <div class="bluk-sms-main" data-aos="zoom-in-up" data-aos-duration="600">
            <form action="<?= $controller; ?>" id="form"> 
                <div class="bluk-sms-form2">
                    <label>Title</label>
                    <input type="text" name="video_title" value="<?php echo $video_title['value'];?>">
                </div>
                <div class="bluk-sms-form2">
                    <label>Short Discribtion</label>
                    <input type="text" name="video_short_desc" value="<?php echo $video_short_dis['value'];?>">
                </div>
                <div class="bluk-sms-form2">
                    <label>Video</label>
                    <textarea name="video_video" id="myTextAreaSec" class="tinymce"><?php echo $video_dis['value'];?></textarea>
                </div>
                <div class="bluk-sms-btn">
                    <input type="button" value="Update" onclick="submitForm()">
                </div>
            </form>
        </div>
        <div class="help-center-dashboard-main">
            <form >
                <table>
                    <tr>
                        <th>Serial No.</th>
                        <th>Question</th>
                        <th>Option</th>                
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>whats???</td>
                        <td>
                            <a href="#">
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit
                            </a>
                            <a href="#">
                                <i class="fa fa-trash" aria-hidden="true"></i> Remove
                            </a>
                        </td>
                    </tr>                
                </table>
            </form>
        </div>
    </div>
</div>
<script>
  function submitForm(form){
    
    var url = $('#form').attr("action");
    
    var myContent = tinymce.get("myTextAreaSec").getContent();
      $('#myTextAreaSec').html(myContent);
    var formData = $('#form').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
      alert('success');
      location.reload();
    }else{
      alert('error');
    }
    });
}
</script>