<div class="wrapper">
    <div class="row">
        <div class="flashdeal-dashboard-main">
        <h1 data-aos="fade-right" data-aos-duration="1500">View Product</h1>
        <form data-aos="fade-down" data-aos-duration="1500">
            <input type="text">
            <input class="s-btn" type="button" value="Search">
        </form>

    </div>
    <div class="Flashdeal-table-main" data-aos="zoom-out-up" data-aos-duration="600">
        <form action="">
            <table>
                <tr>
                    <th>Serial.No</th>
                    <th>Product Name</th>
                    <th>Discription</th>
                    <th>Product Image</th>
                    <th>Purchase Price</th>
                    <th>Price</th>
                    <th>Qty Purchase</th>
                    <th>Qty Remains</th>
                    <th>Category</th>
                    <th>Category 2nd Level</th>
                    <th>Category 3rd Level</th>
                    <th>Featured?</th>
                    <th>Publish?</th>
                    <th>Option</th>
                </tr>
                <?php  
                        if (!empty($data)){
                            
                            $count = 1;
                            
                            foreach ($data as $key => $value) {
                                 $product_image  = getproductsimages($value['product_id']);  
                                 $product_name   = getviewproduct($value['vb_id']);
                                 $category       = getcategorybyid($value['category_id']);
                                 $subcategory = getsubcategorybyid($value['sc_id']);
                                 $subsubcategory = getsubsubcategorybyid($value['ssc_id']);
                                 $price          = getproductinfo($value['product_id']);
                                 if(empty($subcategory)){
                                    $subcategory = '-';
                                 }else{
                                    $subcategory = $subcategory[0]['sub_category'];

                                 }
                                 if(empty($subsubcategory)){
                                    $subsubcategory = '-';
                                 }else{
                                    $subsubcategory = $subsubcategory[0]['ss_category'];

                                 }

                                $is_featured =  $value['is_featured'];

                                $publish =  $value['publish'];


                                if($is_featured == 1){
                                    $is_featured = 'Yes';
                                }else{
                                    $is_featured = 'No';
                                }


                                if($publish == 1){
                                    $publish = 'Yes';
                                }else{
                                    $publish = 'No';
                                }
                                // //$date           = getabandoncart($value['user_id']);
                                 //var_dump($value);
                                 //var_dump($category);
                            
                        ?> 
                <tr>
                    <td><?= $count; ?></td>
                    <td><?= $value['name']; ?></td>
                    <td>
                    <?= $value['description']; ?>
                    </td>
                    <td>
                    <img src="<?= $product_directory.$product_image[0]['image_path'] ?>" alt="">
                    </td>
                    <td><?= $value['purchase_price'] ?></td>
                    <td><?= $value['price'] ?></td>
                    <td><?= $value['quantity_purchase'] ?></td>
                    <td><?= $value['quantity'] ?></td>
                    <td><?= $category[0]['name'] ?></td>
                    <td><?= $subcategory ?></td>
                    <td><?= $subsubcategory ?></td>
                     <td><?= $is_featured ?></td>
                      <td><?= $publish ?></td>
                    <td class="option">
                        <a href="?page=addnewproduct_dashboard&product_name=<?= $value['name']; ?>&product_id=<?= $value['product_id']; ?>&product_desc=<?= $value['description']; ?>&product_qty=<?= $value['quantity']; ?>&product_sell=<?= $value['price']?>&product_purchase=<?= $value ['purchase_price']?>&product_weight=<?= $value['weight']?>&product_feature=<?= $value['is_featured']?>&product_publish=<?= $value['publish']?>&product_cat=<?= $category[0]['name'] ?>&product_cat_sub=<?= $subcategory?>&product_cat_ssub=<?= $subsubcategory?>&product_img= <?= $product_directory.$product_image[0]['image_path']?>">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit
                        </a>
                    </td>
                </tr>
                <?php  
                    $count ++;
                } }  ?>
            </table>
        </form>
    </div>
</div>
</div>