<div class="wrapper">
		<div class="row">
			<div class="col-3 col-m-6 col-sm-6">
            <h1>View Branch</h1>

            <table>
            	<tr>
            		<td>Username</td>
            		<td>Name</td>
            		<td>Contact No</td>
            		<td>Email</td>
            		<td>Address</td>
                        <td>Status</td>
            		<td>Action </td>
            	</tr>

<?php
$admin = NULL;
foreach ($branch as $key => $value) {

      $status = $value['status'];

      if($status == 0){

            $approval = 'NOT APPROVED';
            if($admin || $owner){
$action = '<a href="../app/xhr/approve.php?branch_id='.$value['branch_id'].'&user_id='.$value['user_id'].'&vendor_id='.$value['vendor_id'].'&action=approve&type=branch">Approve</a>';
            }
      }else{
              if($admin || $owner){
$action = '<a href="../app/xhr/approve.php?branch_id='.$value['branch_id'].'&user_id='.$value['user_id'].'&vendor_id='.$value['vendor_id'].'&action=block&type=branch">Block</a>';
            }
            $approval = 'APPROVED';
      }

	echo '<tr>'.'<td>'.$value['name'].'</td>'.'<td>'.$value['name'].'</td>'.'<td>'.$value['contact_no'].'</td>'.'<td>'.$value['email_id'].'</td>'.'<td>'.$value['address'].$value['address_2'].'</td>'.'<td>'.$approval .'</td>'.'<td>Edit | Delete |'. $action . ' </td></tr>';
}


?>

            </table>
</div>
</div>
</div>