

<div class="dashboard">

<!-- main content -->
<div class="wrapper">
    <div class="section-upper-cust">
        <div class="section-content">
            <div class="cust-card-1">
                <div class="cust-name">
                <i class="fa fa-user" aria-hidden="true"></i>
                    <h3>Muzzamil Qureshi</h3>
                </div>
            </div>
            <div class="cust-card-2">
                <div class="cust-card-upper">
                    <p>3</p>
                    <p>Product</p>
                </div>
                <div class="cust-card-lower">
                    <p>in your cart</p>
                </div>
            </div>
            <div class="cust-card-3">
                <div class="cust-card-upper">
                    <p>2</p>
                    <p>Product</p>
                </div>
                <div class="cust-card-lower">
                    <p>in your Wishlist</p>
                </div>
            </div>
            <div class="cust-card-4">
                <div class="cust-card-upper">
                    <p>10</p>
                    <p>Product</p>
                </div>
                <div class="cust-card-lower">
                    <p>you Order</p>
                </div>
            </div>
        </div>
    </div>
    <div class="section-upper-mid">
        <div class="section-mid-info-content">
            <div class="section-mid-info-btn">
                <a href="#editSec" class="edit-cust"><i class="fa fa-pencil" aria-hidden="true"></i> Edit</a>
            </div>
            <div class="section-mid-info-detail">
                <div class="detail-1">
                    <div class="detail-head">Name :</div>
                    <div class="detail-decs">Muzzamil Qureshi</div>
                </div>
                <div class="detail-2">
                    <div class="detail-head">E-mail :</div>
                    <div class="detail-decs">bunniqureshi007@gmail.com</div>
                </div>
                <div class="detail-3">
                    <div class="detail-head">Phone :</div>
                    <div class="detail-decs">+92 349 0950536</div>
                </div>
                <div class="detail-4">
                    <div class="detail-head">Country :</div>
                    <div class="detail-decs">Pakistan</div>
                </div>
                <div class="detail-3">
                    <div class="detail-head">Date Of Birth :</div>
                    <div class="detail-decs">10 / 08 / 1997</div>
                </div>
                <div class="detail-4">
                    <div class="detail-head">Address :</div>
                    <div class="detail-decs">suitno.711, 7th floor , K.S Tower Shah-e-liquat Road opp Asakari Bank New Challie Neare Acard Squard , Saddar Karachi.</div>
                </div>
            </div>
        </div>
    </div>
    <section class="section-upper-low" id="editSec">
        <div class="section-lower-content">
            <div class="section-lower-content-heading">Profile Detail</div>
            <div class="section-lower-content-desc">
                <form action="" class="section-lower-detail-form">
                    <div class="input-section-1">
                        <div class="section-heading">Name :</div>
                        <div class="section-input">
                            <input type="text">
                        </div>
                    </div>
                    <div class="input-section-2">
                        <div class="section-heading">E-mail :</div>
                        <div class="section-input">
                            <input type="email">
                        </div>
                    </div>
                    <div class="input-section-3">
                        <div class="section-heading">Phone :</div>
                        <div class="section-input">
                            <input type="number">
                        </div>
                    </div>
                    <div class="input-section-4">
                        <div class="section-heading">Country :</div>
                        <div class="section-input">
                            <input type="text">
                        </div>
                    </div>
                    <div class="input-section-3">
                        <div class="section-heading">Date Of Birth :</div>
                        <div class="section-input">
                            <input type="date">
                        </div>
                    </div>

                    <div class="input-section-5">
                        <div class="section-heading">Address :</div>
                        <div class="section-input">
                            <textarea name="" id="" cols="30" rows="10"></textarea>
                        </div>
                    </div>
                    <div class="input-section-6">
                        <input class="btn-1" type="submit" value="Update">
                        <input class="btn-2" value="Cancel">
                    </div>

                </form>
            </div>
        </div>
    </section>
</div>
</div>

