<div class="wrapper">
    <div class="row">
        <div class="chat-main">
        <h1 data-aos="fade-right"data-aos-duration="1500">Conversation Between (Admin & User)</h1>
    </div>
    <div class="chat-dashboard-main" data-aos="zoom-in-up" data-aos-duration="600">
        <form action="">
            <div class="conver-upper-main">
                <div class="conver-upper-main-right">
                    <img src="" alt="no-img">
                </div>
                <div class="conver-upper-main-left">
                    <div class="conver-upper-main-name">
                        Admin
                    </div>
                    <div class="conver-upper-main-date">
                        01/01/2020 03:00 PM
                    </div>
                    <div class="conver-upper-main-name">
                        URL: www.demo.com
                    </div>
                </div>
            </div>
            <div class="conver-content-main">
                <textarea></textarea>
            </div>
            <div class="conver-content-btn">
                <input type="button" value="Send">
            </div>
        </form>
    </div>
</div>
</div>