<div class="wrapper">
    <div class="row">
        <div class="chat-main">
        <h1 data-aos="fade-right"data-aos-duration="1500">Conversation</h1>
    </div>
    <div class="chat-dashboard-main" data-aos="zoom-in-up" data-aos-duration="600">
<div id="wrapper">
            <div class="chat-content">
            <div id="menuChat">
                <p class="welcome">Welcome, <br><!-- <b><?php echo $_SESSION['name']; ?></b> --></p>
                <!-- <p class="logout"><a id="exit" href="#">Exit Chat</a></p> -->
            </div>
 
            <div id="chatbox">
            Coversations
            </div>
            </div>
            <form class="chat-inner-btn" name="message" action="">
                <input class="chat-text-box" name="usermsg" type="text" id="usermsg" />
                <input class="chat-text-button" name="submitmsg" type="submit" id="submitmsg" value="Send" />
            </form>
        </div>
    </div>
</div>
</div>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript">
            // jQuery Document
            $(document).ready(function () {
                $("#submitmsg").click(function () {
                    var clientmsg = $("#usermsg").val();
                    $.post("../app/lib/chat.php", { text: clientmsg });
                    $("#usermsg").val("");
                    return false;
                });
 
                function loadLog() {
                    var oldscrollHeight = $("#chatbox")[0].scrollHeight - 20; //Scroll height before the request
                    var postForm = { //Fetch form data
                       
            'user_id'     :  '<?php echo $_GET['user_id'] ;?>',
            'branch_id'     :  '<?php echo $_SESSION['branch_id']  ?>' //Store name fields value
        };
                    
                    $.ajax({
                        type : 'POST',
                        url: "../app/lib/getchat.php",
                        data : postForm,
                        cache: false,
                        success: function (html) {
                            $("#chatbox").html(html); //Insert chat log into the #chatbox div
 
                            //Auto-scroll           
                            var newscrollHeight = $("#chatbox")[0].scrollHeight - 20; //Scroll height after the request
                            if(newscrollHeight > oldscrollHeight){
                                $("#chatbox").animate({ scrollTop: newscrollHeight }, 'normal'); //Autoscroll to bottom of div
                            }   
                        }
                    });
                }
 
                setInterval (loadLog, 1500);
 
                $("#exit").click(function () {
                    var exit = confirm("Are you sure you want to end the session?");
                    if (exit == true) {
                    window.location = "index.php?logout=true";
                    }
                });
            });
        </script>