<div class="wrapper">
    <div class="row">
        <div class="flashdeal-dashboard-main">
        <h1 data-aos="fade-right" data-aos-duration="1500">View Product</h1>
        <form data-aos="fade-down" data-aos-duration="1500">
            <input type="text">
            <input class="s-btn" type="button" value="Search">
        </form>

    </div>
    <div class="Flashdeal-table-main" data-aos="zoom-out-up" data-aos-duration="600">
        <form action="">
            <table>
                <tr>
                    <th>Serial.No</th>
                    <th>Product Name</th>
                    <th>Discribtion</th>
                    <th>Product Image</th>
                    <th>Price</th>
                    <th>Qty</th>
                    <th>Category</th>
                    <th>Category 2nd Level</th>
                    <th>Category 3rd Level</th>
                    <th>Option</th>
                </tr>
                <tr>
                    <td>1</td>
                    <td>Ikea Chair</td>
                    <td>
                        metal with soft lether
                    </td>
                    <td>
                    <img src="https://demo.sirv.com/chair.jpg?scale.width=71  " alt="">
                    </td>
                    <td>30 $</td>
                    <td>2</td>
                    <td>Home</td>
                    <td>Living Room</td>
                    <td>Chair</td>
                    <td class="option">
                        <a href="?page=addnewproduct_dashboard">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit
                        </a>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>
</div>