<div class="wrapper">
      <div class="row">
            <div class="viewbranch-dashboard-main">
                 <h1 data-aos="fade-right" data-aos-duration="1500">View Branch</h1>
            </div>
            <div class="view-branch-main" data-aos="fade-up" data-aos-duration="900">
                  <table>
            	      <tr>
                             
                              <th><?php 
echo getlang('','Branch Name',getlangcookie()); 
?>    </th>
                              <th><?php 
echo getlang('','Branch Url',getlangcookie()); 
?>    </th>
                              <th><?php 
echo getlang('','Contact No',getlangcookie()); 
?>    </th>
                              <th><?php 
echo getlang('','Email',getlangcookie()); 
?>    </th>
                              <th><?php 
echo getlang('','Address',getlangcookie()); 
?>    </th>
                              <th><?php 
echo getlang('','Status',getlangcookie()); 
?>    </th>
                              <th><?php 
echo getlang('','Action',getlangcookie()); 
?>     </th>
                  	</tr>
                        <?php
                        $admin = NULL;
                        foreach ($branch as $key => $value) {

                              $url = getthemeurl($value['branch_id']);
                              if(empty($url[0]['domain_url'])){
                                    $newurl = null;
                              }else{
                                     $newurl = $url[0]['domain_url'];
                              }
                              $url = '?domain=' . $newurl;
                              $status = $value['status'];
                              if($status == 0){
                                    $approval = 'NOT APPROVED';
                                    if($admin || $owner){
                        $action = '<a href="../app/xhr/approve.php?branch_id='.$value['branch_id'].'&user_id='.$value['user_id'].'&vendor_id='.$value['vendor_id'].'&action=approve&type=branch">Approve</a>';
                                    }
                              }else{
                                    if($admin || $owner){
                        $action = '<a href="../app/xhr/approve.php?branch_id='.$value['branch_id'].'&user_id='.$value['user_id'].'&vendor_id='.$value['vendor_id'].'&action=block&type=branch">Block</a>';
                                    }
                                    $approval = 'APPROVED';
                              }
                              echo '<tr>'.'<td>'.$value['name'].'</td>'.'<td>'.$url.'</td>'.'<td>'.$value['contact_no'].'</td>'.'<td>'.$value['email_id'].'</td>'.'<td>'.$value['address'].$value['address_2'].'</td>'.'<td>'.$approval .'</td>'.'<td> <a href="#"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</a><a href="../app/xhr/delete.php?action=vendor&vendor_id='.$value['vendor_id'].'"><i class="fa fa-trash" aria-hidden="true"></i> Remove</a>'. $action . ' </td></tr>';
                        }
                        ?>
                  </table>
            </div>
      </div>
</div>