
<style>
body{margin:0px;padding:0px;}
footer{background: #252525; margin-top:10px;}
.container{max-width: 1280px;margin: auto;}
.footer_content{display: flex;align-items: center;justify-content: center;padding:10px 0px;transition: .3s ease;}
.footer_content:hover{letter-spacing: 4px;}
.footer_content a{font-size: 20px;text-decoration: none;color: white;}
</style>

<footer>
    <div class="container">
        <div class="footer_content">
           <a href="#">ServeWise 2020</a> 
        </div>
    </div>
</footer>
